#!/bin/bash

mkdir -p Incompressible
cd Incompressible
mkdir -p Canal_plan_bi_periodique_M1 Canal_plan_bi_periodique_M10 Canal_plan_bi_periodique_M100 Canal_plan_bi_periodique_M1_tetraedrise Canal_plan_bi_periodique_M1bis_tetraedrise


cd Canal_plan_bi_periodique_M1
cp ../../Canal_plan_bi_periodique_M1.data .
cp ../../Canal_plan_bi_periodique_M1.msh.gz .
gunzip -f Canal_plan_bi_periodique_M1.msh.gz
ln -sf ../../post_run .

cd ../Canal_plan_bi_periodique_M10
cp ../../Canal_plan_bi_periodique_M1.data .
sed "s/Transformer dom x y z/Transformer dom 10*x y z/" Canal_plan_bi_periodique_M1.data  > temp.data
sed "s/segment 50  0.00025 0.0 0.00025	0.00025 0.004 0.00025/segment 50  0.0025 0.0 0.00025	0.0025 0.004 0.00025/g" temp.data > Canal_plan_bi_periodique_M10.data
rm -f Canal_plan_bi_periodique_M1.data temp.data
ln -sf ../../pre_run .
ln -sf ../../Canal_plan_bi_periodique_M1.msh.gz  .

cd ../Canal_plan_bi_periodique_M100
cp ../../Canal_plan_bi_periodique_M1.data .
sed "s/Transformer dom x y z/Transformer dom 100*x y z/" Canal_plan_bi_periodique_M1.data  > temp.data
sed "s/segment 50  0.00025 0.0 0.00025	0.00025 0.004 0.00025/segment 50  0.025 0.0 0.00025	0.025 0.004 0.00025/g" temp.data > Canal_plan_bi_periodique_M100.data
rm -f Canal_plan_bi_periodique_M1.data temp.data
ln -sf ../../Canal_plan_bi_periodique_M1.msh.gz  .
ln -sf ../../pre_run .

cd ../Canal_plan_bi_periodique_M1_tetraedrise
cp ../../Canal_plan_bi_periodique_M1_tetraedrise.data .
ln -sf ../../Canal_plan_bi_periodique_M1.msh.gz  .
ln -sf ../../post_run .

cd ../Canal_plan_bi_periodique_M1bis_tetraedrise
cp ../../Canal_plan_bi_periodique_M1_tetraedrise.data .
sed "s/Nombre_de_Noeuds 5   5   3/Nombre_de_Noeuds 7 7 4/" Canal_plan_bi_periodique_M1_tetraedrise.data > Canal_plan_bi_periodique_M1bis_tetraedrise.data
rm Canal_plan_bi_periodique_M1_tetraedrise.data
ln -sf ../../Canal_plan_bi_periodique_M1.msh.gz  .
ln -sf ../../post_run .
exit 0
