#!/bin/bash

Echantillonner()
{
   fic_a_echantillonner=$1
   
   $TRUST_Awk -v ech=$echantillon 'BEGIN {r=0;Nu=0;i=1;j=0}
     {
	while (1)
        {
	   if ($1<ech*i)
           {
	      j+=1
	      r+=$1
	      Nu+=$2
           }
	   else
	   {
	      if (j!=0)
	      {
	         printf "%1.8e\t%1.8e\n", r/j, Nu/j
	      }
	      j=0
	      r=0
	      Nu=0
	      i+=1
	   }
	   if (getline==0)
	   {
	      break
	   }
	}
     }' $fic_a_echantillonner >> fichier_Nusselt.plot
   
   rm -f $fic_a_echantillonner
}

Calculer_Nusselt()
{
   fichier=`ls *_Nusselt.face`
   if [ "$fichier" == "" ]
   then
      echo "No file found for Nusselt calculation !"
      exit
   fi
   if [ ! -s $fichier ]
   then
      echo "File $fichier is empty !"
      exit
   fi
   
   ligne=`grep -n "Bord PLATE" $fichier | tail -1 | $TRUST_Awk '{print $1+5}'`
   nbligne=`wc -l $fichier | $TRUST_Awk '{print $1-2}'`
   ligne=`$TRUST_Awk "BEGIN{print $nbligne-$ligne}"`
   
   head -$nbligne $fichier | tail -$ligne | $TRUST_Awk -v D=$D -v lambda=$lambda -v Re=$Re  '{printf "%1.8f\t%1.8f\n",sqrt($1*$1+$3*$3)/D, $11*D/lambda/(Re**0.7)}' | sort > .fichier_Nusselt.plot
   
   echo "# Points (X, Y, r, h, Nu) tels que lus dans le fichier $fichier" > fichier_Nusselt.plot
   echo "# Nu = h.D/lambda, avec D=$D, lambda=$lambda et Re=$Re" >> fichier_Nusselt.plot
   echo "# r/D		Nu/Re^0.7" >> fichier_Nusselt.plot
   
   Echantillonner .fichier_Nusselt.plot
}

Calculer_Uplus()
{
   cd Prepare
     extrait_coupe Prepare SONDE_VENTREE
     Utau=`grep "<u\*>" *_pb_Ustar.face | tail -1 | $TRUST_Awk '{print $NF}'`
     $TRUST_Awk -v Utau=$Utau -v D=$D -v mu=$mu -v rho=$rho '{print (D/2-$1)*Utau/(mu/rho) "\t" sqrt($2*$2+$3*$3+$4*$4)/Utau }' Prepare_SONDE_VENTREE.coupe > Uplus.out
     sed 's?0$?supprimer?g' Uplus.out > Uplus.tmp
     sed '/supprimer/d' Uplus.tmp > Uplus.out
     rm -f Uplus.tmp
   cd ../
}

Calculer_Utau()
{
   cd Prepare
     Utau=`grep "<u\*>" *_pb_Ustar.face | tail -1 | $TRUST_Awk '{print $NF}'`
     $TRUST_Awk -v Utau=$Utau -v D=$D -v mu=$mu -v rho=$rho -v Re=$Re 'BEGIN{printf "%1.5f\t%1.5f\t%1.2f\n",sqrt(1/2*0.079/Re^0.25*(mu*Re/rho/D)^2),Utau,(sqrt(1/2*0.079/Re^0.25*(mu*Re/rho/D)^2)-Utau)/Utau*100}' > Utau.tab
   cd ../
}

Calculer_Ucl()
{
   cd Prepare
     Ucl_triou=`tail -1 Prepare_SONDE_VENTREE.son | $TRUST_Awk '{printf "%1.5f",($2*$2+$3*$3+$4*$4)**0.5}'`
     Ucl_ref=`$TRUST_Awk -v D=$D -v mu=$mu -v rho=$rho -v Re=$Re 'BEGIN{printf "%1.5f",(mu*Re/rho/D)/(0.811+0.038*(log(Re)/log(10)-4))}'`
     Ecart=`$TRUST_Awk -v Ut=$Ucl_triou -v Ur=$Ucl_ref 'BEGIN{printf "%1.2f",(Ut-Ur)/Ut*100}'`
     echo "$Ucl_ref	$Ucl_triou	$Ecart" > Ucl.tab
   cd ../
}

# Caracteristique de l'air a 20°C
rho=1.210
mu=1.815e-5
lambda=0.02565
# Caracteristique geometrique
D=0.0265
# Caracteristique echantillonnage
echantillon=0.1
# Calcul du Reynolds
Re=`grep "Re = " Prepare/Prepare.data | $TRUST_Awk '{print $(NF-1)}'`

Calculer_Nusselt
Calculer_Uplus
Calculer_Utau
Calculer_Ucl
