#!/bin/bash


temps6=`ls spectre_3D_tot_6.* | sed -e 's/spectre_3D_tot_//g'  | sort -g -r | tail -1`

cp "spectre_3D_tot_"$temps6 Ec_k_tr6.dat

fs_moyen=`cat thi.dt_ev | awk 'BEGIN{m=0;n=0;}{if ($1>20) {n++;m+=$3;}}END{print m/n;}'`
dt_moyen=`cat thi.dt_ev | awk 'BEGIN{m=0;n=0;}{if ($1>20) {n++;m+=$2;}}END{print m/n;}'`
fs_moyen20=`tail -20 thi.dt_ev | awk 'BEGIN{m=0;n=0;}{n++;m+=$3;}END{print m/n;}'`
dt_moyen20=`tail -20 thi.dt_ev | awk 'BEGIN{m=0;n=0;}{n++;m+=$2;}END{print m/n;}'`

dt_conv=`grep -A 2 "Printing of the next provisional time steps for the equation: Navier_Stokes_Turbulent" thi.out | grep convective | tail -20|  awk 'BEGIN{m=0;n=0;}{n++;m+=$5;}END{print m/n;}'`
dt_diffNS=`grep -A 2 "Printing of the next provisional time steps for the equation: Navier_Stokes_Turbulent" thi.out | grep diffusive | tail -20|  awk 'BEGIN{m=0;n=0;}{n++;m+=$5;}END{print m/n;}'`

fs_conv=`echo "scale=8;$dt_moyen20/$dt_conv" | bc`
fs_diffNS=`echo "scale=8;$dt_moyen20/$dt_diffNS" | bc`

echo  $fs_moyen20  " " $fs_conv " " $fs_diffNS  > comp_facsec 
