#!/bin/bash

lata_analyzer marqueurs.lata writelata_convert=output.lata asciiout

grep TEMPS output.lata |awk '{printf "%1.10f\n", $2}' > file_temps
rm -f val_out

limit=$(wc -l file_temps | awk '{print $1}')
limit=$(expr $limit + 1)

if [[ "$limit" == "1" ]]
then
	echo "file_temps file is empty, problem reading lata datas."
	exit
fi

i=1
while test $i -ne $limit
do
	temps=`head -$i file_temps|tail -1`
	fichier=output.lata.PARTICULES.${temps}
	echo $temps $fichier
	# z analytique:
	val=`awk "BEGIN{print -2.4729715*($temps+0.45045*(exp(-2.22*$temps)-1.))+1.}"` 
	[ `head -1 $fichier` == 3 ] && echo $temps" "`head -2 $fichier |tail -1`" "$val >> val_out
	i=$(($i+1)) 
done
exit
#val=`awk "BEGIN{print -($temps+0.45045*exp(-2.22*$temps))+1.45045}"`
#val=`awk "BEGIN{print -1.635*$temps*$temps+1.}"`
#val=`awk "BEGIN{print (0.079577472*(1-cos(2*3.14159265358979323846*$temps)))+0.5}"`
