Statistiques de post resolution

Temps total                       2.48613


Timesteps                         1
Secondes / pas de temps           2.22008
Dont solveurs Ax=B                0.101005  4% (20 appels/pas de temps)
Dont operateurs convection        0.002731  0% (207 appels/pas de temps)
Dont operateurs diffusion         0.790144 35% (3 appels/pas de temps)
Dont operations postraitement     0.042037  1% (2 appels/pas de temps)
Dont calcul divers                -0.906148 -40% (0 appels/pas de temps)
Nb echange_espace_virtuel / pas de temps 2541
Nb solveur / pas de temps         20
Secondes / solveur                0.00505025
Iterations / solveur              31.05
I/O:

Timesteps = number of time steps
Nb solveur = number of linear system resolutions
Nb assemblage implicite = number of matrix assemblies for the implicit scheme
Iterations = average number of iterations of the solver
Communications = fraction of the time spent
                 in communications between processors (excluding io files)
Network latency = time of one mpsum measured by an internal bench over 0.1s
Network bandwidth = maximum on all processors
                    of the average bandwidth of send_recv operations
Waiting time = estimation of the waiting time of the different processors

Max_waiting_time big    => probably due to a bad partitioning
Communications > 30%    => too many processors or network too slow

Statistiques de post resolution

Temps total                       2.61291


Timesteps                         1
Secondes / pas de temps           2.31366
Dont solveurs Ax=B                0.105311  4% (20 appels/pas de temps)
Dont operateurs convection        0.002841  0% (207 appels/pas de temps)
Dont operateurs diffusion         0.838207 36% (3 appels/pas de temps)
Dont operations postraitement     0.043949  1% (2 appels/pas de temps)
Dont calcul divers                -0.957671 -41% (0 appels/pas de temps)
Nb echange_espace_virtuel / pas de temps 2568
Nb solveur / pas de temps         20
Secondes / solveur                0.00526555
Iterations / solveur              31.5
I/O:

Timesteps = number of time steps
Nb solveur = number of linear system resolutions
Nb assemblage implicite = number of matrix assemblies for the implicit scheme
Iterations = average number of iterations of the solver
Communications = fraction of the time spent
                 in communications between processors (excluding io files)
Network latency = time of one mpsum measured by an internal bench over 0.1s
Network bandwidth = maximum on all processors
                    of the average bandwidth of send_recv operations
Waiting time = estimation of the waiting time of the different processors

Max_waiting_time big    => probably due to a bad partitioning
Communications > 30%    => too many processors or network too slow

