#!/bin/bash
#construction tableau recapitulatif
cp ../VDF/NoFlow-lami-espece_VDF_FRACTION_MASSIQUE0.son .
cp ../VDF/NoFlow-lami-espece_VDF_FRACTION_MASSIQUE1.son .
cp ../VDF/NoFlow-lami-espece_VDF_MASSE_VOLUMIQUE1.son .
cp ../VDF/NoFlow-lami-espece_VDF_MASSE_VOLUMIQUE2.son .
cp ../analyticResults.dat .
python ../ligneTableau-specie1.py
python ../ligneTableau-specie2.py
python ../ligneTableau-density.py
mv ligneTableau-specie1.dat ../.
mv ligneTableau-specie2.dat ../.
mv ligneTableau-density.dat ../.
