#!/bin/bash

#Creation des repertoires
cd Bulle

LISTE_CAS="Cas_01 Cas_02"
LISTE_MESH="M1 M2 M3 M4 M5"

for CAS in $LISTE_CAS ; do
 for MESH in $LISTE_MESH ; do
  
  REP=./$CAS/$MESH
  mkdir -p $REP
  cp ../post_run $REP
  SRCDATA=FTD_Oscillation_Bulle_3D_VDF.data
  SRCMESH=decoupage.data
  DESTDATA=$REP/$SRCDATA
  DESTMESH=$REP/$SRCMESH

  if test "$CAS" = "Cas_01" ; then
	if test "$MESH" = "M1" ; then
	  cp $SRCMESH $DESTMESH
	  sed "s/facsec 1./facsec 0.91/" $SRCDATA > $DESTDATA

	elif test "$MESH" = "M2" ; then
	  sed "s/Nombre_de_Noeuds 43 43 43/Nombre_de_Noeuds 61 61 61/;
	       s/tranches 2 1 1/tranches 2 2 1/" $SRCMESH > $DESTMESH
	  sed "s/facsec 1./facsec 0.46/" $SRCDATA > $DESTDATA

	elif test "$MESH" = "M3" ; then
	  sed "s/Nombre_de_Noeuds 43 43 43/Nombre_de_Noeuds 86 86 86/;
	       s/tranches 2 1 1/tranches 3 3 3/" $SRCMESH > $DESTMESH
	  sed "s/facsec 1./facsec 0.25/" $SRCDATA > $DESTDATA

	elif test "$MESH" = "M4" ; then
	  sed "s/Nombre_de_Noeuds 43 43 43/Nombre_de_Noeuds 121 121 121/;
	       s/tranches 2 1 1/tranches 5 4 2/" $SRCMESH > $DESTMESH
	  sed "s/facsec 1./facsec 0.1/" $SRCDATA > $DESTDATA

	else #M5 
	  sed "s/Nombre_de_Noeuds 43 43 43/Nombre_de_Noeuds 170 170 170/;
	       s/tranches 2 1 1/tranches 5 5 5/" $SRCMESH > $DESTMESH
	  sed "s/facsec 1./facsec 0.02/" $SRCDATA > $DESTDATA
	fi


  else # Cas_02 
	if test "$MESH" = "M1" ; then
	   cp $SRCMESH $DESTMESH
	   sed "s/facsec 1./facsec 0.78/;
		s/lissage_courbure_iterations 10/lissage_courbure_iterations_systematique 1 lissage_courbure_iterations_si_remaillage 5/;
		s/critere_remaillage 0.20/critere_remaillage 0.35/;
		s/lissage_courbure_coeff -0.1/lissage_courbure_coeff -0.05/;
		s/facteur_longueur_ideale 0.8/facteur_longueur_ideale 1./" $SRCDATA > $DESTDATA

	elif test "$MESH" = "M2" ; then
	   sed "s/Nombre_de_Noeuds 43 43 43/Nombre_de_Noeuds 61 61 61/;
	        s/tranches 2 1 1/tranches 2 2 1/" $SRCMESH > $DESTMESH
	   sed "s/facsec 1./facsec 0.38/;
		s/lissage_courbure_iterations 10/lissage_courbure_iterations_systematique 1 lissage_courbure_iterations_si_remaillage 5/;
		s/critere_remaillage 0.20/critere_remaillage 0.35/;
		s/lissage_courbure_coeff -0.1/lissage_courbure_coeff -0.05/;
		s/facteur_longueur_ideale 0.8/facteur_longueur_ideale 1./" $SRCDATA > $DESTDATA

	elif test "$MESH" = "M3" ; then
	   sed "s/Nombre_de_Noeuds 43 43 43/Nombre_de_Noeuds 86 86 86/;
	        s/tranches 2 1 1/tranches 3 3 3/" $SRCMESH > $DESTMESH
	   sed "s/facsec 1./facsec 0.2/;
	       s/lissage_courbure_iterations 10/lissage_courbure_iterations_systematique 1 lissage_courbure_iterations_si_remaillage 5/;
	       s/critere_remaillage 0.20/critere_remaillage 0.35/;
	       s/lissage_courbure_coeff -0.1/lissage_courbure_coeff -0.05/;
	       s/facteur_longueur_ideale 0.8/facteur_longueur_ideale 1./" $SRCDATA > $DESTDATA

	elif test "$MESH" = "M4" ; then
	   sed "s/Nombre_de_Noeuds 43 43 43/Nombre_de_Noeuds 121 121 121/;
	       s/tranches 2 1 1/tranches 5 4 2/" $SRCMESH > $DESTMESH
	   sed "s/facsec 1./facsec 0.08/;
	       s/lissage_courbure_iterations 10/lissage_courbure_iterations_systematique 1 lissage_courbure_iterations_si_remaillage 5/;
	       s/lissage_courbure_coeff -0.1/lissage_courbure_coeff -0.05/;
	       s/critere_remaillage 0.20/critere_remaillage 0.35/;
	       s/facteur_longueur_ideale 0.8/facteur_longueur_ideale 1./" $SRCDATA > $DESTDATA 

	else #M5
	   sed "s/Nombre_de_Noeuds 43 43 43/Nombre_de_Noeuds 170 170 170/;
	       s/tranches 2 1 1/tranches 5 5 5/" $SRCMESH > $DESTMESH
	   sed "s/facsec 1./facsec 0.022/;
	       s/lissage_courbure_iterations 10/lissage_courbure_iterations_systematique 1 lissage_courbure_iterations_si_remaillage 5/;
	       s/critere_remaillage 0.20/critere_remaillage 0.35/;
	       s/lissage_courbure_coeff -0.1/lissage_courbure_coeff -0.05/;
	       s/facteur_longueur_ideale 0.8/facteur_longueur_ideale 1./" $SRCDATA > $DESTDATA
	fi
  fi
  cp pre_run $REP
 done
done

echo "prepare fini"
