#!/bin/bash
data=`pwd`
data=`basename $data`.data
vitesse_imposee="vitesse_imposee 0.1 0.1"
[ "`grep 'dimension 3' $data`" != "" ] && vitesse_imposee="vitesse_imposee 0.1 0.1 0.1"
sed "s?methode_transport loi_horaire loi?methode_transport $vitesse_imposee?g" $data > ref.data
data=${data%.data}
echo "Comparaison methode_transport vitesse_imposee et loi_horaire pour $data:"
# Calcul sequentiel
rm -f *lml *lata*
trust ref
