*************************************************************************************************
Statistiques de post resolution
Block divided into 2 parts:
Part 1: for each function, gives the percentage consumed by communications
Part 2: for each type of communication, gives the percentage of time spent in each function
        Note that some counters are nested within each other, 
        that's why the sum of the percentages does not necessarily add up to 100% in this part.
*************************************************************************************************



-----------------------------------------------------------------
                    Famille MPI_allreduce                         
-----------------------------------------------------------------
Temps total : 0s

-----------------------------------------------------------------
                    Famille MPI_sendrecv                           
-----------------------------------------------------------------
Temps total : 0s


*************************************************************************************************
Statistiques de post resolution
Block divided into 2 parts:
Part 1: for each function, gives the percentage consumed by communications
Part 2: for each type of communication, gives the percentage of time spent in each function
        Note that some counters are nested within each other, 
        that's why the sum of the percentages does not necessarily add up to 100% in this part.
*************************************************************************************************



-----------------------------------------------------------------
                    Famille MPI_allreduce                         
-----------------------------------------------------------------
Temps total : 0s

-----------------------------------------------------------------
                    Famille MPI_sendrecv                           
-----------------------------------------------------------------
Temps total : 0s


