#!/bin/sh

sed 's/__EXPRESSION_TO_PLOT__/simu_div_lambda_grad_t/g' instructions2.py > instructions_simu_div_lambda_grad_t.py
sed 's/__EXPRESSION_TO_PLOT__/ana_div_lambda_grad_t/g' instructions2.py  > instructions_ana_div_lambda_grad_t.py
sed 's/__EXPRESSION_TO_PLOT__/error_div_lambda_grad_t/g' instructions2.py  > instructions_error_div_lambda_grad_t.py

rm -f simu_div_lambda_grad_t????.curve && visit -nowin -cli -s instructions_simu_div_lambda_grad_t.py 
rm -f ana_div_lambda_grad_t????.curve && visit -nowin -cli -s instructions_ana_div_lambda_grad_t.py 
rm -f error_div_lambda_grad_t????.curve && visit -nowin -cli -s instructions_error_div_lambda_grad_t.py 
