#!/bin/bash

# source $TRUST_ROOT/Validation/Outils/Genere_courbe/scripts/scripts_validation.sh
ko=0
tar xzf reference.tgz

compare_lata ref/rho_g.lata lata/rho_g.lata --seuil 1.e-8
[ $? -ne 0 ] && echo "Failure of compare_lata to reference in $PWD" && ko=1

compare_lata lata/grad_I.lata lata/rho_g.lata --seuil 8.e-6
[ $? -ne 0 ] && echo "Failure of compare_lata between grad_I and rho_g options in $PWD" && ko=1

# Calcul pour verifier la reprise du champ de Temperature et de vitesse par le .sauv : 
compare_lata lata/rho_g.lata lata/repr1.lata --seuil 1.e-6 --dernier
[ $? -ne 0 ] && echo "Failure of compare_lata between rho_g and repr1 (by sauv) in $PWD" && ko=1

# Calcul pour verifier la reprise du champ de Temperature et de vitesse par relecture d'un med :
compare_lata lata/rho_g.lata lata/repr2.lata --seuil 1.e-6 --dernier
[ $? -ne 0 ] && echo "Failure of compare_lata between rho_g and repr2 (by reloading from med) in $PWD" && ko=1



exit $ko
