#!/bin/bash

trust -copy ChFrontLu_gen_file_Turbulent
jdd=ChFrontLu_gen_file_Turbulent.data
cp -f ChFrontLu_gen_file_Turbulent/*.geom .
cp -f ChFrontLu_gen_file_Turbulent/$jdd .
rm -rf ChFrontLu_gen_file_Turbulent

chmod +w $jdd
sed -i "s?nb_pas_dt_max 10?nb_pas_dt_max 1?g" $jdd
[ "$TRUST_DISABLE_MPI" != 1 ] && make_PAR.data $jdd
# On lance un calcul en sequentiel et parallele pour generer
# un .dat en sequentiel et un .dat en parallele pour tester
# la reprise
trust $jdd || exit -1
# Renomme un fichier .dat
mv `ls -rt pb_VITESSE_PERIO*dat | tail -1` pb_VITESSE_PERIO.dat
if [ "$TRUST_DISABLE_MPI" != 1 ]
then
    trust PAR_$jdd 2 || exit -1
fi
# Renomme un fichier .dat
mv `ls -rt pb_K_EPS_PERIO*dat | tail -1` pb_K_EPS_PERIO.dat

