#!/bin/bash

#Creation des repertoires Convection Rotating Table
for etude in  crtable_crenel  crtable_gaussian  ; do
		for timesh in EE02 EE05 RK3 CN ; do
			for conv in Amont Muscl EF_stab EF_stab02 ; do
				mkdir -p ./$etude/$timesh/$conv
			done;
		done;
done;

RACINE=`pwd`

echo $RACINE


#cas de base : Muscl & CN & creneau
cd $RACINE/crtable_crenel/CN/Muscl
cp $RACINE/test_crt.data .


##
#CAS CRENEAU
#-----------
#  
#    
#	CN 
cd $RACINE/crtable_crenel/CN/Muscl
mv test_crt.data test.data
cp $RACINE/post_run .

#      Amont
cd $RACINE/crtable_crenel/CN/Amont
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { amont }/" test_crt.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
rm -rf test_crt.data

#      EF_stab alpha=1
cd $RACINE/crtable_crenel/CN/EF_stab
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { EF_stab { } }/" test_crt.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data

#      EF_stab alpha=0.2
cd $RACINE/crtable_crenel/CN/EF_stab02
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { EF_stab { alpha 0.2 } }/" test_crt.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data

#    RK3
#      
cd $RACINE/crtable_crenel/RK3/Muscl
cp $RACINE/test_crt.data .
sed "s/Sch_CN_iteratif sch/Runge_kutta_ordre_3 sch/" test_crt.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data

#      Amont
cd $RACINE/crtable_crenel/RK3/Amont
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { amont }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data

#      EF_stab alpha=1
cd $RACINE/crtable_crenel/RK3/EF_stab
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { EF_stab { } }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data

#      EF_stab alpha=0.2
cd $RACINE/crtable_crenel/RK3/EF_stab02
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { EF_stab { alpha 0.2 } }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data

#    EE05
#      
cd $RACINE/crtable_crenel/EE05/Muscl
cp $RACINE/test_crt.data .
sed "s/facsec 1/facsec 0.5/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Schema_Euler_explicite sch/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data

#      Amont
cd $RACINE/crtable_crenel/EE05/Amont
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { amont }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Schema_Euler_explicite sch/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data

#      EF_stab alpha=1
cd $RACINE/crtable_crenel/EE05/EF_stab
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { EF_stab { } }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Schema_Euler_explicite sch/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data

#      EF_stab alpha=0.2
cd $RACINE/crtable_crenel/EE05/EF_stab02
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { EF_stab { alpha 0.2 } }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Schema_Euler_explicite sch/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data

#    EE02
#      
cd $RACINE/crtable_crenel/EE02/Muscl
cp $RACINE/test_crt.data .
sed "s/facsec 1/facsec 0.2/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Schema_Euler_explicite sch/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data
#      Amont
cd $RACINE/crtable_crenel/EE02/Amont
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { amont }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.2/" test.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Schema_Euler_explicite sch/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data
#      EF_stab alpha=1
cd $RACINE/crtable_crenel/EE02/EF_stab
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { EF_stab { } }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.2/" test.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Schema_Euler_explicite sch/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data
#      EF_stab alpha=0.2
cd $RACINE/crtable_crenel/EE02/EF_stab02
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { EF_stab { alpha 0.2 } }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.2/" test.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Schema_Euler_explicite sch/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data

#--------------------------------------------------------------------------------------------
#CAS gaussien
#-----------
#
#	CN 
cd $RACINE/crtable_gaussian/CN/Muscl
cp $RACINE/test_crt.data .
sed "s/(x>(-0.1))\*(x<0.1)\*(y>0.5)\*(y<0.7)/EXP(-100\*(x\*x+(y-0.6)\*(y-0.6)))/" test_crt.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data
#      Amont
cd $RACINE/crtable_gaussian/CN/Amont
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { amont }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/(x>(-0.1))\*(x<0.1)\*(y>0.5)\*(y<0.7)/EXP(-100\*(x\*x+(y-0.6)\*(y-0.6)))/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data
#      EF_stab alpha=1
cd $RACINE/crtable_gaussian/CN/EF_stab
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { EF_stab { } }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/(x>(-0.1))\*(x<0.1)\*(y>0.5)\*(y<0.7)/EXP(-100\*(x\*x+(y-0.6)\*(y-0.6)))/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data
#      EF_stab alpha=0.2
cd $RACINE/crtable_gaussian/CN/EF_stab02
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { EF_stab { alpha 0.2 } }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/(x>(-0.1))\*(x<0.1)\*(y>0.5)\*(y<0.7)/EXP(-100\*(x\*x+(y-0.6)\*(y-0.6)))/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data
#    RK3
#      
cd $RACINE/crtable_gaussian/RK3/Muscl
cp $RACINE/test_crt.data .
sed "s/Sch_CN_iteratif sch/Runge_kutta_ordre_3 sch/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/(x>(-0.1))\*(x<0.1)\*(y>0.5)\*(y<0.7)/EXP(-100\*(x\*x+(y-0.6)\*(y-0.6)))/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data
#      Amont
cd $RACINE/crtable_gaussian/RK3/Amont
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { amont }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>(-0.1))\*(x<0.1)\*(y>0.5)\*(y<0.7)/EXP(-100\*(x\*x+(y-0.6)\*(y-0.6)))/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data
#      EF_stab alpha=1
cd $RACINE/crtable_gaussian/RK3/EF_stab
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { EF_stab { } }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>(-0.1))\*(x<0.1)\*(y>0.5)\*(y<0.7)/EXP(-100\*(x\*x+(y-0.6)\*(y-0.6)))/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data
#      EF_stab alpha=0.2
cd $RACINE/crtable_gaussian/RK3/EF_stab02
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { EF_stab { alpha 0.2 } }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>(-0.1))\*(x<0.1)\*(y>0.5)\*(y<0.7)/EXP(-100\*(x\*x+(y-0.6)\*(y-0.6)))/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data

#    EE05
#      
cd $RACINE/crtable_gaussian/EE05/Muscl
cp $RACINE/test_crt.data .
sed "s/facsec 1/facsec 0.5/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Schema_Euler_explicite sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>(-0.1))\*(x<0.1)\*(y>0.5)\*(y<0.7)/EXP(-100\*(x\*x+(y-0.6)\*(y-0.6)))/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data
#      Amont
cd $RACINE/crtable_gaussian/EE05/Amont
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { amont }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Schema_Euler_explicite sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>(-0.1))\*(x<0.1)\*(y>0.5)\*(y<0.7)/EXP(-100\*(x\*x+(y-0.6)\*(y-0.6)))/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data
#      EF_stab alpha=1
cd $RACINE/crtable_gaussian/EE05/EF_stab
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { EF_stab { } }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Schema_Euler_explicite sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>(-0.1))\*(x<0.1)\*(y>0.5)\*(y<0.7)/EXP(-100\*(x\*x+(y-0.6)\*(y-0.6)))/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data
#      EF_stab alpha=0.2
cd $RACINE/crtable_gaussian/EE05/EF_stab02
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { EF_stab { alpha 0.2 } }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Schema_Euler_explicite sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>(-0.1))\*(x<0.1)\*(y>0.5)\*(y<0.7)/EXP(-100\*(x\*x+(y-0.6)\*(y-0.6)))/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data

#    EE02
#      
cd $RACINE/crtable_gaussian/EE02/Muscl
cp $RACINE/test_crt.data .
sed "s/facsec 1/facsec 0.2/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Schema_Euler_explicite sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>(-0.1))\*(x<0.1)\*(y>0.5)\*(y<0.7)/EXP(-100\*(x\*x+(y-0.6)\*(y-0.6)))/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data
#      Amont
cd $RACINE/crtable_gaussian/EE02/Amont
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { amont }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.2/" test.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Schema_Euler_explicite sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>(-0.1))\*(x<0.1)\*(y>0.5)\*(y<0.7)/EXP(-100\*(x\*x+(y-0.6)\*(y-0.6)))/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data
#      EF_stab alpha=1
cd $RACINE/crtable_gaussian/EE02/EF_stab
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { EF_stab { } }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.2/" test.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Schema_Euler_explicite sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>(-0.1))\*(x<0.1)\*(y>0.5)\*(y<0.7)/EXP(-100\*(x\*x+(y-0.6)\*(y-0.6)))/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data
#      EF_stab alpha=0.2
cd $RACINE/crtable_gaussian/EE02/EF_stab02
cp $RACINE/test_crt.data .
sed "s/convection { muscl }/convection { EF_stab { alpha 0.2 } }/" test_crt.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.2/" test.data > modifie.data
mv modifie.data test.data
sed "s/Sch_CN_iteratif sch/Schema_Euler_explicite sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>(-0.1))\*(x<0.1)\*(y>0.5)\*(y<0.7)/EXP(-100\*(x\*x+(y-0.6)\*(y-0.6)))/" test.data > modifie.data
mv modifie.data test.data
rm -rf test_crt.data
