#!/bin/bash

# source $TRUST_ROOT/Validation/Outils/Genere_courbe/scripts/scripts_validation.sh
ko=0
tar xzf ref.tgz

compare_lata ./ref/rho_g_Texplicite.lata ./lata/rho_g_Texplicite.lata --dernier
[ $? -ne 0 ] && echo "Failure of compare_lata rho_g_Texplicite to reference in $PWD" && ko=1

compare_lata ./ref/rho_g_Timplicite_lowDT.lata ./lata/rho_g_Timplicite_lowDT.lata --dernier
[ $? -ne 0 ] && echo "Failure of compare_lata rho_g_Timplicite_lowDT to reference in $PWD" && ko=1

# On peut voir sur la sonde qu'avec le pas de temps relaxe grace a l'implicitation de la diffusion on peut passer avec un grand dt.
# Mais ATTENTION, dans ce cas, le couplage NS/T via boussinesq est moins bien resolu 
# plot "FTD_Boussinesq_Cylindrical_Buoyant_Steady_State_rhog_Timplicite_T_POINTS.son" u 1:2 w l, "" u 1:3 w l, "" u 1:4 w l
compare_lata ./ref/rho_g_Timplicite.lata ./lata/rho_g_Timplicite.lata --dernier
[ $? -ne 0 ] && echo "Failure of compare_lata rho_g_Timplicite to reference in $PWD" && ko=1

# rho_g et grad_I n'ont pas exactement les memes temps. Je ne comprends pas pourquoi.
# Eh rho_g, le solveur ne trouve pas vraiment 0 meme sans boussinesq. Il est plus sensible au seuil du solveur de pression
# On fait une verif assez laxiste:
compare_lata ./ref/rho_g_Timplicite.lata lata/grad_I_Timplicite.lata --seuil 6e-5
[ $? -ne 0 ] && echo "Failure of compare_lata between rho_g and grad_I options in $PWD" && ko=1

# Calcul pour verifier la reprise du champ de Temperature et de vitesse par le .sauv : 
# Le seuil doit etre un peu lache car la solution evolue encore car elle n'est pas encore steadystate
compare_lata ./ref/rho_g_Timplicite.lata lata/repr1.lata --seuil 1.e-6 --dernier
[ $? -ne 0 ] && echo "Failure of compare_lata between rho_g and repr1 (by sauv) in $PWD" && ko=1

# Calcul pour verifier la reprise du champ de Temperature et de vitesse par relecture d'un med :
compare_lata ./ref/rho_g_Timplicite.lata lata/repr2.lata --seuil 1.e-6 --dernier
[ $? -ne 0 ] && echo "Failure of compare_lata between rho_g and repr2 (by reloading from med) in $PWD" && ko=1



exit $ko
