#!/bin/bash
# Ce script est execute apres chaque cas tests (depuis leur repertoire)
[ -f $1.lml ] && gzip -f $1.lml
src=$project_directory/share/Validation/Rapports_automatiques/Multiphase/Front_tracking_IJK/IJK_FT/canal_perio_monoph/src
source $project_directory/env_for_PyTools.sh 
python $src/profils_turb.py
