#!/bin/bash
# echo $ECHO_OPTS "Build the different meshes...\c"
# trust BuildMeshes 1>BuildMeshes.out 2>&1
# if [ $? = 0 ]
# then
#    echo OK
# else
#    echo KO. See `pwd`/BuildMeshes.out
#    exit -1
# fi

# echo $ECHO_OPTS "Run the RANS parallel calculation in the box...\c"
# trust PeriodicBoxRANS 2 1>PeriodicBoxRANS.out 2>&1 || exit -1
# if [ $? = 0 ]
# then
#    echo OK
# else
#    echo KO. See `pwd`/PeriodicBoxRANS.out
#    exit -1
# fi
# echo $ECHO_OPTS "Run the LES parallel calculation in the box...\c"
# trust PeriodicBoxLES 2 1>PeriodicBoxLES.out 2>&1 || exit -1
# if [ $? = 0 ]
# then
#    echo OK
# else
#    echo KO. See `pwd`/PeriodicBoxLES.out
#    exit -1
# fi
