#!/bin/bash

# P1 #
sed "s/Read dis { P0 }/Read dis { P1 }/" NoFlow_P0_Ra1.data >   NoFlow_P1_Ra1.data
sed "s/Read dis { P0 }/Read dis { P1 }/" NoFlow_P0_Ra100.data > NoFlow_P1_Ra100.data

# P0P1 #
sed "s/Read dis { P0 }/Read dis { P0 P1 }/" NoFlow_P0_Ra1.data >   NoFlow_P0P1_Ra1.data
sed "s/Read dis { P0 }/Read dis { P0 P1 }/" NoFlow_P0_Ra100.data > NoFlow_P0P1_Ra100.data

# P0RT #
sed "s/Read dis { P0 }/Read dis { P0 RT }/" NoFlow_P0_Ra1.data >   NoFlow_P0RT_Ra1.data
sed "s/Read dis { P0 }/Read dis { P0 RT }/" NoFlow_P0_Ra100.data > NoFlow_P0RT_Ra100.data

# Folders & Data files generation #

Parameter="Ra1 Ra100"
Discretization="P0 P1 P0P1 P0RT"
for Discr in $Discretization ; do
  for Ra in $Parameter ; do
    for num in `seq 1 3`; do

        fold="mesh_"$num"/"$Discr"/"$Ra
        mkdir -p $fold

        MeshFile="Square_h"$num
	if [ $(basename $project_directory) == "P1NCP0RT" ]   
	then
	    ln -sfn $project_directory/share/Validation/Rapports_automatiques/mesh/$MeshFile".med" $fold/.
	else
	    ln -sfn $P1NCP0RT_project_directory/share/Validation/Rapports_automatiques/mesh/$MeshFile".med" $fold/.
	fi
             
        DataFile="NoFlow_"$Discr"_"$Ra".data"
        cp  $DataFile $fold/NoFlow.data
        sed -i "s/ Square_h1.med/ $MeshFile.med/" $fold/NoFlow.data
    done
  done
done
