/****************************************************************************
* Copyright (c) 2015 - 2016, CEA
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
* 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
* 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
* 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
* OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*****************************************************************************/
/////////////////////////////////////////////////////////////////////////////
//
// File      : OpConvIJKAmont.cpp
// Directory : $IJK_ROOT/src/IJK/OpVDF
//
/////////////////////////////////////////////////////////////////////////////
#include <OpConvIJKAmont.h>
//
// WARNING: DO NOT EDIT THIS FILE! Only edit the template file OpConvIJKAmont.cpp.P
//
#include <Statistiques.h>





void OpConvAmontIJK_double::initialize(const IJK_Splitting& splitting)
{
  channel_data_.initialize(splitting);
}

void OpConvAmontIJK_double::calculer(const IJK_Field_double& inputx, const IJK_Field_double& inputy, const IJK_Field_double& inputz,
                                     const IJK_Field_double& vx, const IJK_Field_double& vy, const IJK_Field_double& vz,
                                     IJK_Field_double& dvx, IJK_Field_double& dvy, IJK_Field_double& dvz)
{
  vx_ = &vx;
  vy_ = &vy;
  vz_ = &vz;
  inputx_ = &inputx;
  inputy_ = &inputy;
  inputz_ = &inputz;

  compute_set(dvx, dvy, dvz);

  vx_ = vy_ = vz_ = inputx_ = inputy_ = inputz_ = 0;
}

void OpConvAmontIJK_double::ajouter(const IJK_Field_double& inputx, const IJK_Field_double& inputy, const IJK_Field_double& inputz,
                                    const IJK_Field_double& vx, const IJK_Field_double& vy, const IJK_Field_double& vz,
                                    IJK_Field_double& dvx, IJK_Field_double& dvy, IJK_Field_double& dvz)
{
  vx_ = &vx;
  vy_ = &vy;
  vz_ = &vz;
  inputx_ = &inputx;
  inputy_ = &inputy;
  inputz_ = &inputz;

  compute_add(dvx, dvy, dvz);

  vx_ = vy_ = vz_ = inputx_ = inputy_ = inputz_ = 0;
}

// Description: compute fluxes in direction x for velocity component x
//  for the layer of fluxes k_layer
// 4-th order centered convection scheme
void OpConvAmontIJK_double::compute_flux_x_vx(IJK_Field_local_double& resu, const int k_layer)
{
  // convected field
  const IJK_Field_local_double& src = *inputx_;
  // Convected vector field:
  ConstIJK_double_ptr src_ptr(src, 0, 0, k_layer);
  // Velocity in x direction (convecting velocity)
  ConstIJK_double_ptr vconvx_ptr(*vx_, 0, 0, k_layer);

  const int idir = 0;
  const int nx = src.ni() + 1;
  const int ny = src.nj();
  const int icompo = 0;

  // Result (fluxes in direction x for component x of the convected field)
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);



  const int global_k_layer = k_layer + channel_data_.offset_to_global_k_layer();
  // global index of the layer of flux of the wall
  //  (assume one walls at zmin and zmax)
  const int first_global_k_layer = channel_data_.first_global_k_layer_flux(icompo, idir);
  const int last_global_k_layer = channel_data_.last_global_k_layer_flux(icompo, idir);

  if (global_k_layer < first_global_k_layer || global_k_layer > last_global_k_layer)
    {
      // We are in the wall
      putzero(resu);
      return;
    }

  double half_surface = channel_data_.get_surface(k_layer, icompo, idir) * 0.5;
  {
    const int imax = nx;
    const int jmax = ny;
    const int vsize = Simd_double::size();
    for (int j = 0; ; j++)
      {
        for (int i = 0; i < imax; i += vsize)     // specific coding for uniform mesh in x and y: surfaces are constant on an xy plane
          {
            Simd_double vit_0,vit_1; // 2 adjacent velocity values
            src_ptr.get_left_center_x(i,vit_0,vit_1);
            // get convecting velocity
            Simd_double vconv0, vconv1;
            vconvx_ptr.get_left_center_x(i, vconv0, vconv1);

            // Average of the convecting velocity (copied from Eval_Amont_VDF_Face : not weighted)
            Simd_double psc = (vconv0 + vconv1) * half_surface;
            Simd_double upwind_velocity = select_double(psc, 0., vit_1 /* if psc < 0 */, vit_0 /* if psc > 0 */);
            Simd_double flux = psc * upwind_velocity;
            resu_ptr.put_val(i, flux);
          }
        // do not execute end_iloop at last iteration (because of assert on valid j+1)
        if (j+1==jmax)
          break;
        // instructions to perform to jump to next row
        src_ptr.next_j();
        resu_ptr.next_j();
        vconvx_ptr.next_j();
      }
  }
}

// Description: compute fluxes in direction x for velocity component y
//  for the layer of fluxes k_layer
// 4-th order centered convection scheme
void OpConvAmontIJK_double::compute_flux_x_vy(IJK_Field_local_double& resu, const int k_layer)
{
  // convected field
  const IJK_Field_local_double& src = *inputy_;
  // Convected vector field:
  ConstIJK_double_ptr src_ptr(src, 0, 0, k_layer);
  // Velocity in x direction (convecting velocity)
  ConstIJK_double_ptr vconvx_ptr(*vx_, 0, 0, k_layer);

  const int idir = 0;
  const int nx = src.ni() + 1;
  const int ny = src.nj();
  const int icompo = 1;
  // Result (fluxes in direction x for component y of the convected field)
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);



  const int global_k_layer = k_layer + channel_data_.offset_to_global_k_layer();
  // global index of the layer of flux of the wall
  //  (assume one walls at zmin and zmax)
  const int first_global_k_layer = channel_data_.first_global_k_layer_flux(icompo, idir);
  const int last_global_k_layer = channel_data_.last_global_k_layer_flux(icompo, idir);

  if (global_k_layer < first_global_k_layer || global_k_layer > last_global_k_layer)
    {
      // We are in the wall
      putzero(resu);
      return;
    }

  double half_surface = channel_data_.get_surface(k_layer, icompo, idir) * 0.5;
  {
    const int imax = nx;
    const int jmax = ny;
    const int vsize = Simd_double::size();
    for (int j = 0; ; j++)
      {
        for (int i = 0; i < imax; i += vsize)     // specific coding for uniform mesh in x and y: surfaces are constant on an xy plane
          {
            Simd_double vit_0,vit_1; // 2 adjacent velocity values
            src_ptr.get_left_center_x(i,vit_0,vit_1);
            // get convecting velocity
            Simd_double vconv0, vconv1;
            vconvx_ptr.get_left_center_y(i, vconv0, vconv1);

            // Average of the convecting velocity (copied from Eval_Amont_VDF_Face : not weighted)
            Simd_double psc = (vconv0 + vconv1) * half_surface;
            Simd_double upwind_velocity = select_double(psc, 0., vit_1 /* if psc < 0 */, vit_0 /* if psc > 0 */);
            Simd_double flux = psc * upwind_velocity;
            resu_ptr.put_val(i, flux);
          }
        // do not execute end_iloop at last iteration (because of assert on valid j+1)
        if (j+1==jmax)
          break;
        // instructions to perform to jump to next row
        src_ptr.next_j();
        resu_ptr.next_j();
        vconvx_ptr.next_j();
      }
  }
}

// Description: compute fluxes in direction x for velocity component z
//  for the layer of fluxes k_layer
// 4-th order centered convection scheme
void OpConvAmontIJK_double::compute_flux_x_vz(IJK_Field_local_double& resu, const int k_layer)
{
  // convected field
  const IJK_Field_local_double& src = *inputz_;
  // Convected vector field:
  ConstIJK_double_ptr src_ptr(src, 0, 0, k_layer);
  // Velocity in x direction (convecting velocity)
  ConstIJK_double_ptr vconvx_ptr(*vx_, 0, 0, k_layer);

  const int idir = 0;
  const int nx = src.ni() + 1;
  const int ny = src.nj();
  const int icompo = 2;
  // Result (fluxes in direction x for component z of the convected field)
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);



  const int global_k_layer = k_layer + channel_data_.offset_to_global_k_layer();
  // global index of the layer of flux of the wall
  //  (assume one walls at zmin and zmax)
  const int first_global_k_layer = channel_data_.first_global_k_layer_flux(icompo, idir);
  const int last_global_k_layer = channel_data_.last_global_k_layer_flux(icompo, idir);

  if (global_k_layer < first_global_k_layer || global_k_layer > last_global_k_layer)
    {
      // We are in the wall
      putzero(resu);
      return;
    }

  double half_surface = channel_data_.get_surface(k_layer, icompo, idir) * 0.5;
  {
    const int imax = nx;
    const int jmax = ny;
    const int vsize = Simd_double::size();
    for (int j = 0; ; j++)
      {
        for (int i = 0; i < imax; i += vsize)     // specific coding for uniform mesh in x and y: surfaces are constant on an xy plane
          {
            Simd_double vit_0,vit_1; // 2 adjacent velocity values
            src_ptr.get_left_center_x(i,vit_0,vit_1);
            // get convecting velocity
            Simd_double vconv0, vconv1;
            vconvx_ptr.get_left_center_z(i, vconv0, vconv1);

            // Average of the convecting velocity (copied from Eval_Amont_VDF_Face : not weighted)
            Simd_double psc = (vconv0 + vconv1) * half_surface;
            Simd_double upwind_velocity = select_double(psc, 0., vit_1 /* if psc < 0 */, vit_0 /* if psc > 0 */);
            Simd_double flux = psc * upwind_velocity;
            resu_ptr.put_val(i, flux);
          }
        // do not execute end_iloop at last iteration (because of assert on valid j+1)
        if (j+1==jmax)
          break;
        // instructions to perform to jump to next row
        src_ptr.next_j();
        resu_ptr.next_j();
        vconvx_ptr.next_j();
      }
  }
}

// Description: compute fluxes in direction y for velocity component x
//  for the layer of fluxes k_layer
// 4-th order centered convection scheme
void OpConvAmontIJK_double::compute_flux_y_vx(IJK_Field_local_double& resu, const int k_layer)
{
  // convected field
  const IJK_Field_local_double& src = *inputx_;
  // Convected vector field:
  ConstIJK_double_ptr src_ptr(src, 0, 0, k_layer);
  // Velocity in y direction (convecting velocity)
  ConstIJK_double_ptr vconvy_ptr(*vy_, 0, 0, k_layer);

  const int idir = 1;
  const int nx = src.ni();
  const int ny = src.nj() + 1;
  const int icompo = 0;

  // Result (fluxes in direction y for component x of the convected field)
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);



  const int global_k_layer = k_layer + channel_data_.offset_to_global_k_layer();
  // global index of the layer of flux of the wall
  //  (assume one walls at zmin and zmax)
  const int first_global_k_layer = channel_data_.first_global_k_layer_flux(icompo, idir);
  const int last_global_k_layer = channel_data_.last_global_k_layer_flux(icompo, idir);

  if (global_k_layer < first_global_k_layer || global_k_layer > last_global_k_layer)
    {
      // We are in the wall
      putzero(resu);
      return;
    }

  double half_surface = channel_data_.get_surface(k_layer, icompo, idir) * 0.5;
  {
    const int imax = nx;
    const int jmax = ny;
    const int vsize = Simd_double::size();
    for (int j = 0; ; j++)
      {
        for (int i = 0; i < imax; i += vsize)     // specific coding for uniform mesh in x and y: surfaces are constant on an xy plane
          {
            Simd_double vit_0,vit_1; // 2 adjacent velocity values
            src_ptr.get_left_center_y(i,vit_0,vit_1);
            // get convecting velocity
            Simd_double vconv0, vconv1;
            vconvy_ptr.get_left_center_x(i, vconv0, vconv1);

            // Average of the convecting velocity (copied from Eval_Amont_VDF_Face : not weighted)
            Simd_double psc = (vconv0 + vconv1) * half_surface;
            Simd_double upwind_velocity = select_double(psc, 0., vit_1 /* if psc < 0 */, vit_0 /* if psc > 0 */);
            Simd_double flux = psc * upwind_velocity;
            resu_ptr.put_val(i, flux);
          }
        // do not execute end_iloop at last iteration (because of assert on valid j+1)
        if (j+1==jmax)
          break;
        // instructions to perform to jump to next row
        src_ptr.next_j();
        resu_ptr.next_j();
        vconvy_ptr.next_j();
      }
  }
}

// Description: compute fluxes in direction y for velocity component y
//  for the layer of fluxes k_layer
// 4-th order centered convection scheme
void OpConvAmontIJK_double::compute_flux_y_vy(IJK_Field_local_double& resu, const int k_layer)
{
  // convected field
  const IJK_Field_local_double& src = *inputy_;
  // Convected vector field:
  ConstIJK_double_ptr src_ptr(src, 0, 0, k_layer);
  // Velocity in y direction (convecting velocity)
  ConstIJK_double_ptr vconvy_ptr(*vy_, 0, 0, k_layer);

  const int idir = 1;
  const int nx = src.ni();
  const int ny = src.nj() + 1;
  const int icompo = 1;
  // Result (fluxes in direction y for component y of the convected field)
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);



  const int global_k_layer = k_layer + channel_data_.offset_to_global_k_layer();
  // global index of the layer of flux of the wall
  //  (assume one walls at zmin and zmax)
  const int first_global_k_layer = channel_data_.first_global_k_layer_flux(icompo, idir);
  const int last_global_k_layer = channel_data_.last_global_k_layer_flux(icompo, idir);

  if (global_k_layer < first_global_k_layer || global_k_layer > last_global_k_layer)
    {
      // We are in the wall
      putzero(resu);
      return;
    }

  double half_surface = channel_data_.get_surface(k_layer, icompo, idir) * 0.5;
  {
    const int imax = nx;
    const int jmax = ny;
    const int vsize = Simd_double::size();
    for (int j = 0; ; j++)
      {
        for (int i = 0; i < imax; i += vsize)     // specific coding for uniform mesh in x and y: surfaces are constant on an xy plane
          {
            Simd_double vit_0,vit_1; // 2 adjacent velocity values
            src_ptr.get_left_center_y(i,vit_0,vit_1);
            // get convecting velocity
            Simd_double vconv0, vconv1;
            vconvy_ptr.get_left_center_y(i, vconv0, vconv1);

            // Average of the convecting velocity (copied from Eval_Amont_VDF_Face : not weighted)
            Simd_double psc = (vconv0 + vconv1) * half_surface;
            Simd_double upwind_velocity = select_double(psc, 0., vit_1 /* if psc < 0 */, vit_0 /* if psc > 0 */);
            Simd_double flux = psc * upwind_velocity;
            resu_ptr.put_val(i, flux);
          }
        // do not execute end_iloop at last iteration (because of assert on valid j+1)
        if (j+1==jmax)
          break;
        // instructions to perform to jump to next row
        src_ptr.next_j();
        resu_ptr.next_j();
        vconvy_ptr.next_j();
      }
  }
}

// Description: compute fluxes in direction y for velocity component z
//  for the layer of fluxes k_layer
// 4-th order centered convection scheme
void OpConvAmontIJK_double::compute_flux_y_vz(IJK_Field_local_double& resu, const int k_layer)
{
  // convected field
  const IJK_Field_local_double& src = *inputz_;
  // Convected vector field:
  ConstIJK_double_ptr src_ptr(src, 0, 0, k_layer);
  // Velocity in y direction (convecting velocity)
  ConstIJK_double_ptr vconvy_ptr(*vy_, 0, 0, k_layer);

  const int idir = 1;
  const int nx = src.ni();
  const int ny = src.nj() + 1;
  const int icompo = 2;
  // Result (fluxes in direction y for component z of the convected field)
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);



  const int global_k_layer = k_layer + channel_data_.offset_to_global_k_layer();
  // global index of the layer of flux of the wall
  //  (assume one walls at zmin and zmax)
  const int first_global_k_layer = channel_data_.first_global_k_layer_flux(icompo, idir);
  const int last_global_k_layer = channel_data_.last_global_k_layer_flux(icompo, idir);

  if (global_k_layer < first_global_k_layer || global_k_layer > last_global_k_layer)
    {
      // We are in the wall
      putzero(resu);
      return;
    }

  double half_surface = channel_data_.get_surface(k_layer, icompo, idir) * 0.5;
  {
    const int imax = nx;
    const int jmax = ny;
    const int vsize = Simd_double::size();
    for (int j = 0; ; j++)
      {
        for (int i = 0; i < imax; i += vsize)     // specific coding for uniform mesh in x and y: surfaces are constant on an xy plane
          {
            Simd_double vit_0,vit_1; // 2 adjacent velocity values
            src_ptr.get_left_center_y(i,vit_0,vit_1);
            // get convecting velocity
            Simd_double vconv0, vconv1;
            vconvy_ptr.get_left_center_z(i, vconv0, vconv1);

            // Average of the convecting velocity (copied from Eval_Amont_VDF_Face : not weighted)
            Simd_double psc = (vconv0 + vconv1) * half_surface;
            Simd_double upwind_velocity = select_double(psc, 0., vit_1 /* if psc < 0 */, vit_0 /* if psc > 0 */);
            Simd_double flux = psc * upwind_velocity;
            resu_ptr.put_val(i, flux);
          }
        // do not execute end_iloop at last iteration (because of assert on valid j+1)
        if (j+1==jmax)
          break;
        // instructions to perform to jump to next row
        src_ptr.next_j();
        resu_ptr.next_j();
        vconvy_ptr.next_j();
      }
  }
}

// Description: compute fluxes in direction z for velocity component x
//  for the layer of fluxes k_layer
// 4-th order centered convection scheme
void OpConvAmontIJK_double::compute_flux_z_vx(IJK_Field_local_double& resu, const int k_layer)
{
  // convected field
  const IJK_Field_local_double& src = *inputx_;
  // Convected vector field:
  ConstIJK_double_ptr src_ptr(src, 0, 0, k_layer);
  // Velocity in z direction (convecting velocity)
  ConstIJK_double_ptr vconvz_ptr(*vz_, 0, 0, k_layer);

  const int idir = 2;
  const int nx = src.ni();
  const int ny = src.nj();
  const int icompo = 0;

  // Result (fluxes in direction z for component x of the convected field)
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);



  const int global_k_layer = k_layer + channel_data_.offset_to_global_k_layer();
  // global index of the layer of flux of the wall
  //  (assume one walls at zmin and zmax)
  const int first_global_k_layer = channel_data_.first_global_k_layer_flux(icompo, idir);
  const int last_global_k_layer = channel_data_.last_global_k_layer_flux(icompo, idir);

  if (global_k_layer < first_global_k_layer || global_k_layer > last_global_k_layer)
    {
      // We are in the wall
      putzero(resu);
      return;
    }

  double half_surface = channel_data_.get_surface(k_layer, icompo, idir) * 0.5;
  {
    const int imax = nx;
    const int jmax = ny;
    const int vsize = Simd_double::size();
    for (int j = 0; ; j++)
      {
        for (int i = 0; i < imax; i += vsize)     // specific coding for uniform mesh in x and y: surfaces are constant on an xy plane
          {
            Simd_double vit_0,vit_1; // 2 adjacent velocity values
            src_ptr.get_left_center_z(i,vit_0,vit_1);
            // get convecting velocity
            Simd_double vconv0, vconv1;
            vconvz_ptr.get_left_center_x(i, vconv0, vconv1);

            // Average of the convecting velocity (copied from Eval_Amont_VDF_Face : not weighted)
            Simd_double psc = (vconv0 + vconv1) * half_surface;
            Simd_double upwind_velocity = select_double(psc, 0., vit_1 /* if psc < 0 */, vit_0 /* if psc > 0 */);
            Simd_double flux = psc * upwind_velocity;
            resu_ptr.put_val(i, flux);
          }
        // do not execute end_iloop at last iteration (because of assert on valid j+1)
        if (j+1==jmax)
          break;
        // instructions to perform to jump to next row
        src_ptr.next_j();
        resu_ptr.next_j();
        vconvz_ptr.next_j();
      }
  }
}

// Description: compute fluxes in direction z for velocity component y
//  for the layer of fluxes k_layer
// 4-th order centered convection scheme
void OpConvAmontIJK_double::compute_flux_z_vy(IJK_Field_local_double& resu, const int k_layer)
{
  // convected field
  const IJK_Field_local_double& src = *inputy_;
  // Convected vector field:
  ConstIJK_double_ptr src_ptr(src, 0, 0, k_layer);
  // Velocity in z direction (convecting velocity)
  ConstIJK_double_ptr vconvz_ptr(*vz_, 0, 0, k_layer);

  const int idir = 2;
  const int nx = src.ni();
  const int ny = src.nj();
  const int icompo = 1;
  // Result (fluxes in direction z for component y of the convected field)
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);



  const int global_k_layer = k_layer + channel_data_.offset_to_global_k_layer();
  // global index of the layer of flux of the wall
  //  (assume one walls at zmin and zmax)
  const int first_global_k_layer = channel_data_.first_global_k_layer_flux(icompo, idir);
  const int last_global_k_layer = channel_data_.last_global_k_layer_flux(icompo, idir);

  if (global_k_layer < first_global_k_layer || global_k_layer > last_global_k_layer)
    {
      // We are in the wall
      putzero(resu);
      return;
    }

  double half_surface = channel_data_.get_surface(k_layer, icompo, idir) * 0.5;
  {
    const int imax = nx;
    const int jmax = ny;
    const int vsize = Simd_double::size();
    for (int j = 0; ; j++)
      {
        for (int i = 0; i < imax; i += vsize)     // specific coding for uniform mesh in x and y: surfaces are constant on an xy plane
          {
            Simd_double vit_0,vit_1; // 2 adjacent velocity values
            src_ptr.get_left_center_z(i,vit_0,vit_1);
            // get convecting velocity
            Simd_double vconv0, vconv1;
            vconvz_ptr.get_left_center_y(i, vconv0, vconv1);

            // Average of the convecting velocity (copied from Eval_Amont_VDF_Face : not weighted)
            Simd_double psc = (vconv0 + vconv1) * half_surface;
            Simd_double upwind_velocity = select_double(psc, 0., vit_1 /* if psc < 0 */, vit_0 /* if psc > 0 */);
            Simd_double flux = psc * upwind_velocity;
            resu_ptr.put_val(i, flux);
          }
        // do not execute end_iloop at last iteration (because of assert on valid j+1)
        if (j+1==jmax)
          break;
        // instructions to perform to jump to next row
        src_ptr.next_j();
        resu_ptr.next_j();
        vconvz_ptr.next_j();
      }
  }
}

// Description: compute fluxes in direction z for velocity component z
//  for the layer of fluxes k_layer
// 4-th order centered convection scheme
void OpConvAmontIJK_double::compute_flux_z_vz(IJK_Field_local_double& resu, const int k_layer)
{
  // convected field
  const IJK_Field_local_double& src = *inputz_;
  // Convected vector field:
  ConstIJK_double_ptr src_ptr(src, 0, 0, k_layer);
  // Velocity in z direction (convecting velocity)
  ConstIJK_double_ptr vconvz_ptr(*vz_, 0, 0, k_layer);

  const int idir = 2;
  const int nx = src.ni();
  const int ny = src.nj();
  const int icompo = 2;
  // Result (fluxes in direction z for component z of the convected field)
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);



  const int global_k_layer = k_layer + channel_data_.offset_to_global_k_layer();
  // global index of the layer of flux of the wall
  //  (assume one walls at zmin and zmax)
  const int first_global_k_layer = channel_data_.first_global_k_layer_flux(icompo, idir);
  const int last_global_k_layer = channel_data_.last_global_k_layer_flux(icompo, idir);

  if (global_k_layer < first_global_k_layer || global_k_layer > last_global_k_layer)
    {
      // We are in the wall
      putzero(resu);
      return;
    }

  double half_surface = channel_data_.get_surface(k_layer, icompo, idir) * 0.5;
  {
    const int imax = nx;
    const int jmax = ny;
    const int vsize = Simd_double::size();
    for (int j = 0; ; j++)
      {
        for (int i = 0; i < imax; i += vsize)     // specific coding for uniform mesh in x and y: surfaces are constant on an xy plane
          {
            Simd_double vit_0,vit_1; // 2 adjacent velocity values
            src_ptr.get_left_center_z(i,vit_0,vit_1);
            // get convecting velocity
            Simd_double vconv0, vconv1;
            vconvz_ptr.get_left_center_z(i, vconv0, vconv1);

            // Average of the convecting velocity (copied from Eval_Amont_VDF_Face : not weighted)
            Simd_double psc = (vconv0 + vconv1) * half_surface;
            Simd_double upwind_velocity = select_double(psc, 0., vit_1 /* if psc < 0 */, vit_0 /* if psc > 0 */);
            Simd_double flux = psc * upwind_velocity;
            resu_ptr.put_val(i, flux);
          }
        // do not execute end_iloop at last iteration (because of assert on valid j+1)
        if (j+1==jmax)
          break;
        // instructions to perform to jump to next row
        src_ptr.next_j();
        resu_ptr.next_j();
        vconvz_ptr.next_j();
      }
  }
}


