#!/bin/bash

#Creation des repertoires
mkdir -p ./EI/Muscl
mkdir -p ./EI/EF_stab02
#
RACINE=`pwd`
###
# Cas EI/Muscl
cd $RACINE/EI/Muscl
cp $RACINE/cc_re100.data test.data
cp $RACINE/post_run .

# Cas EI/EF_stab02
cd $RACINE/EI/EF_stab02
cp $RACINE/cc_re100.data test.data
sed "s/convection { muscl }/convection { EF_stab { alpha 0.2 } }/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .