#!/bin/sh

sed 's/__EXPRESSION_TO_PLOT__/simu_d_rho/g' instructions2.py > instructions_simu_d_rho.py
sed 's/__EXPRESSION_TO_PLOT__/ana_d_rho/g' instructions2.py  > instructions_ana_d_rho.py
sed 's/__EXPRESSION_TO_PLOT__/error_d_rho/g' instructions2.py  > instructions_error_d_rho.py

rm -f simu_d_rho????.curve && visit -nowin -cli -s instructions_simu_d_rho.py 
rm -f ana_d_rho????.curve && visit -nowin -cli -s instructions_ana_d_rho.py 
rm -f error_d_rho????.curve && visit -nowin -cli -s instructions_error_d_rho.py 
