#!/bin/bash

#Creation des repertoires
for dim in 2D 3D ; do
	for etude in  crenel  gaussian  ; do
		for timesh in EE RK3 CN ; do
			for conv in Amont Muscl EF_stab EF_stab02 ; do
				mkdir -p ./$dim/$etude/$timesh/$conv
			done;
		done;
	done;
done;
mkdir -p ./2D/crenel/EE/Muscl_facsec02
mkdir -p ./2D/crenel/EE/EF_stab_facsec02
mkdir -p ./2D/crenel/EE/EF_stab02_facsec02
mkdir -p ./3D/crenel/EE/Muscl_facsec02
mkdir -p ./3D/crenel/EE/EF_stab_facsec02
mkdir -p ./3D/crenel/EE/EF_stab02_facsec02

mkdir -p ./2D/gaussian/EE/Muscl_facsec02
mkdir -p ./2D/gaussian/EE/EF_stab_facsec02
mkdir -p ./2D/gaussian/EE/EF_stab02_facsec02
mkdir -p ./3D/gaussian/EE/Muscl_facsec02
mkdir -p ./3D/gaussian/EE/EF_stab_facsec02
mkdir -p ./3D/gaussian/EE/EF_stab02_facsec02
#############
RACINE=`pwd`

echo $RACINE

#cas de base : Euler explicite & Muscl -> 2D/3D & creneau/gaussienne
cd $RACINE/2D/crenel/EE/Muscl
cp $RACINE/test_2D.data test.data
sed "s/tmax 3/tmax 12/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .

cd $RACINE/3D/crenel/EE/Muscl
cp $RACINE/test_3D.data test.data


#CAS CRENEAU 2D
#--------------
#
#    EE
#      
#	Amont
cd $RACINE/2D/crenel/EE/Amont
cp $RACINE/test_2D.data test.data
sed "s/convection { muscl }/convection { amont }/" test.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data
sed "s/tmax 3/tmax 12/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 1)
#
cd $RACINE/2D/crenel/EE/EF_stab
cp $RACINE/test_2D.data test.data
sed "s/convection { muscl }/convection { EF_stab { } }/" test.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data
sed "s/tmax 3/tmax 12/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 0.2)
#
cd $RACINE/2D/crenel/EE/EF_stab02
cp $RACINE/test_2D.data test.data
sed "s/convection { muscl }/convection { EF_stab { } }/" test.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data
###
###	CN
###
#	Muscl
cd $RACINE/2D/crenel/CN/Muscl
cp $RACINE/test_2D.data test.data
sed "s/Schema_Euler_Explicite sch/Sch_CN_iteratif sch/" test.data > modifie.data
mv modifie.data test.data
#
#	Amont
#
cd $RACINE/2D/crenel/CN/Amont
cp $RACINE/test_2D.data test.data
sed "s/Schema_Euler_Explicite sch/Sch_CN_iteratif sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { amont }/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 1)
#
cd $RACINE/2D/crenel/CN/EF_stab
cp $RACINE/test_2D.data test.data
sed "s/Schema_Euler_Explicite sch/Sch_CN_iteratif sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { EF_stab { } }/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 0.2)
#
cd $RACINE/2D/crenel/CN/EF_stab02
cp $RACINE/test_2D.data test.data
sed "s/Schema_Euler_Explicite sch/Sch_CN_iteratif sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { EF_stab { alpha 0.2 } }/" test.data > modifie.data
mv modifie.data test.data
###
###	RK3
###
#	Muscl
cd $RACINE/2D/crenel/RK3/Muscl
cp $RACINE/test_2D.data test.data
sed "s/Schema_Euler_Explicite sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
#
#	Amont
#
cd $RACINE/2D/crenel/RK3/Amont
cp $RACINE/test_2D.data test.data
sed "s/Schema_Euler_Explicite sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { amont }/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 1)
#
cd $RACINE/2D/crenel/RK3/EF_stab
cp $RACINE/test_2D.data test.data
sed "s/Schema_Euler_Explicite sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { EF_stab { } }/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 0.2)
#
cd $RACINE/2D/crenel/RK3/EF_stab02
cp $RACINE/test_2D.data test.data
sed "s/Schema_Euler_Explicite sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { EF_stab { alpha 0.2 } }/" test.data > modifie.data
mv modifie.data test.data

#CAS GAUSSIEN 2D
#--------------
#
#    EE
#
#	Muscl
cd $RACINE/2D/gaussian/EE/Muscl
cp $RACINE/test_2D.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data
#
#	Amont
#
cd $RACINE/2D/gaussian/EE/Amont
cp $RACINE/test_2D.data test.data
sed "s/convection { muscl }/convection { amont }/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 1)
#
cd $RACINE/2D/gaussian/EE/EF_stab
cp $RACINE/test_2D.data test.data
sed "s/convection { muscl }/convection { EF_stab { } }/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data

#
#	EF_stab (alpha = 0.2)
#
cd $RACINE/2D/gaussian/EE/EF_stab02
cp $RACINE/test_2D.data test.data
sed "s/convection { muscl }/convection { EF_stab { } }/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data
###
###	CN
###
#	Muscl
cd $RACINE/2D/gaussian/CN/Muscl
cp $RACINE/test_2D.data test.data
sed "s/Schema_Euler_Explicite sch/Sch_CN_iteratif sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
#
#	Amont
#
cd $RACINE/2D/gaussian/CN/Amont
cp $RACINE/test_2D.data test.data
sed "s/Schema_Euler_Explicite sch/Sch_CN_iteratif sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { amont }/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 1)
#
cd $RACINE/2D/gaussian/CN/EF_stab
cp $RACINE/test_2D.data test.data
sed "s/Schema_Euler_Explicite sch/Sch_CN_iteratif sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { EF_stab { } }/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 0.2)
#
cd $RACINE/2D/gaussian/CN/EF_stab02
cp $RACINE/test_2D.data test.data
sed "s/Schema_Euler_Explicite sch/Sch_CN_iteratif sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { EF_stab { alpha 0.2 } }/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
###
###	RK3
###
#	Muscl
cd $RACINE/2D/gaussian/RK3/Muscl
cp $RACINE/test_2D.data test.data
sed "s/Schema_Euler_Explicite sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
#
#	Amont
#
cd $RACINE/2D/gaussian/RK3/Amont
cp $RACINE/test_2D.data test.data
sed "s/Schema_Euler_Explicite sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { amont }/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 1)
#
cd $RACINE/2D/gaussian/RK3/EF_stab
cp $RACINE/test_2D.data test.data
sed "s/Schema_Euler_Explicite sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { EF_stab { } }/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 0.2)
#
cd $RACINE/2D/gaussian/RK3/EF_stab02
cp $RACINE/test_2D.data test.data
sed "s/Schema_Euler_Explicite sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { EF_stab { alpha 0.2 } }/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data

###
###
###
###	3D
###
###
###
###
###


#CAS CRENEAU 3D
#--------------
#
#    EE
#      
#	Amont
cd $RACINE/3D/crenel/EE/Amont
cp $RACINE/test_3D.data test.data
sed "s/convection { muscl }/convection { amont }/" test.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 1)
#
cd $RACINE/3D/crenel/EE/EF_stab
cp $RACINE/test_3D.data test.data
sed "s/convection { muscl }/convection { EF_stab { } }/" test.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 0.2)
#
cd $RACINE/3D/crenel/EE/EF_stab02
cp $RACINE/test_3D.data test.data
sed "s/convection { muscl }/convection { EF_stab { } }/" test.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data
###
###	CN
###
#	Muscl
cd $RACINE/3D/crenel/CN/Muscl
cp $RACINE/test_3D.data test.data
sed "s/Schema_Euler_Explicite sch/Sch_CN_iteratif sch/" test.data > modifie.data
mv modifie.data test.data
#
#	Amont
#
cd $RACINE/3D/crenel/CN/Amont
cp $RACINE/test_3D.data test.data
sed "s/Schema_Euler_Explicite sch/Sch_CN_iteratif sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { amont }/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 1)
#
cd $RACINE/3D/crenel/CN/EF_stab
cp $RACINE/test_3D.data test.data
sed "s/Schema_Euler_Explicite sch/Sch_CN_iteratif sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { EF_stab { } }/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 0.2)
#
cd $RACINE/3D/crenel/CN/EF_stab02
cp $RACINE/test_3D.data test.data
sed "s/Schema_Euler_Explicite sch/Sch_CN_iteratif sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { EF_stab { alpha 0.2 } }/" test.data > modifie.data
mv modifie.data test.data
###
###	RK3
###
#	Muscl
cd $RACINE/3D/crenel/RK3/Muscl
cp $RACINE/test_3D.data test.data
sed "s/Schema_Euler_Explicite sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
#
#	Amont
#
cd $RACINE/3D/crenel/RK3/Amont
cp $RACINE/test_3D.data test.data
sed "s/Schema_Euler_Explicite sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { amont }/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 1)
#
cd $RACINE/3D/crenel/RK3/EF_stab
cp $RACINE/test_3D.data test.data
sed "s/Schema_Euler_Explicite sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { EF_stab { } }/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 0.2)
#
cd $RACINE/3D/crenel/RK3/EF_stab02
cp $RACINE/test_3D.data test.data
sed "s/Schema_Euler_Explicite sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { EF_stab { alpha 0.2 } }/" test.data > modifie.data
mv modifie.data test.data


#CAS GAUSSIEN 3D
#--------------
#
#    EE
#
#	Muscl
cd $RACINE/3D/gaussian/EE/Muscl
cp $RACINE/test_3D.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data
#
#	Amont
#
cd $RACINE/3D/gaussian/EE/Amont
cp $RACINE/test_3D.data test.data
sed "s/convection { muscl }/convection { amont }/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 1)
#
cd $RACINE/3D/gaussian/EE/EF_stab
cp $RACINE/test_3D.data test.data
sed "s/convection { muscl }/convection { EF_stab { } }/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 0.2)
#
cd $RACINE/3D/gaussian/EE/EF_stab02
cp $RACINE/test_3D.data test.data
sed "s/convection { muscl }/convection { EF_stab { } }/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.5/" test.data > modifie.data
mv modifie.data test.data
###
###	CN
###
#	Muscl
cd $RACINE/3D/gaussian/CN/Muscl
cp $RACINE/test_3D.data test.data
sed "s/Schema_Euler_Explicite sch/Sch_CN_iteratif sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
#
#	Amont
#
cd $RACINE/3D/gaussian/CN/Amont
cp $RACINE/test_3D.data test.data
sed "s/Schema_Euler_Explicite sch/Sch_CN_iteratif sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { amont }/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 1)
#
cd $RACINE/3D/gaussian/CN/EF_stab
cp $RACINE/test_3D.data test.data
sed "s/Schema_Euler_Explicite sch/Sch_CN_iteratif sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { EF_stab { } }/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 0.2)
#
cd $RACINE/3D/gaussian/CN/EF_stab02
cp $RACINE/test_3D.data test.data
sed "s/Schema_Euler_Explicite sch/Sch_CN_iteratif sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { EF_stab { alpha 0.2 } }/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
###
###	RK3
###
#	Muscl
cd $RACINE/3D/gaussian/RK3/Muscl
cp $RACINE/test_3D.data test.data
sed "s/Schema_Euler_Explicite sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
#
#	Amont
#
cd $RACINE/3D/gaussian/RK3/Amont
cp $RACINE/test_3D.data test.data
sed "s/Schema_Euler_Explicite sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { amont }/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 1)
#
cd $RACINE/3D/gaussian/RK3/EF_stab
cp $RACINE/test_3D.data test.data
sed "s/Schema_Euler_Explicite sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { EF_stab { } }/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data
#
#	EF_stab (alpha = 0.2)
#
cd $RACINE/3D/gaussian/RK3/EF_stab02
cp $RACINE/test_3D.data test.data
sed "s/Schema_Euler_Explicite sch/Runge_kutta_ordre_3 sch/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { muscl }/convection { EF_stab { alpha 0.2 } }/" test.data > modifie.data
mv modifie.data test.data
sed "s/(x>0.4)-(x>0.6)/EXP(-100*(x-0.5)*(x-0.5))/" test.data > modifie.data
mv modifie.data test.data


############
##############################################################
####### Cas facsec = 0.2
#
# crenel
cd $RACINE/2D/crenel/EE/Muscl_facsec02
cp $RACINE/test_2D.data test.data
sed "s/facsec 1/facsec 0.2/" test.data > modifie.data
mv modifie.data test.data
sed "s/tmax 3/tmax 12/" test.data > modifie.data
mv modifie.data test.data
##
##
cd $RACINE/2D/crenel/EE/EF_stab_facsec02
cp $RACINE/test_2D.data test.data
sed "s/convection { muscl }/convection { EF_stab { } }/" test.data > modifie.data
mv modifie.data test.data
sed "s/facsec 1/facsec 0.2/" test.data > modifie.data
mv modifie.data test.data
sed "s/tmax 3/tmax 12/" test.data > modifie.data
mv modifie.data test.data
##
##



