Statistiques de post resolution

Temps total                       1.71659

Timesteps                         1
Secondes / pas de temps           1.38135
Dont solveurs Ax=B                0.114127 8% (20 appels/pas de temps)
Dont operations postraitement     0.061226 4% (2 appels/pas de temps)
Dont calcul divers                -1.40995 -102%
Nb echange_espace_virtuel / pas de temps 1999
Nb solveur / pas de temps         20
Secondes / solveur                0.00570635
Iterations / solveur              31.65

Timesteps = nombre de pas de temps
Nb solveur = nombre de resolutions de systeme lineaire
Nb assemblage implicite = nombre d'assemblage de matrice pour le schema implicite
Iterations = nombre moyen d'iterations du solveur
Communications = fraction du temps passe dans les
                 communications entre processeurs (hors io fichiers)
Network latency = temps d'un mpsum mesure par un bench interne sur 0.1s
Network bandwidth = maximum sur l'ensemble des processeurs
                    de la bande passante moyenne des operations send_recv
Waiting time = estimation du temps d'attente des differents processeurs

Max_waiting_time grand  => probablement mauvais decoupage
Communications > 30%    => trop de processeurs ou reseau trop lent

Statistiques de post resolution

Temps total                       0.67457

Timesteps                         1
Secondes / pas de temps           0.337904
Dont solveurs Ax=B                0.080514 23% (20 appels/pas de temps)
Dont operations postraitement     0.035459 10% (2 appels/pas de temps)
Dont calcul divers                -0.332236 -98%
Nb echange_espace_virtuel / pas de temps 3217
Nb MPI_allreduce / pas de temps 2444
-----------------------------------------------------------------------------------------------------------------------------------------
Warning: The number of MPI_allreduce calls per time step is high. Contact TRUST support if you plan to run massive parallel calculation.
-----------------------------------------------------------------------------------------------------------------------------------------
Nb solveur / pas de temps         20
Secondes / solveur                0.0040257
Iterations / solveur              51.95
Communications avg        37.1 % of total time
Communications max        47.2 % of total time
Communications min        23.1 % of total time
Network latency benchmark 7.24792e-06 s
Network bandwidth max     895.474 MB/s
Total network traffic     1188.43 MB / timestep
Average message size      1.83092 kB
Min waiting time          8 % of total time
Max waiting time          29 % of total time
Avg waiting time          21.9889 % of total time

Timesteps = nombre de pas de temps
Nb solveur = nombre de resolutions de systeme lineaire
Nb assemblage implicite = nombre d'assemblage de matrice pour le schema implicite
Iterations = nombre moyen d'iterations du solveur
Communications = fraction du temps passe dans les
                 communications entre processeurs (hors io fichiers)
Network latency = temps d'un mpsum mesure par un bench interne sur 0.1s
Network bandwidth = maximum sur l'ensemble des processeurs
                    de la bande passante moyenne des operations send_recv
Waiting time = estimation du temps d'attente des differents processeurs

Max_waiting_time grand  => probablement mauvais decoupage
Communications > 30%    => trop de processeurs ou reseau trop lent

Statistiques de post resolution

Temps total                       5.75066

Timesteps                         1
Secondes / pas de temps           5.51414
Dont solveurs Ax=B                0.153042 2% (20 appels/pas de temps)
Dont operations postraitement     0.068204 1% (2 appels/pas de temps)
Dont calcul divers                -5.81683 -105%
Nb echange_espace_virtuel / pas de temps 3217
Nb MPI_allreduce / pas de temps 2479
-----------------------------------------------------------------------------------------------------------------------------------------
Warning: The number of MPI_allreduce calls per time step is high. Contact TRUST support if you plan to run massive parallel calculation.
-----------------------------------------------------------------------------------------------------------------------------------------
Nb solveur / pas de temps         20
Secondes / solveur                0.0076521
Iterations / solveur              51.95
Communications avg        8.4 % of total time
Communications max        9.6 % of total time
Communications min        6.2 % of total time
Network latency benchmark 7.689e-06 s
Network bandwidth max     382.918 MB/s
Total network traffic     1188.5 MB / timestep
Average message size      1.80631 kB
Min waiting time          2.4 % of total time
Max waiting time          5.2 % of total time
Avg waiting time          4.61667 % of total time

Timesteps = nombre de pas de temps
Nb solveur = nombre de resolutions de systeme lineaire
Nb assemblage implicite = nombre d'assemblage de matrice pour le schema implicite
Iterations = nombre moyen d'iterations du solveur
Communications = fraction du temps passe dans les
                 communications entre processeurs (hors io fichiers)
Network latency = temps d'un mpsum mesure par un bench interne sur 0.1s
Network bandwidth = maximum sur l'ensemble des processeurs
                    de la bande passante moyenne des operations send_recv
Waiting time = estimation du temps d'attente des differents processeurs

Max_waiting_time grand  => probablement mauvais decoupage
Communications > 30%    => trop de processeurs ou reseau trop lent

