#!/bin/bash
gunzip -c trio_BODY_geo.asc.gz > trio_BODY_geo.asc
#Creation des repertoires

mkdir -p EF_stab EF_stab02 Amont

RACINE=`pwd`
#cp ../src/post_run .		#COPIE DES SCRIPTS DE POST-TRAITEMENT DANS LE BUILD POUR RAJOUTER CALCUL DE U* et DpPx dans la fiche
#cp ../src/tableauCourbes.py .
#cp ../src/propertiesGeometry.py .

echo $RACINE

#maillage N5
#-----------
#      Amont
cd $RACINE/Amont
cp $RACINE/test.data .
cp $RACINE/post_run .
cp $RACINE//trio_BODY_geo.asc .

#
#      EF_stab alpha=1
#
cd $RACINE/EF_stab
cp $RACINE/test.data .
sed "s/amont/EF_stab { }/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
cp $RACINE//trio_BODY_geo.asc .

#
#      EF_stab alpha=0.2
#
cd $RACINE/EF_stab02
cp $RACINE/test.data .
sed "s/amont/EF_stab { alpha 0.2 }/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
cp $RACINE//trio_BODY_geo.asc .

