//TRUST_NO_INDENT
/****************************************************************************
* Copyright (c) 2015 - 2016, CEA
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
* 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
* 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
* 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
* OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*****************************************************************************/
/////////////////////////////////////////////////////////////////////////////
//
// File      : OpDiffTurbIJKScalar.cpp
// Directory : $IJK_ROOT/src/IJK/OpVDF
//
/////////////////////////////////////////////////////////////////////////////
//
// WARNING: DO NOT EDIT THIS FILE! Only edit the template file OpDiffTurbIJKScalar.cpp.P
//
#include <OpDiffTurbIJKScalar.h>



void copy_boundary_condition(const IJK_Field_local_double & boundary_flux, IJK_Field_local_double & resu)
{
  assert(resu.ni() >= boundary_flux.ni());
  assert(resu.nj() >= boundary_flux.nj());
  // resu is the temporary array where all fluxes are stored before computing divergence,
  // they might have more place than ni and nj because there 1 more flux value dans velocity values
  // to compute divergence
  const int ni = boundary_flux.ni();
  const int nj = boundary_flux.nj();
  for (int j = 0; j < nj; j++)
    for (int i = 0; i < ni; i++)
      resu(i,j,0) = boundary_flux(i,j,0);
}


OpDiffIJKScalar_double::OpDiffIJKScalar_double()
{
  input_field_ = 0;
  lambda_ = 0;
  boundary_flux_kmin_ = boundary_flux_kmax_ = 0;
}

void OpDiffIJKScalar_double::initialize(const IJK_Splitting & splitting)
{
  channel_data_.initialize(splitting);
  perio_k_= splitting.get_grid_geometry().get_periodic_flag(DIRECTION_K);
}

void OpDiffIJKScalar_double::calculer(const IJK_Field_double & field, 
                                  const IJK_Field_double & lambda,
                                  IJK_Field_double & result,
                                  const IJK_Field_local_double & boundary_flux_kmin,
                                  const IJK_Field_local_double & boundary_flux_kmax)
{
  input_field_ = &field;
  lambda_ = &lambda;
  boundary_flux_kmin_ = &boundary_flux_kmin;
  boundary_flux_kmax_ = &boundary_flux_kmax;
  compute_set(result);
  input_field_ = 0;
  lambda_ = 0;
  boundary_flux_kmin_ = boundary_flux_kmax_ = 0;
}

void OpDiffIJKScalar_double::ajouter(const IJK_Field_double & field, 
                                 const IJK_Field_double & lambda,
                                 IJK_Field_double & result,
                                 const IJK_Field_local_double & boundary_flux_kmin,
                                 const IJK_Field_local_double & boundary_flux_kmax)
{
  input_field_ = &field;
  lambda_ = &lambda;
  boundary_flux_kmin_ = &boundary_flux_kmin;
  boundary_flux_kmax_ = &boundary_flux_kmax;
  compute_add(result);
  input_field_ = 0;
  lambda_ = 0;
  boundary_flux_kmin_ = boundary_flux_kmax_ = 0;
}

void OpDiffIJKScalar_double::compute_flux_x(IJK_Field_local_double & resu, const int k_layer)
{
  ConstIJK_double_ptr input_field(*input_field_, 0, 0, k_layer);
  ConstIJK_double_ptr lambda(*lambda_, 0, 0, k_layer);
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);

  const int nx = input_field_->ni() + 1;
  const int ny = input_field_->nj();
  const double d0 = channel_data_.get_delta_x() * 0.5;
  const double d1 = d0;
  const double surface = channel_data_.get_delta_y() * channel_data_.get_delta_z()[k_layer];

{
  const int imax = nx;
  const int jmax = ny;
  const int vsize = Simd_double::size();
  for (int j = 0; ; j++) {
    for (int i = 0; i < imax; i += vsize) {   Simd_double left_val, right_val, lambda_m1, lambda_m2;
  input_field.get_left_center_x(i, left_val, right_val);
  // Fetch conductivity on neighbour cells:
  lambda.get_left_center_x(i, lambda_m1, lambda_m2);

  // geometric avg: (d0+d1) / ( d0 / lambda_m1 + d1 / lambda_m2 ), optimized with only 1 division:

  Simd_double dsabs = SimdSelect(0, d0 * lambda_m2 + d1 * lambda_m1, d0 * lambda_m2 + d1 * lambda_m1, (-1) * (d0 * lambda_m2 + d1 * lambda_m1));
  Simd_double ds = SimdSelect(dsabs, DMINFLOAT, 1., d0 * lambda_m2 + d1 * lambda_m1);
  Simd_double avg_lambda = SimdSelect(dsabs, DMINFLOAT, 0., SimdDivideMed(lambda_m1 * lambda_m2, ds));
  // thermal flux is positive if going from left to right => -grad(T)
  Simd_double flux = (left_val - right_val) * avg_lambda * surface;
  resu_ptr.put_val(i, flux);
 }
    // do not execute end_iloop at last iteration (because of assert on valid j+1)
    if (j+1==jmax)
      break; 
  input_field.next_j();
  lambda.next_j();
  resu_ptr.next_j();
  }
}

}
void OpDiffIJKScalar_double::compute_flux_y(IJK_Field_local_double & resu, const int k_layer)
{
  ConstIJK_double_ptr input_field(*input_field_, 0, 0, k_layer);
  ConstIJK_double_ptr lambda(*lambda_, 0, 0, k_layer);
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);

  const int nx = input_field_->ni();
  const int ny = input_field_->nj() + 1;
  const double d0 = channel_data_.get_delta_y() * 0.5;
  const double d1 = d0;
  const double surface = channel_data_.get_delta_x() * channel_data_.get_delta_z()[k_layer];

{
  const int imax = nx;
  const int jmax = ny;
  const int vsize = Simd_double::size();
  for (int j = 0; ; j++) {
    for (int i = 0; i < imax; i += vsize) {   Simd_double left_val, right_val, lambda_m1, lambda_m2;
  input_field.get_left_center_y(i, left_val, right_val);
  // Fetch conductivity on neighbour cells:
  lambda.get_left_center_y(i, lambda_m1, lambda_m2);

  // geometric avg: (d0+d1) / ( d0 / lambda_m1 + d1 / lambda_m2 ), optimized with only 1 division:

  Simd_double dsabs = SimdSelect(0, d0 * lambda_m2 + d1 * lambda_m1, d0 * lambda_m2 + d1 * lambda_m1, (-1) * (d0 * lambda_m2 + d1 * lambda_m1));
  Simd_double ds = SimdSelect(dsabs, DMINFLOAT, 1., d0 * lambda_m2 + d1 * lambda_m1);
  Simd_double avg_lambda = SimdSelect(dsabs, DMINFLOAT, 0., SimdDivideMed(lambda_m1 * lambda_m2, ds));
  // thermal flux is positive if going from left to right => -grad(T)
  Simd_double flux = (left_val - right_val) * avg_lambda * surface;
  resu_ptr.put_val(i, flux);
 }
    // do not execute end_iloop at last iteration (because of assert on valid j+1)
    if (j+1==jmax)
      break; 
  input_field.next_j();
  lambda.next_j();
  resu_ptr.next_j();
  }
}

}
void OpDiffIJKScalar_double::compute_flux_z(IJK_Field_local_double & resu, const int k_layer)
{
  ConstIJK_double_ptr input_field(*input_field_, 0, 0, k_layer);
  ConstIJK_double_ptr lambda(*lambda_, 0, 0, k_layer);
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);
  // Are we on the wall ?
  const int global_k_layer = k_layer + channel_data_.offset_to_global_k_layer();
  // global index of the layer of flux of the wall
  //  (assume one walls at zmin and zmax)
  const int first_global_k_layer = 0; // index of k_layer when we are on the wall
  // Fluxes in direction k are on the faces, hence, index of last flux is equal to number of elements
  const int last_global_k_layer =  channel_data_.nb_elem_k_tot();

  if (!perio_k_)
    {
      if (global_k_layer == first_global_k_layer)
        {
          // We are on wall at kmin, copy boundary condition fluxes to "resu"
          if (boundary_flux_kmin_) // boundary condition is not zero flux
            copy_boundary_condition(*boundary_flux_kmin_, resu);
          else
            putzero(resu);
          return;
        }
      else if (global_k_layer == last_global_k_layer)
        {
          if (boundary_flux_kmax_) // boundary condition is not zero flux
            copy_boundary_condition(*boundary_flux_kmax_, resu);
          else
            putzero(resu);
          return;
        }
    }

  const int nx = input_field_->ni();
  const int ny = input_field_->nj();
  const double d0 = channel_data_.get_delta_z()[k_layer-1] * 0.5;
  const double d1 = channel_data_.get_delta_z()[k_layer] * 0.5;
  const double surface = channel_data_.get_delta_x() * channel_data_.get_delta_y();

{
  const int imax = nx;
  const int jmax = ny;
  const int vsize = Simd_double::size();
  for (int j = 0; ; j++) {
    for (int i = 0; i < imax; i += vsize) {   Simd_double left_val, right_val, lambda_m1, lambda_m2;
  input_field.get_left_center_z(i, left_val, right_val);
  // Fetch conductivity on neighbour cells:
  lambda.get_left_center_z(i, lambda_m1, lambda_m2);

  // geometric avg: (d0+d1) / ( d0 / lambda_m1 + d1 / lambda_m2 ), optimized with only 1 division:

  Simd_double dsabs = SimdSelect(0, d0 * lambda_m2 + d1 * lambda_m1, d0 * lambda_m2 + d1 * lambda_m1, (-1) * (d0 * lambda_m2 + d1 * lambda_m1));
  Simd_double ds = SimdSelect(dsabs, DMINFLOAT, 1., d0 * lambda_m2 + d1 * lambda_m1);
  Simd_double avg_lambda = SimdSelect(dsabs, DMINFLOAT, 0., SimdDivideMed(lambda_m1 * lambda_m2, ds));
  // thermal flux is positive if going from left to right => -grad(T)
  Simd_double flux = (left_val - right_val) * avg_lambda * surface;
  resu_ptr.put_val(i, flux);
 }
    // do not execute end_iloop at last iteration (because of assert on valid j+1)
    if (j+1==jmax)
      break; 
  input_field.next_j();
  lambda.next_j();
  resu_ptr.next_j();
  }
}

}

OpDiffAnisotropicIJKScalar_double::OpDiffAnisotropicIJKScalar_double()
{
  input_field_ = 0;
  lambda_ = 0;
  boundary_flux_kmin_ = boundary_flux_kmax_ = 0;
}

void OpDiffAnisotropicIJKScalar_double::initialize(const IJK_Splitting & splitting)
{
  channel_data_.initialize(splitting);
  perio_k_= splitting.get_grid_geometry().get_periodic_flag(DIRECTION_K);
}

void OpDiffAnisotropicIJKScalar_double::calculer(const IJK_Field_double & field, 
                                  const IJK_Field_double & lambda,
                                  IJK_Field_double & result,
                                  const IJK_Field_local_double & boundary_flux_kmin,
                                  const IJK_Field_local_double & boundary_flux_kmax)
{
  input_field_ = &field;
  lambda_ = &lambda;
  boundary_flux_kmin_ = &boundary_flux_kmin;
  boundary_flux_kmax_ = &boundary_flux_kmax;
  compute_set(result);
  input_field_ = 0;
  lambda_ = 0;
  boundary_flux_kmin_ = boundary_flux_kmax_ = 0;
}

void OpDiffAnisotropicIJKScalar_double::ajouter(const IJK_Field_double & field, 
                                 const IJK_Field_double & lambda,
                                 IJK_Field_double & result,
                                 const IJK_Field_local_double & boundary_flux_kmin,
                                 const IJK_Field_local_double & boundary_flux_kmax)
{
  input_field_ = &field;
  lambda_ = &lambda;
  boundary_flux_kmin_ = &boundary_flux_kmin;
  boundary_flux_kmax_ = &boundary_flux_kmax;
  compute_add(result);
  input_field_ = 0;
  lambda_ = 0;
  boundary_flux_kmin_ = boundary_flux_kmax_ = 0;
}

void OpDiffAnisotropicIJKScalar_double::compute_flux_x(IJK_Field_local_double & resu, const int k_layer)
{
  ConstIJK_double_ptr input_field(*input_field_, 0, 0, k_layer);
  ConstIJK_double_ptr lambda(*lambda_, 0, 0, k_layer);
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);

  const int nx = input_field_->ni() + 1;
  const int ny = input_field_->nj();
  const double d0 = channel_data_.get_delta_x() * 0.5;
  const double d1 = d0;
  const double surface = channel_data_.get_delta_y() * channel_data_.get_delta_z()[k_layer];

{
  const int imax = nx;
  const int jmax = ny;
  const int vsize = Simd_double::size();
  for (int j = 0; ; j++) {
    for (int i = 0; i < imax; i += vsize) {   const double d = d0 + d1;
  Simd_double left_val, right_val, lambda_m1, lambda_m2;
  input_field.get_left_center_x(i, left_val, right_val);
  // Fetch conductivity on neighbour cells:
  lambda.get_left_center_x(i, lambda_m1, lambda_m2);

  // geometric avg: (d0+d1) / ( d0 / lambda_m1 + d1 / lambda_m2 ), optimized with only 1 division:

  Simd_double dsabs = SimdSelect(0, d0 * lambda_m2 + d1 * lambda_m1, d0 * lambda_m2 + d1 * lambda_m1, (-1) * (d0 * lambda_m2 + d1 * lambda_m1));
  Simd_double ds = SimdSelect(dsabs, DMINFLOAT, 1., d0 * lambda_m2 + d1 * lambda_m1);
  Simd_double avg_lambda = SimdSelect(dsabs, DMINFLOAT, 0., SimdDivideMed(d * lambda_m1 * lambda_m2, ds));
  // thermal flux is positive if going from left to right => -grad(T)
  Simd_double flux = (left_val - right_val) * avg_lambda * surface;
  resu_ptr.put_val(i, flux);
 }
    // do not execute end_iloop at last iteration (because of assert on valid j+1)
    if (j+1==jmax)
      break; 
  input_field.next_j();
  lambda.next_j();
  resu_ptr.next_j();
  }
}

}
void OpDiffAnisotropicIJKScalar_double::compute_flux_y(IJK_Field_local_double & resu, const int k_layer)
{
  ConstIJK_double_ptr input_field(*input_field_, 0, 0, k_layer);
  ConstIJK_double_ptr lambda(*lambda_, 0, 0, k_layer);
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);

  const int nx = input_field_->ni();
  const int ny = input_field_->nj() + 1;
  const double d0 = channel_data_.get_delta_y() * 0.5;
  const double d1 = d0;
  const double surface = channel_data_.get_delta_x() * channel_data_.get_delta_z()[k_layer];

{
  const int imax = nx;
  const int jmax = ny;
  const int vsize = Simd_double::size();
  for (int j = 0; ; j++) {
    for (int i = 0; i < imax; i += vsize) {   const double d = d0 + d1;
  Simd_double left_val, right_val, lambda_m1, lambda_m2;
  input_field.get_left_center_y(i, left_val, right_val);
  // Fetch conductivity on neighbour cells:
  lambda.get_left_center_y(i, lambda_m1, lambda_m2);

  // geometric avg: (d0+d1) / ( d0 / lambda_m1 + d1 / lambda_m2 ), optimized with only 1 division:

  Simd_double dsabs = SimdSelect(0, d0 * lambda_m2 + d1 * lambda_m1, d0 * lambda_m2 + d1 * lambda_m1, (-1) * (d0 * lambda_m2 + d1 * lambda_m1));
  Simd_double ds = SimdSelect(dsabs, DMINFLOAT, 1., d0 * lambda_m2 + d1 * lambda_m1);
  Simd_double avg_lambda = SimdSelect(dsabs, DMINFLOAT, 0., SimdDivideMed(d * lambda_m1 * lambda_m2, ds));
  // thermal flux is positive if going from left to right => -grad(T)
  Simd_double flux = (left_val - right_val) * avg_lambda * surface;
  resu_ptr.put_val(i, flux);
 }
    // do not execute end_iloop at last iteration (because of assert on valid j+1)
    if (j+1==jmax)
      break; 
  input_field.next_j();
  lambda.next_j();
  resu_ptr.next_j();
  }
}

}
void OpDiffAnisotropicIJKScalar_double::compute_flux_z(IJK_Field_local_double & resu, const int k_layer)
{
  ConstIJK_double_ptr input_field(*input_field_, 0, 0, k_layer);
  ConstIJK_double_ptr lambda(*lambda_, 0, 0, k_layer);
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);
  // Are we on the wall ?
  const int global_k_layer = k_layer + channel_data_.offset_to_global_k_layer();
  // global index of the layer of flux of the wall
  //  (assume one walls at zmin and zmax)
  const int first_global_k_layer = 0; // index of k_layer when we are on the wall
  // Fluxes in direction k are on the faces, hence, index of last flux is equal to number of elements
  const int last_global_k_layer =  channel_data_.nb_elem_k_tot();

  if (!perio_k_)
    {
      if (global_k_layer == first_global_k_layer)
        {
          // We are on wall at kmin, copy boundary condition fluxes to "resu"
          if (boundary_flux_kmin_) // boundary condition is not zero flux
            copy_boundary_condition(*boundary_flux_kmin_, resu);
          else
            putzero(resu);
          return;
        }
      else if (global_k_layer == last_global_k_layer)
        {
          if (boundary_flux_kmax_) // boundary condition is not zero flux
            copy_boundary_condition(*boundary_flux_kmax_, resu);
          else
            putzero(resu);
          return;
        }
    }

  const int nx = input_field_->ni();
  const int ny = input_field_->nj();
  const double d0 = channel_data_.get_delta_z()[k_layer-1] * 0.5;
  const double d1 = channel_data_.get_delta_z()[k_layer] * 0.5;
  const double surface = channel_data_.get_delta_x() * channel_data_.get_delta_y();

{
  const int imax = nx;
  const int jmax = ny;
  const int vsize = Simd_double::size();
  for (int j = 0; ; j++) {
    for (int i = 0; i < imax; i += vsize) {   const double d = d0 + d1;
  Simd_double left_val, right_val, lambda_m1, lambda_m2;
  input_field.get_left_center_z(i, left_val, right_val);
  // Fetch conductivity on neighbour cells:
  lambda.get_left_center_z(i, lambda_m1, lambda_m2);

  // geometric avg: (d0+d1) / ( d0 / lambda_m1 + d1 / lambda_m2 ), optimized with only 1 division:

  Simd_double dsabs = SimdSelect(0, d0 * lambda_m2 + d1 * lambda_m1, d0 * lambda_m2 + d1 * lambda_m1, (-1) * (d0 * lambda_m2 + d1 * lambda_m1));
  Simd_double ds = SimdSelect(dsabs, DMINFLOAT, 1., d0 * lambda_m2 + d1 * lambda_m1);
  Simd_double avg_lambda = SimdSelect(dsabs, DMINFLOAT, 0., SimdDivideMed(d * lambda_m1 * lambda_m2, ds));
  // thermal flux is positive if going from left to right => -grad(T)
  Simd_double flux = (left_val - right_val) * avg_lambda * surface;
  resu_ptr.put_val(i, flux);
 }
    // do not execute end_iloop at last iteration (because of assert on valid j+1)
    if (j+1==jmax)
      break; 
  input_field.next_j();
  lambda.next_j();
  resu_ptr.next_j();
  }
}

}

OpDiffVectorialIJKScalar_double::OpDiffVectorialIJKScalar_double()
{
  input_field_ = 0;
  lambda_vector_x_ = 0;
  lambda_vector_y_ = 0;
  lambda_vector_z_ = 0;
  boundary_flux_kmin_ = boundary_flux_kmax_ = 0;
}

void OpDiffVectorialIJKScalar_double::initialize(const IJK_Splitting & splitting)
{
  channel_data_.initialize(splitting);
  perio_k_= splitting.get_grid_geometry().get_periodic_flag(DIRECTION_K);
}

void OpDiffVectorialIJKScalar_double::calculer(const IJK_Field_double & field, 
                                  const IJK_Field_double & lambda_vector_x,
                                  const IJK_Field_double & lambda_vector_y,
                                  const IJK_Field_double & lambda_vector_z,
                                  IJK_Field_double & result,
                                  const IJK_Field_local_double & boundary_flux_kmin,
                                  const IJK_Field_local_double & boundary_flux_kmax)
{
  input_field_ = &field;
  lambda_vector_x_ = &lambda_vector_x;
  lambda_vector_y_ = &lambda_vector_y;
  lambda_vector_z_ = &lambda_vector_z;
  boundary_flux_kmin_ = &boundary_flux_kmin;
  boundary_flux_kmax_ = &boundary_flux_kmax;
  compute_set(result);
  input_field_ = 0;
  lambda_vector_x_ = 0;
  lambda_vector_y_ = 0;
  lambda_vector_z_ = 0;
  boundary_flux_kmin_ = boundary_flux_kmax_ = 0;
}

void OpDiffVectorialIJKScalar_double::ajouter(const IJK_Field_double & field, 
                                 const IJK_Field_double & lambda_vector_x,
                                 const IJK_Field_double & lambda_vector_y,
                                 const IJK_Field_double & lambda_vector_z,
                                 IJK_Field_double & result,
                                 const IJK_Field_local_double & boundary_flux_kmin,
                                 const IJK_Field_local_double & boundary_flux_kmax)
{
  input_field_ = &field;
  lambda_vector_x_ = &lambda_vector_x;
  lambda_vector_y_ = &lambda_vector_y;
  lambda_vector_z_ = &lambda_vector_z;
  boundary_flux_kmin_ = &boundary_flux_kmin;
  boundary_flux_kmax_ = &boundary_flux_kmax;
  compute_add(result);
  input_field_ = 0;
  lambda_vector_x_ = 0;
  lambda_vector_y_ = 0;
  lambda_vector_z_ = 0;
  boundary_flux_kmin_ = boundary_flux_kmax_ = 0;
}

void OpDiffVectorialIJKScalar_double::compute_flux_x(IJK_Field_local_double & resu, const int k_layer)
{
  ConstIJK_double_ptr input_field(*input_field_, 0, 0, k_layer);
  ConstIJK_double_ptr lambda(*lambda_vector_x_, 0, 0, k_layer);
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);

  const int nx = input_field_->ni() + 1;
  const int ny = input_field_->nj();
  const double d0 = channel_data_.get_delta_x() * 0.5;
  const double d1 = d0;
  const double surface = channel_data_.get_delta_y() * channel_data_.get_delta_z()[k_layer];

{
  const int imax = nx;
  const int jmax = ny;
  const int vsize = Simd_double::size();
  for (int j = 0; ; j++) {
    for (int i = 0; i < imax; i += vsize) {   Simd_double left_val, right_val, lambda_m1, lambda_m2;
  input_field.get_left_center_x(i, left_val, right_val);
  // Fetch conductivity on neighbour cells:
  lambda.get_left_center_x(i, lambda_m1, lambda_m2);

  // geometric avg: (d0+d1) / ( d0 / lambda_m1 + d1 / lambda_m2 ), optimized with only 1 division:

  Simd_double dsabs = SimdSelect(0, d0 * lambda_m2 + d1 * lambda_m1, d0 * lambda_m2 + d1 * lambda_m1, (-1) * (d0 * lambda_m2 + d1 * lambda_m1));
  Simd_double ds = SimdSelect(dsabs, DMINFLOAT, 1., d0 * lambda_m2 + d1 * lambda_m1);
  Simd_double avg_lambda = SimdSelect(dsabs, DMINFLOAT, 0., SimdDivideMed(lambda_m1 * lambda_m2, ds));
  // thermal flux is positive if going from left to right => -grad(T)
  Simd_double flux = (left_val - right_val) * avg_lambda * surface;
  resu_ptr.put_val(i, flux);
 }
    // do not execute end_iloop at last iteration (because of assert on valid j+1)
    if (j+1==jmax)
      break; 
  input_field.next_j();
  lambda.next_j();
  resu_ptr.next_j();
  }
}

}
void OpDiffVectorialIJKScalar_double::compute_flux_y(IJK_Field_local_double & resu, const int k_layer)
{
  ConstIJK_double_ptr input_field(*input_field_, 0, 0, k_layer);
  ConstIJK_double_ptr lambda(*lambda_vector_y_, 0, 0, k_layer);
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);

  const int nx = input_field_->ni();
  const int ny = input_field_->nj() + 1;
  const double d0 = channel_data_.get_delta_y() * 0.5;
  const double d1 = d0;
  const double surface = channel_data_.get_delta_x() * channel_data_.get_delta_z()[k_layer];

{
  const int imax = nx;
  const int jmax = ny;
  const int vsize = Simd_double::size();
  for (int j = 0; ; j++) {
    for (int i = 0; i < imax; i += vsize) {   Simd_double left_val, right_val, lambda_m1, lambda_m2;
  input_field.get_left_center_y(i, left_val, right_val);
  // Fetch conductivity on neighbour cells:
  lambda.get_left_center_y(i, lambda_m1, lambda_m2);

  // geometric avg: (d0+d1) / ( d0 / lambda_m1 + d1 / lambda_m2 ), optimized with only 1 division:

  Simd_double dsabs = SimdSelect(0, d0 * lambda_m2 + d1 * lambda_m1, d0 * lambda_m2 + d1 * lambda_m1, (-1) * (d0 * lambda_m2 + d1 * lambda_m1));
  Simd_double ds = SimdSelect(dsabs, DMINFLOAT, 1., d0 * lambda_m2 + d1 * lambda_m1);
  Simd_double avg_lambda = SimdSelect(dsabs, DMINFLOAT, 0., SimdDivideMed(lambda_m1 * lambda_m2, ds));
  // thermal flux is positive if going from left to right => -grad(T)
  Simd_double flux = (left_val - right_val) * avg_lambda * surface;
  resu_ptr.put_val(i, flux);
 }
    // do not execute end_iloop at last iteration (because of assert on valid j+1)
    if (j+1==jmax)
      break; 
  input_field.next_j();
  lambda.next_j();
  resu_ptr.next_j();
  }
}

}
void OpDiffVectorialIJKScalar_double::compute_flux_z(IJK_Field_local_double & resu, const int k_layer)
{
  ConstIJK_double_ptr input_field(*input_field_, 0, 0, k_layer);
  ConstIJK_double_ptr lambda(*lambda_vector_z_, 0, 0, k_layer);
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);
  // Are we on the wall ?
  const int global_k_layer = k_layer + channel_data_.offset_to_global_k_layer();
  // global index of the layer of flux of the wall
  //  (assume one walls at zmin and zmax)
  const int first_global_k_layer = 0; // index of k_layer when we are on the wall
  // Fluxes in direction k are on the faces, hence, index of last flux is equal to number of elements
  const int last_global_k_layer =  channel_data_.nb_elem_k_tot();

  if (!perio_k_)
    {
      if (global_k_layer == first_global_k_layer)
        {
          // We are on wall at kmin, copy boundary condition fluxes to "resu"
          if (boundary_flux_kmin_) // boundary condition is not zero flux
            copy_boundary_condition(*boundary_flux_kmin_, resu);
          else
            putzero(resu);
          return;
        }
      else if (global_k_layer == last_global_k_layer)
        {
          if (boundary_flux_kmax_) // boundary condition is not zero flux
            copy_boundary_condition(*boundary_flux_kmax_, resu);
          else
            putzero(resu);
          return;
        }
    }

  const int nx = input_field_->ni();
  const int ny = input_field_->nj();
  const double d0 = channel_data_.get_delta_z()[k_layer-1] * 0.5;
  const double d1 = channel_data_.get_delta_z()[k_layer] * 0.5;
  const double surface = channel_data_.get_delta_x() * channel_data_.get_delta_y();

{
  const int imax = nx;
  const int jmax = ny;
  const int vsize = Simd_double::size();
  for (int j = 0; ; j++) {
    for (int i = 0; i < imax; i += vsize) {   Simd_double left_val, right_val, lambda_m1, lambda_m2;
  input_field.get_left_center_z(i, left_val, right_val);
  // Fetch conductivity on neighbour cells:
  lambda.get_left_center_z(i, lambda_m1, lambda_m2);

  // geometric avg: (d0+d1) / ( d0 / lambda_m1 + d1 / lambda_m2 ), optimized with only 1 division:

  Simd_double dsabs = SimdSelect(0, d0 * lambda_m2 + d1 * lambda_m1, d0 * lambda_m2 + d1 * lambda_m1, (-1) * (d0 * lambda_m2 + d1 * lambda_m1));
  Simd_double ds = SimdSelect(dsabs, DMINFLOAT, 1., d0 * lambda_m2 + d1 * lambda_m1);
  Simd_double avg_lambda = SimdSelect(dsabs, DMINFLOAT, 0., SimdDivideMed(lambda_m1 * lambda_m2, ds));
  // thermal flux is positive if going from left to right => -grad(T)
  Simd_double flux = (left_val - right_val) * avg_lambda * surface;
  resu_ptr.put_val(i, flux);
 }
    // do not execute end_iloop at last iteration (because of assert on valid j+1)
    if (j+1==jmax)
      break; 
  input_field.next_j();
  lambda.next_j();
  resu_ptr.next_j();
  }
}

}

OpDiffVectorialAnisotropicIJKScalar_double::OpDiffVectorialAnisotropicIJKScalar_double()
{
  input_field_ = 0;
  lambda_vector_x_ = 0;
  lambda_vector_y_ = 0;
  lambda_vector_z_ = 0;
  boundary_flux_kmin_ = boundary_flux_kmax_ = 0;
}

void OpDiffVectorialAnisotropicIJKScalar_double::initialize(const IJK_Splitting & splitting)
{
  channel_data_.initialize(splitting);
  perio_k_= splitting.get_grid_geometry().get_periodic_flag(DIRECTION_K);
}

void OpDiffVectorialAnisotropicIJKScalar_double::calculer(const IJK_Field_double & field, 
                                  const IJK_Field_double & lambda_vector_x,
                                  const IJK_Field_double & lambda_vector_y,
                                  const IJK_Field_double & lambda_vector_z,
                                  IJK_Field_double & result,
                                  const IJK_Field_local_double & boundary_flux_kmin,
                                  const IJK_Field_local_double & boundary_flux_kmax)
{
  input_field_ = &field;
  lambda_vector_x_ = &lambda_vector_x;
  lambda_vector_y_ = &lambda_vector_y;
  lambda_vector_z_ = &lambda_vector_z;
  boundary_flux_kmin_ = &boundary_flux_kmin;
  boundary_flux_kmax_ = &boundary_flux_kmax;
  compute_set(result);
  input_field_ = 0;
  lambda_vector_x_ = 0;
  lambda_vector_y_ = 0;
  lambda_vector_z_ = 0;
  boundary_flux_kmin_ = boundary_flux_kmax_ = 0;
}

void OpDiffVectorialAnisotropicIJKScalar_double::ajouter(const IJK_Field_double & field, 
                                 const IJK_Field_double & lambda_vector_x,
                                 const IJK_Field_double & lambda_vector_y,
                                 const IJK_Field_double & lambda_vector_z,
                                 IJK_Field_double & result,
                                 const IJK_Field_local_double & boundary_flux_kmin,
                                 const IJK_Field_local_double & boundary_flux_kmax)
{
  input_field_ = &field;
  lambda_vector_x_ = &lambda_vector_x;
  lambda_vector_y_ = &lambda_vector_y;
  lambda_vector_z_ = &lambda_vector_z;
  boundary_flux_kmin_ = &boundary_flux_kmin;
  boundary_flux_kmax_ = &boundary_flux_kmax;
  compute_add(result);
  input_field_ = 0;
  lambda_vector_x_ = 0;
  lambda_vector_y_ = 0;
  lambda_vector_z_ = 0;
  boundary_flux_kmin_ = boundary_flux_kmax_ = 0;
}

void OpDiffVectorialAnisotropicIJKScalar_double::compute_flux_x(IJK_Field_local_double & resu, const int k_layer)
{
  ConstIJK_double_ptr input_field(*input_field_, 0, 0, k_layer);
  ConstIJK_double_ptr lambda(*lambda_vector_x_, 0, 0, k_layer);
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);

  const int nx = input_field_->ni() + 1;
  const int ny = input_field_->nj();
  const double d0 = channel_data_.get_delta_x() * 0.5;
  const double d1 = d0;
  const double surface = channel_data_.get_delta_y() * channel_data_.get_delta_z()[k_layer];

{
  const int imax = nx;
  const int jmax = ny;
  const int vsize = Simd_double::size();
  for (int j = 0; ; j++) {
    for (int i = 0; i < imax; i += vsize) {   const double d = d0 + d1;
  Simd_double left_val, right_val, lambda_m1, lambda_m2;
  input_field.get_left_center_x(i, left_val, right_val);
  // Fetch conductivity on neighbour cells:
  lambda.get_left_center_x(i, lambda_m1, lambda_m2);

  // geometric avg: (d0+d1) / ( d0 / lambda_m1 + d1 / lambda_m2 ), optimized with only 1 division:

  Simd_double dsabs = SimdSelect(0, d0 * lambda_m2 + d1 * lambda_m1, d0 * lambda_m2 + d1 * lambda_m1, (-1) * (d0 * lambda_m2 + d1 * lambda_m1));
  Simd_double ds = SimdSelect(dsabs, DMINFLOAT, 1., d0 * lambda_m2 + d1 * lambda_m1);
  Simd_double avg_lambda = SimdSelect(dsabs, DMINFLOAT, 0., SimdDivideMed(d * lambda_m1 * lambda_m2, ds));
  // thermal flux is positive if going from left to right => -grad(T)
  Simd_double flux = (left_val - right_val) * avg_lambda * surface;
  resu_ptr.put_val(i, flux);
 }
    // do not execute end_iloop at last iteration (because of assert on valid j+1)
    if (j+1==jmax)
      break; 
  input_field.next_j();
  lambda.next_j();
  resu_ptr.next_j();
  }
}

}
void OpDiffVectorialAnisotropicIJKScalar_double::compute_flux_y(IJK_Field_local_double & resu, const int k_layer)
{
  ConstIJK_double_ptr input_field(*input_field_, 0, 0, k_layer);
  ConstIJK_double_ptr lambda(*lambda_vector_y_, 0, 0, k_layer);
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);

  const int nx = input_field_->ni();
  const int ny = input_field_->nj() + 1;
  const double d0 = channel_data_.get_delta_y() * 0.5;
  const double d1 = d0;
  const double surface = channel_data_.get_delta_x() * channel_data_.get_delta_z()[k_layer];

{
  const int imax = nx;
  const int jmax = ny;
  const int vsize = Simd_double::size();
  for (int j = 0; ; j++) {
    for (int i = 0; i < imax; i += vsize) {   const double d = d0 + d1;
  Simd_double left_val, right_val, lambda_m1, lambda_m2;
  input_field.get_left_center_y(i, left_val, right_val);
  // Fetch conductivity on neighbour cells:
  lambda.get_left_center_y(i, lambda_m1, lambda_m2);

  // geometric avg: (d0+d1) / ( d0 / lambda_m1 + d1 / lambda_m2 ), optimized with only 1 division:

  Simd_double dsabs = SimdSelect(0, d0 * lambda_m2 + d1 * lambda_m1, d0 * lambda_m2 + d1 * lambda_m1, (-1) * (d0 * lambda_m2 + d1 * lambda_m1));
  Simd_double ds = SimdSelect(dsabs, DMINFLOAT, 1., d0 * lambda_m2 + d1 * lambda_m1);
  Simd_double avg_lambda = SimdSelect(dsabs, DMINFLOAT, 0., SimdDivideMed(d * lambda_m1 * lambda_m2, ds));
  // thermal flux is positive if going from left to right => -grad(T)
  Simd_double flux = (left_val - right_val) * avg_lambda * surface;
  resu_ptr.put_val(i, flux);
 }
    // do not execute end_iloop at last iteration (because of assert on valid j+1)
    if (j+1==jmax)
      break; 
  input_field.next_j();
  lambda.next_j();
  resu_ptr.next_j();
  }
}

}
void OpDiffVectorialAnisotropicIJKScalar_double::compute_flux_z(IJK_Field_local_double & resu, const int k_layer)
{
  ConstIJK_double_ptr input_field(*input_field_, 0, 0, k_layer);
  ConstIJK_double_ptr lambda(*lambda_vector_z_, 0, 0, k_layer);
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);
  // Are we on the wall ?
  const int global_k_layer = k_layer + channel_data_.offset_to_global_k_layer();
  // global index of the layer of flux of the wall
  //  (assume one walls at zmin and zmax)
  const int first_global_k_layer = 0; // index of k_layer when we are on the wall
  // Fluxes in direction k are on the faces, hence, index of last flux is equal to number of elements
  const int last_global_k_layer =  channel_data_.nb_elem_k_tot();

  if (!perio_k_)
    {
      if (global_k_layer == first_global_k_layer)
        {
          // We are on wall at kmin, copy boundary condition fluxes to "resu"
          if (boundary_flux_kmin_) // boundary condition is not zero flux
            copy_boundary_condition(*boundary_flux_kmin_, resu);
          else
            putzero(resu);
          return;
        }
      else if (global_k_layer == last_global_k_layer)
        {
          if (boundary_flux_kmax_) // boundary condition is not zero flux
            copy_boundary_condition(*boundary_flux_kmax_, resu);
          else
            putzero(resu);
          return;
        }
    }

  const int nx = input_field_->ni();
  const int ny = input_field_->nj();
  const double d0 = channel_data_.get_delta_z()[k_layer-1] * 0.5;
  const double d1 = channel_data_.get_delta_z()[k_layer] * 0.5;
  const double surface = channel_data_.get_delta_x() * channel_data_.get_delta_y();

{
  const int imax = nx;
  const int jmax = ny;
  const int vsize = Simd_double::size();
  for (int j = 0; ; j++) {
    for (int i = 0; i < imax; i += vsize) {   const double d = d0 + d1;
  Simd_double left_val, right_val, lambda_m1, lambda_m2;
  input_field.get_left_center_z(i, left_val, right_val);
  // Fetch conductivity on neighbour cells:
  lambda.get_left_center_z(i, lambda_m1, lambda_m2);

  // geometric avg: (d0+d1) / ( d0 / lambda_m1 + d1 / lambda_m2 ), optimized with only 1 division:

  Simd_double dsabs = SimdSelect(0, d0 * lambda_m2 + d1 * lambda_m1, d0 * lambda_m2 + d1 * lambda_m1, (-1) * (d0 * lambda_m2 + d1 * lambda_m1));
  Simd_double ds = SimdSelect(dsabs, DMINFLOAT, 1., d0 * lambda_m2 + d1 * lambda_m1);
  Simd_double avg_lambda = SimdSelect(dsabs, DMINFLOAT, 0., SimdDivideMed(d * lambda_m1 * lambda_m2, ds));
  // thermal flux is positive if going from left to right => -grad(T)
  Simd_double flux = (left_val - right_val) * avg_lambda * surface;
  resu_ptr.put_val(i, flux);
 }
    // do not execute end_iloop at last iteration (because of assert on valid j+1)
    if (j+1==jmax)
      break; 
  input_field.next_j();
  lambda.next_j();
  resu_ptr.next_j();
  }
}

}

OpDiffIJKScalarStructuralOnly_double::OpDiffIJKScalarStructuralOnly_double()
{
  input_field_ = 0;
  structural_model_x_ = 0;
  structural_model_y_ = 0;
  structural_model_z_ = 0;
  boundary_flux_kmin_ = boundary_flux_kmax_ = 0;
}

void OpDiffIJKScalarStructuralOnly_double::initialize(const IJK_Splitting & splitting)
{
  channel_data_.initialize(splitting);
  perio_k_= splitting.get_grid_geometry().get_periodic_flag(DIRECTION_K);
}

void OpDiffIJKScalarStructuralOnly_double::calculer(const IJK_Field_double & field, 
                                  const IJK_Field_double & structural_model_x,
                                  const IJK_Field_double & structural_model_y,
                                  const IJK_Field_double & structural_model_z,
                                  IJK_Field_double & result,
                                  const IJK_Field_local_double & boundary_flux_kmin,
                                  const IJK_Field_local_double & boundary_flux_kmax)
{
  input_field_ = &field;
  structural_model_x_ = &structural_model_x;
  structural_model_y_ = &structural_model_y;
  structural_model_z_ = &structural_model_z;
  boundary_flux_kmin_ = &boundary_flux_kmin;
  boundary_flux_kmax_ = &boundary_flux_kmax;
  compute_set(result);
  input_field_ = 0;
  structural_model_x_ = 0;
  structural_model_y_ = 0;
  structural_model_z_ = 0;
  boundary_flux_kmin_ = boundary_flux_kmax_ = 0;
}

void OpDiffIJKScalarStructuralOnly_double::ajouter(const IJK_Field_double & field, 
                                 const IJK_Field_double & structural_model_x,
                                 const IJK_Field_double & structural_model_y,
                                 const IJK_Field_double & structural_model_z,
                                 IJK_Field_double & result,
                                 const IJK_Field_local_double & boundary_flux_kmin,
                                 const IJK_Field_local_double & boundary_flux_kmax)
{
  input_field_ = &field;
  structural_model_x_ = &structural_model_x;
  structural_model_y_ = &structural_model_y;
  structural_model_z_ = &structural_model_z;
  boundary_flux_kmin_ = &boundary_flux_kmin;
  boundary_flux_kmax_ = &boundary_flux_kmax;
  compute_add(result);
  input_field_ = 0;
  structural_model_x_ = 0;
  structural_model_y_ = 0;
  structural_model_z_ = 0;
  boundary_flux_kmin_ = boundary_flux_kmax_ = 0;
}

void OpDiffIJKScalarStructuralOnly_double::compute_flux_x(IJK_Field_local_double & resu, const int k_layer)
{
  ConstIJK_double_ptr input_field(*input_field_, 0, 0, k_layer);
  ConstIJK_double_ptr structural_model(*structural_model_x_, 0, 0, k_layer);
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);

  const int nx = input_field_->ni() + 1;
  const int ny = input_field_->nj();
  const double surface = channel_data_.get_delta_y() * channel_data_.get_delta_z()[k_layer];

{
  const int imax = nx;
  const int jmax = ny;
  const int vsize = Simd_double::size();
  for (int j = 0; ; j++) {
    for (int i = 0; i < imax; i += vsize) {   Simd_double s_mo, s_mo_dummy;
  structural_model.get_left_center_x(i, s_mo_dummy, s_mo);
  Simd_double flux = (-1.) * s_mo * surface;
  resu_ptr.put_val(i, flux);
 }
    // do not execute end_iloop at last iteration (because of assert on valid j+1)
    if (j+1==jmax)
      break; 
  input_field.next_j();
  structural_model.next_j();
  resu_ptr.next_j();
  }
}

}
void OpDiffIJKScalarStructuralOnly_double::compute_flux_y(IJK_Field_local_double & resu, const int k_layer)
{
  ConstIJK_double_ptr input_field(*input_field_, 0, 0, k_layer);
  ConstIJK_double_ptr structural_model(*structural_model_y_, 0, 0, k_layer);
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);

  const int nx = input_field_->ni();
  const int ny = input_field_->nj() + 1;
  const double surface = channel_data_.get_delta_x() * channel_data_.get_delta_z()[k_layer];

{
  const int imax = nx;
  const int jmax = ny;
  const int vsize = Simd_double::size();
  for (int j = 0; ; j++) {
    for (int i = 0; i < imax; i += vsize) {   Simd_double s_mo, s_mo_dummy;
  structural_model.get_left_center_y(i, s_mo_dummy, s_mo);
  Simd_double flux = (-1.) * s_mo * surface;
  resu_ptr.put_val(i, flux);
 }
    // do not execute end_iloop at last iteration (because of assert on valid j+1)
    if (j+1==jmax)
      break; 
  input_field.next_j();
  structural_model.next_j();
  resu_ptr.next_j();
  }
}

}
void OpDiffIJKScalarStructuralOnly_double::compute_flux_z(IJK_Field_local_double & resu, const int k_layer)
{
  ConstIJK_double_ptr input_field(*input_field_, 0, 0, k_layer);
  ConstIJK_double_ptr structural_model(*structural_model_z_, 0, 0, k_layer);
  IJK_double_ptr resu_ptr(resu, 0, 0, 0);
  // Are we on the wall ?
  const int global_k_layer = k_layer + channel_data_.offset_to_global_k_layer();
  // global index of the layer of flux of the wall
  //  (assume one walls at zmin and zmax)
  const int first_global_k_layer = 0; // index of k_layer when we are on the wall
  // Fluxes in direction k are on the faces, hence, index of last flux is equal to number of elements
  const int last_global_k_layer =  channel_data_.nb_elem_k_tot();

  if (!perio_k_)
    {
      if (global_k_layer == first_global_k_layer)
        {
          // We are on wall at kmin, copy boundary condition fluxes to "resu"
          if (boundary_flux_kmin_) // boundary condition is not zero flux
            copy_boundary_condition(*boundary_flux_kmin_, resu);
          else
            putzero(resu);
          return;
        }
      else if (global_k_layer == last_global_k_layer)
        {
          if (boundary_flux_kmax_) // boundary condition is not zero flux
            copy_boundary_condition(*boundary_flux_kmax_, resu);
          else
            putzero(resu);
          return;
        }
    }

  const int nx = input_field_->ni();
  const int ny = input_field_->nj();
  const double surface = channel_data_.get_delta_x() * channel_data_.get_delta_y();

{
  const int imax = nx;
  const int jmax = ny;
  const int vsize = Simd_double::size();
  for (int j = 0; ; j++) {
    for (int i = 0; i < imax; i += vsize) {   Simd_double s_mo, s_mo_dummy;
  structural_model.get_left_center_z(i, s_mo_dummy, s_mo);
  Simd_double flux = (-1.) * s_mo * surface;
  resu_ptr.put_val(i, flux);
 }
    // do not execute end_iloop at last iteration (because of assert on valid j+1)
    if (j+1==jmax)
      break; 
  input_field.next_j();
  structural_model.next_j();
  resu_ptr.next_j();
  }
}

}

