#!/bin/bash
[ -f $1.lml ] && gzip -f $1.lml
[ -f $1 == "ijkft_follow_colors_multi_seq" ] && tail -n2 ijkft_follow_colors_multi_seq_bulles_colors.out > suivi.txt
[ -f $1 == "ijkft_follow_colors_multi_repr_seq" ] && head -n2 ijkft_follow_colors_multi_repr_seq_bulles_colors.out >> suivi.txt
