Statistiques de post resolution

Temps total                       2.64547


Timesteps                         1
Secondes / pas de temps           2.37064
Dont solveurs Ax=B                0.096997  4% (20 appels/pas de temps)
Dont operateurs convection        0.002635  0% (207 appels/pas de temps)
Dont operateurs diffusion         0.904518 38% (3 appels/pas de temps)
Dont operations postraitement     0.041988  1% (2 appels/pas de temps)
Dont calcul divers                -1.017285 -42% (0 appels/pas de temps)
Nb echange_espace_virtuel / pas de temps 2574
Nb solveur / pas de temps         20
Secondes / solveur                0.00484985
Iterations / solveur              31.6
I/O:

Timesteps = number of time steps
Nb solveur = number of linear system resolutions
Nb assemblage implicite = number of matrix assemblies for the implicit scheme
Iterations = average number of iterations of the solver
Communications = fraction of the time spent
                 in communications between processors (excluding io files)
Network latency = time of one mpsum measured by an internal bench over 0.1s
Network bandwidth = maximum on all processors
                    of the average bandwidth of send_recv operations
Waiting time = estimation of the waiting time of the different processors

Max_waiting_time big    => probably due to a bad partitioning
Communications > 30%    => too many processors or network too slow

Statistiques de post resolution

Temps total                       2.64061


Timesteps                         1
Secondes / pas de temps           2.36261
Dont solveurs Ax=B                0.102751  4% (20 appels/pas de temps)
Dont operateurs convection        0.002733  0% (207 appels/pas de temps)
Dont operateurs diffusion         0.889685 37% (3 appels/pas de temps)
Dont operations postraitement     0.043076  1% (2 appels/pas de temps)
Dont calcul divers                -1.007246 -42% (0 appels/pas de temps)
Nb echange_espace_virtuel / pas de temps 2568
Nb solveur / pas de temps         20
Secondes / solveur                0.00513755
Iterations / solveur              31.5
I/O:

Timesteps = number of time steps
Nb solveur = number of linear system resolutions
Nb assemblage implicite = number of matrix assemblies for the implicit scheme
Iterations = average number of iterations of the solver
Communications = fraction of the time spent
                 in communications between processors (excluding io files)
Network latency = time of one mpsum measured by an internal bench over 0.1s
Network bandwidth = maximum on all processors
                    of the average bandwidth of send_recv operations
Waiting time = estimation of the waiting time of the different processors

Max_waiting_time big    => probably due to a bad partitioning
Communications > 30%    => too many processors or network too slow

Statistiques de post resolution

Temps total                       2.67505


Timesteps                         1
Secondes / pas de temps           2.38918
Dont solveurs Ax=B                0.103581  4% (20 appels/pas de temps)
Dont operateurs convection        0.002793  0% (207 appels/pas de temps)
Dont operateurs diffusion         0.895862 37% (3 appels/pas de temps)
Dont operations postraitement     0.043762  1% (2 appels/pas de temps)
Dont calcul divers                -1.014523 -42% (0 appels/pas de temps)
Nb echange_espace_virtuel / pas de temps 2568
Nb solveur / pas de temps         20
Secondes / solveur                0.00517905
Iterations / solveur              31.5
I/O:

Timesteps = number of time steps
Nb solveur = number of linear system resolutions
Nb assemblage implicite = number of matrix assemblies for the implicit scheme
Iterations = average number of iterations of the solver
Communications = fraction of the time spent
                 in communications between processors (excluding io files)
Network latency = time of one mpsum measured by an internal bench over 0.1s
Network bandwidth = maximum on all processors
                    of the average bandwidth of send_recv operations
Waiting time = estimation of the waiting time of the different processors

Max_waiting_time big    => probably due to a bad partitioning
Communications > 30%    => too many processors or network too slow

Statistiques de post resolution

Temps total                       2.46599


Timesteps                         1
Secondes / pas de temps           2.17079
Dont solveurs Ax=B                0.104952  4% (20 appels/pas de temps)
Dont operateurs convection        0.002827  0% (207 appels/pas de temps)
Dont operateurs diffusion         0.736010 33% (3 appels/pas de temps)
Dont operations postraitement     0.043001  1% (2 appels/pas de temps)
Dont calcul divers                -0.855542 -39% (0 appels/pas de temps)
Nb echange_espace_virtuel / pas de temps 2568
Nb solveur / pas de temps         20
Secondes / solveur                0.0052476
Iterations / solveur              31.5
I/O:

Timesteps = number of time steps
Nb solveur = number of linear system resolutions
Nb assemblage implicite = number of matrix assemblies for the implicit scheme
Iterations = average number of iterations of the solver
Communications = fraction of the time spent
                 in communications between processors (excluding io files)
Network latency = time of one mpsum measured by an internal bench over 0.1s
Network bandwidth = maximum on all processors
                    of the average bandwidth of send_recv operations
Waiting time = estimation of the waiting time of the different processors

Max_waiting_time big    => probably due to a bad partitioning
Communications > 30%    => too many processors or network too slow

Statistiques de post resolution

Temps total                       2.47581


Timesteps                         1
Secondes / pas de temps           2.17497
Dont solveurs Ax=B                0.102179  4% (20 appels/pas de temps)
Dont operateurs convection        0.002962  0% (207 appels/pas de temps)
Dont operateurs diffusion         0.742532 34% (3 appels/pas de temps)
Dont operations postraitement     0.042452  1% (2 appels/pas de temps)
Dont calcul divers                -0.858031 -39% (0 appels/pas de temps)
Nb echange_espace_virtuel / pas de temps 2568
Nb solveur / pas de temps         20
Secondes / solveur                0.00510895
Iterations / solveur              31.5
I/O:

Timesteps = number of time steps
Nb solveur = number of linear system resolutions
Nb assemblage implicite = number of matrix assemblies for the implicit scheme
Iterations = average number of iterations of the solver
Communications = fraction of the time spent
                 in communications between processors (excluding io files)
Network latency = time of one mpsum measured by an internal bench over 0.1s
Network bandwidth = maximum on all processors
                    of the average bandwidth of send_recv operations
Waiting time = estimation of the waiting time of the different processors

Max_waiting_time big    => probably due to a bad partitioning
Communications > 30%    => too many processors or network too slow

Statistiques de post resolution

Temps total                       2.72589


Timesteps                         1
Secondes / pas de temps           2.43494
Dont solveurs Ax=B                0.104303  4% (20 appels/pas de temps)
Dont operateurs convection        0.002849  0% (207 appels/pas de temps)
Dont operateurs diffusion         0.924658 37% (3 appels/pas de temps)
Dont operations postraitement     0.044351  1% (2 appels/pas de temps)
Dont calcul divers                -1.044662 -42% (0 appels/pas de temps)
Nb echange_espace_virtuel / pas de temps 2568
Nb solveur / pas de temps         20
Secondes / solveur                0.00521515
Iterations / solveur              31.5
I/O:

Timesteps = number of time steps
Nb solveur = number of linear system resolutions
Nb assemblage implicite = number of matrix assemblies for the implicit scheme
Iterations = average number of iterations of the solver
Communications = fraction of the time spent
                 in communications between processors (excluding io files)
Network latency = time of one mpsum measured by an internal bench over 0.1s
Network bandwidth = maximum on all processors
                    of the average bandwidth of send_recv operations
Waiting time = estimation of the waiting time of the different processors

Max_waiting_time big    => probably due to a bad partitioning
Communications > 30%    => too many processors or network too slow

Statistiques de post resolution

Temps total                       2.52605


Timesteps                         1
Secondes / pas de temps           2.16768
Dont solveurs Ax=B                0.102627  4% (20 appels/pas de temps)
Dont operateurs convection        0.002937  0% (207 appels/pas de temps)
Dont operateurs diffusion         0.737738 34% (3 appels/pas de temps)
Dont operations postraitement     0.044645  2% (2 appels/pas de temps)
Dont calcul divers                -0.855965 -39% (0 appels/pas de temps)
Nb echange_espace_virtuel / pas de temps 2568
Nb solveur / pas de temps         20
Secondes / solveur                0.00513135
Iterations / solveur              31.5
I/O:

Timesteps = number of time steps
Nb solveur = number of linear system resolutions
Nb assemblage implicite = number of matrix assemblies for the implicit scheme
Iterations = average number of iterations of the solver
Communications = fraction of the time spent
                 in communications between processors (excluding io files)
Network latency = time of one mpsum measured by an internal bench over 0.1s
Network bandwidth = maximum on all processors
                    of the average bandwidth of send_recv operations
Waiting time = estimation of the waiting time of the different processors

Max_waiting_time big    => probably due to a bad partitioning
Communications > 30%    => too many processors or network too slow

Statistiques de post resolution

Temps total                       55.807


Timesteps                         1
Secondes / pas de temps           54.2911
Dont solveurs Ax=B                0.496196  0% (20 appels/pas de temps)
Dont operateurs convection        0.133613  0% (207 appels/pas de temps)
Dont operateurs diffusion         2.497753  4% (3 appels/pas de temps)
Dont operations postraitement     0.537439  0% (2 appels/pas de temps)
Dont calcul divers                -3.428592 -6% (0 appels/pas de temps)
Nb echange_espace_virtuel / pas de temps 2568
Nb solveur / pas de temps         20
Secondes / solveur                0.0248098
Iterations / solveur              31.5
I/O:

Timesteps = number of time steps
Nb solveur = number of linear system resolutions
Nb assemblage implicite = number of matrix assemblies for the implicit scheme
Iterations = average number of iterations of the solver
Communications = fraction of the time spent
                 in communications between processors (excluding io files)
Network latency = time of one mpsum measured by an internal bench over 0.1s
Network bandwidth = maximum on all processors
                    of the average bandwidth of send_recv operations
Waiting time = estimation of the waiting time of the different processors

Max_waiting_time big    => probably due to a bad partitioning
Communications > 30%    => too many processors or network too slow

Statistiques de post resolution

Temps total                       9.09829


Timesteps                         1
Secondes / pas de temps           8.81126
Dont solveurs Ax=B                0.478715  5% (20 appels/pas de temps)
Dont operateurs convection        0.018974  0% (105 appels/pas de temps)
Dont operateurs diffusion         0.285817  3% (3 appels/pas de temps)
Dont operations postraitement     0.100028  1% (2 appels/pas de temps)
Dont calcul divers                -0.714963 -8% (0 appels/pas de temps)
Nb echange_espace_virtuel / pas de temps 578
Nb MPI_allreduce / pas de temps 2570
-----------------------------------------------------------------------------------------------------------------------------------------
Warning: The number of MPI_allreduce calls per time step is high. Contact TRUST support if you plan to run massive parallel calculation.
-----------------------------------------------------------------------------------------------------------------------------------------
Nb solveur / pas de temps         20
Secondes / solveur                0.0239357
Iterations / solveur              53.9
I/O:
Communications avg        5.3 % of total time
Communications max        7.6 % of total time
Communications min        3.3 % of total time
Network latency benchmark 5.65052e-06 s
Network bandwidth max     809.983 MB/s
Total network traffic     891.245 MB / timestep
Average message size      4.58243 kB
Min waiting time          1.6 % of total time
Max waiting time          5.5 % of total time
Avg waiting time          3.4625 % of total time

Timesteps = number of time steps
Nb solveur = number of linear system resolutions
Nb assemblage implicite = number of matrix assemblies for the implicit scheme
Iterations = average number of iterations of the solver
Communications = fraction of the time spent
                 in communications between processors (excluding io files)
Network latency = time of one mpsum measured by an internal bench over 0.1s
Network bandwidth = maximum on all processors
                    of the average bandwidth of send_recv operations
Waiting time = estimation of the waiting time of the different processors

Max_waiting_time big    => probably due to a bad partitioning
Communications > 30%    => too many processors or network too slow

Statistiques de post resolution

Temps total                       6.41061


Timesteps                         1
Secondes / pas de temps           6.19946
Dont solveurs Ax=B                0.483841  7% (20 appels/pas de temps)
Dont operateurs convection        0.012943  0% (105 appels/pas de temps)
Dont operateurs diffusion         0.193150  3% (3 appels/pas de temps)
Dont operations postraitement     0.079497  1% (2 appels/pas de temps)
Dont calcul divers                -0.646378 -10% (0 appels/pas de temps)
Nb echange_espace_virtuel / pas de temps 578
Nb MPI_allreduce / pas de temps 2512
-----------------------------------------------------------------------------------------------------------------------------------------
Warning: The number of MPI_allreduce calls per time step is high. Contact TRUST support if you plan to run massive parallel calculation.
-----------------------------------------------------------------------------------------------------------------------------------------
Nb solveur / pas de temps         20
Secondes / solveur                0.024192
Iterations / solveur              52.45
I/O:
Communications avg        5.7 % of total time
Communications max        7.9 % of total time
Communications min        4.6 % of total time
Network latency benchmark 6.69003e-06 s
Network bandwidth max     681.061 MB/s
Total network traffic     1052.94 MB / timestep
Average message size      2.89632 kB
Min waiting time          2.1 % of total time
Max waiting time          4.6 % of total time
Avg waiting time          3.18333 % of total time

Timesteps = number of time steps
Nb solveur = number of linear system resolutions
Nb assemblage implicite = number of matrix assemblies for the implicit scheme
Iterations = average number of iterations of the solver
Communications = fraction of the time spent
                 in communications between processors (excluding io files)
Network latency = time of one mpsum measured by an internal bench over 0.1s
Network bandwidth = maximum on all processors
                    of the average bandwidth of send_recv operations
Waiting time = estimation of the waiting time of the different processors

Max_waiting_time big    => probably due to a bad partitioning
Communications > 30%    => too many processors or network too slow

Statistiques de post resolution

Temps total                       6.39836


Timesteps                         1
Secondes / pas de temps           6.19982
Dont solveurs Ax=B                0.467267  7% (20 appels/pas de temps)
Dont operateurs convection        0.012973  0% (105 appels/pas de temps)
Dont operateurs diffusion         0.195645  3% (3 appels/pas de temps)
Dont operations postraitement     0.077931  1% (2 appels/pas de temps)
Dont calcul divers                -0.643999 -10% (0 appels/pas de temps)
Nb echange_espace_virtuel / pas de temps 578
Nb MPI_allreduce / pas de temps 2502
-----------------------------------------------------------------------------------------------------------------------------------------
Warning: The number of MPI_allreduce calls per time step is high. Contact TRUST support if you plan to run massive parallel calculation.
-----------------------------------------------------------------------------------------------------------------------------------------
Nb solveur / pas de temps         20
Secondes / solveur                0.0233633
Iterations / solveur              52.2
I/O:
Communications avg        5.1 % of total time
Communications max        6.3 % of total time
Communications min        2.5 % of total time
Network latency benchmark 6.10828e-06 s
Network bandwidth max     814.919 MB/s
Total network traffic     1051.8 MB / timestep
Average message size      2.90469 kB
Min waiting time          0.4 % of total time
Max waiting time          3.3 % of total time
Avg waiting time          2.96667 % of total time

Timesteps = number of time steps
Nb solveur = number of linear system resolutions
Nb assemblage implicite = number of matrix assemblies for the implicit scheme
Iterations = average number of iterations of the solver
Communications = fraction of the time spent
                 in communications between processors (excluding io files)
Network latency = time of one mpsum measured by an internal bench over 0.1s
Network bandwidth = maximum on all processors
                    of the average bandwidth of send_recv operations
Waiting time = estimation of the waiting time of the different processors

Max_waiting_time big    => probably due to a bad partitioning
Communications > 30%    => too many processors or network too slow

Statistiques de post resolution

Temps total                       4.80974


Timesteps                         1
Secondes / pas de temps           4.65443
Dont solveurs Ax=B                0.499658 10% (20 appels/pas de temps)
Dont operateurs convection        0.009012  0% (105 appels/pas de temps)
Dont operateurs diffusion         0.108021  2% (3 appels/pas de temps)
Dont operations postraitement     0.063983  1% (2 appels/pas de temps)
Dont calcul divers                -0.606350 -13% (0 appels/pas de temps)
Nb echange_espace_virtuel / pas de temps 578
Nb MPI_allreduce / pas de temps 2526
-----------------------------------------------------------------------------------------------------------------------------------------
Warning: The number of MPI_allreduce calls per time step is high. Contact TRUST support if you plan to run massive parallel calculation.
-----------------------------------------------------------------------------------------------------------------------------------------
Nb solveur / pas de temps         20
Secondes / solveur                0.0249829
Iterations / solveur              52.8
I/O:
Communications avg        8.2 % of total time
Communications max        9.9 % of total time
Communications min        4.9 % of total time
Network latency benchmark 8.18968e-06 s
Network bandwidth max     576.12 MB/s
Total network traffic     1198.02 MB / timestep
Average message size      1.79848 kB
Min waiting time          2.3 % of total time
Max waiting time          5.4 % of total time
Avg waiting time          4.9 % of total time

Timesteps = number of time steps
Nb solveur = number of linear system resolutions
Nb assemblage implicite = number of matrix assemblies for the implicit scheme
Iterations = average number of iterations of the solver
Communications = fraction of the time spent
                 in communications between processors (excluding io files)
Network latency = time of one mpsum measured by an internal bench over 0.1s
Network bandwidth = maximum on all processors
                    of the average bandwidth of send_recv operations
Waiting time = estimation of the waiting time of the different processors

Max_waiting_time big    => probably due to a bad partitioning
Communications > 30%    => too many processors or network too slow

Statistiques de post resolution

Temps total                       0.431419


Timesteps                         1
Secondes / pas de temps           0.349035
Dont solveurs Ax=B                0.166286 47% (20 appels/pas de temps)
Dont operateurs convection        0.000404  0% (105 appels/pas de temps)
Dont operateurs diffusion         0.014361  4% (3 appels/pas de temps)
Dont operations postraitement     0.021504  6% (2 appels/pas de temps)
Dont calcul divers                -0.149728 -42% (0 appels/pas de temps)
Nb echange_espace_virtuel / pas de temps 578
Nb MPI_allreduce / pas de temps 2479
-----------------------------------------------------------------------------------------------------------------------------------------
Warning: The number of MPI_allreduce calls per time step is high. Contact TRUST support if you plan to run massive parallel calculation.
-----------------------------------------------------------------------------------------------------------------------------------------
Nb solveur / pas de temps         20
Secondes / solveur                0.0083143
Iterations / solveur              52.6
I/O:
Communications avg        45.6 % of total time
Communications max        51.6 % of total time
Communications min        21.9 % of total time
Network latency benchmark 7.09057e-06 s
Network bandwidth max     1333.03 MB/s
Total network traffic     1197 MB / timestep
Average message size      1.82272 kB
Min waiting time          4.2 % of total time
Max waiting time          31.4 % of total time
Avg waiting time          28.0944 % of total time

Timesteps = number of time steps
Nb solveur = number of linear system resolutions
Nb assemblage implicite = number of matrix assemblies for the implicit scheme
Iterations = average number of iterations of the solver
Communications = fraction of the time spent
                 in communications between processors (excluding io files)
Network latency = time of one mpsum measured by an internal bench over 0.1s
Network bandwidth = maximum on all processors
                    of the average bandwidth of send_recv operations
Waiting time = estimation of the waiting time of the different processors

Max_waiting_time big    => probably due to a bad partitioning
Communications > 30%    => too many processors or network too slow

