#!/bin/bash
gunzip -c dom_3D.geom.gz > dom_3D.geom
#Creation des repertoires test 1
mkdir -p ./Amont
mkdir -p ./Muscl
mkdir -p ./Negligeable
mkdir -p ./EF_stab02

#############
RACINE=`pwd`

echo $RACINE


#####################
##################### 
#####################
#
cd $RACINE/Amont
cp $RACINE/ppv.data test.data
cp $RACINE/post_run .
#
cd $RACINE/Muscl
cp $RACINE/ppv.data test.data
sed "s/convection { Amont }/convection { Muscl }/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
#
cd $RACINE/Negligeable
cp $RACINE/ppv.data test.data
sed "s/convection { Amont }/convection { Negligeable }/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
#
cd $RACINE/EF_stab02
cp $RACINE/ppv.data test.data
sed "s/convection { Amont }/convection { EF_stab { alpha 0.2 } }/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
