#!/bin/bash
# Ce script est execute avant de lancer les cas tests

# Generation des interfaces pour l'etat initial:
# On suppose que gmsh a deja ete execute avec cette commande:
gmsh bulle_nulle.geo -2 -format msh2

# Generation de 3 bulles  :
# 0.01 0.0025 0.0025 bulle3.msh
cat >deplacements.txt <<EOF
0.0 0.0 0.0 bulle3.msh
EOF
./cree_multi_bulles.sh deplacements.txt init.lata


# Placement des sondes
${project_directory}/share/PyTools/probes/place_sondes.sh spectral spectral_point2 cree [2,2,2,.] [force_ph,velocity]

# Deplacement de ce qui est utile au calcul dans le dossier RUN00

# Recuperation du numero de RUN
currentRepo=$PWD
re='^[0-9]+$'>--
if ! [[ $jobid =~ $re ]] ; then
    jobidnext=00
    newRepo=RUN00
    mkdir -p $newRepo/NEXT
    mv spectral_point2.data $newRepo
    mv init.lata* $newRepo
    mv post_run $newRepo
    cp like_sub_file $newRepo
    cp prepare $newRepo
else
  jobidnext=$((jobid+1))
  newRepo="../RUN$(printf "%02d" $jobidnext)"
    mv spectral_point2.data $newRepo
    mv init.lata* $newRepo
    mv post_run $newRepo
    cp like_sub_file $newRepo
    cp prepare $newRepo
fi


