#!/bin/bash

for i in "interp_standard" "interp_modifiee" "interp_ai_based" 
do
  #for j in "CORRECTION_GHOST_INDIC"
  #for j in "NO_CORRECTION" "ZERO_NET_FLUX_ON_MIXED_CELLS" "ZERO_OUT_FLUX_ON_MIXED_CELLS"
  for j in "NO_CORRECTION" "CORRECTION_GHOST_INDIC" "ZERO_NET_FLUX_ON_MIXED_CELLS" "ZERO_OUT_FLUX_ON_MIXED_CELLS"
  do
    name=${i}_${j}
    sed -e "s/interpol_indic_pour_dI_dt.*/interpol_indic_pour_dI_dt $i/" \
	-e "s/OutletCorrection_pour_dI_dt .*/OutletCorrection_pour_dI_dt $j/" \
	-e "s/template/${name}/" \
	template.data > ${name}.data
    echo "Running calculation ${name}"
    time trust ${name} 1>${name}.out 2>${name}.err &
    [ $? != 0 ] && echo "Failure in ${name}"
    grep "Volume_phase_0" ${name}.err | awk '{print $4, $2/(0.001*0.001*3.141592653589793/2)}' > ${name}.txt
  done
done
# Wait for all jobs to finish.
wait
echo "$0 finished in $PWD"
