#!/bin/bash

gunzip -c jetsymfine3.geom.gz > jetsymfine3.geom

cp TSW_jet.data test.data
sed -i "s/ BEGIN MESH #/ BEGIN MESH/; s/# END MESH/END MESH/; s/BEGIN SCATTER/BEGIN SCATTER #/; s/END SCATTER/# END SCATTER/" test.data

folders="./v_1/EF_stab ./v_1/EF_stab02 ./v_156/EF_stab ./v_156/EF_stab02"

for fold in $folders
do
   mkdir -p $fold
   cp jetsymfine3.geom TSW_jet.data post_run pre_run curves.py $fold
   cp test.data $fold/test.data
done

sed -i "s/w<0.15/w<0.19/" v_1/EF_stab02/curves.py
sed -i "s/w<0.15/w<0.19/" v_156/EF_stab02/curves.py
sed -i "s/w<0.15/w<0.13/" v_156/EF_stab/curves.py 

sed -i "s/Ef_stab { }/Ef_stab { alpha 0.2 }/" v_1/EF_stab02/test.data

sed -i "s/3 0.0 0.0 1.0/3 0.0 0.0 1.56/;s/2 0.0051886 0.2924415/2 0.0112985 0.9397039/;s/2 1.0e-5 1.0e-5/2 0.1e-5 0.1e-5/;s/tmax 4/tmax 3/" v_156/EF_stab/test.data

sed "s/Ef_stab { }/Ef_stab { alpha 0.2 }/" v_156/EF_stab/test.data > v_156/EF_stab02/test.data