#!/bin/sh


list="10 20 40 80"
cas="cas cas-rk3"

stdfacsecs="1 0.1 0.01 0.001"

facsecs="$stdfacsecs"
sed "s/%list%/$list/; s/%cas%/$cas/;s/%extfacsecs%/$facsecs/;s/%facsecs%/$stdfacsecs/" conv.prm.P.m  > conv.prm.P
ROOT=$TRUST_ROOT
[ "$ROOT" = "" ] && ROOT=$TRIO_U_ROOT
python $ROOT/bin/KSH/preprocessor.py  conv.prm.P conv.prm

echo > ll
for K in ${cas}
do
for resol in $list
  do
  nn=`echo $resol+1|bc `
  for facsec in $facsecs
    do
    mkdir -p  ${K}${resol}_${facsec}
    sed "s/11 11/$nn $nn/;s/facsec 1/facsec $facsec/" base.data >  ${K}${resol}_${facsec}/cas.data
    [ "$K" = "cas-rk3" ] && sed "s/11 11/$nn $nn/;s/facsec 1/facsec $facsec/;s/schema_euler_explicite/Runge_Kutta_ordre_3_qc/;" base.data >  ${K}${resol}_${facsec}/cas.data
   sed "s/RESOL/${resol}/;s/FACSEC/$facsec/;s/CAS/$K/" post_run >   ${K}${resol}_${facsec}/post_run
   echo ${K}${resol}_${facsec}/cas.data >> ll
  done
done
done
grep -v 10_0.1 ll > liste_cas_exclu_nr
 
