#!/bin/bash
# ce script est execute avant de lire les cas tests

for dir in "CONVECTION" "DIFFUSION" "SCHEMA_TEMPS"
do
    mkdir -p $dir
    # cp post_run $dir
    # Genearation du cas test correspondant a $dir
    echo "JDD pour calcul de base " $dir
    sed -e "s/temperature_convergence/${dir}/g" temperature_convergence.data > $dir/${dir}.data
    cd $dir
    if [ ${dir} = "CONVECTION" ] ; then
        cp ../convection.sh CONVECTION.sh
        cp ../post_run .
        sed -i -e "s/conv_temp.*/# convection_temperature_negligible #/g" \
            -e "s/disable_convection_qdm//g" \
            -e "s/# CONV//g" \
            -e "s/CONV #//g" $dir.data
    fi
    if [ $dir = "DIFFUSION" ] ; then
        sed -e "s/basic_temperature/${dir}/g" \
            -e "s/BASIC_TEMPERATURE/${dir}/g" ../diffusion.sh >DIFFUSION.sh
        cp ../post_run .
        sed -i -e "s/diff_temp.*/# diff_temp_negligible #/g" \
            -e "s/timestep .*/timestep 9e-8/"\
            -e "s/DIFF #//g"\
            -e "s/# DIFF//g" $dir.data
    fi
    if [ $dir = "SCHEMA_TEMPS" ] ; then
        cp ../schema_temps.sh .
        sed -i -e "s/TEMPS #//g" \
            -e "s/# TEMPS//g" $dir.data
    fi
    cd ..
done



