#!/bin/bash

#Creation des repertoires
mkdir -p ./VDF/Quick
mkdir -p ./VDF/Centre
#
mkdir -p ./VEF/EF_stab
mkdir -p ./VEF/EF_stab02
mkdir -p ./VEF/Muscl

#############
RACINE=`pwd`

echo $RACINE

#cas de base : VDF/Quick
cd $RACINE/VDF/Quick
cp $RACINE/test_osc_flow.data test.data
cp $RACINE/post_run .
# VDF/Centre
cd $RACINE/VDF/Centre
cp $RACINE/test_osc_flow.data test.data
sed "s/convection { quick }/convection { centre }/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
#

################
################ VEF
################
# VEF/EF_stab
cd $RACINE/VEF/EF_stab
cp $RACINE/test_osc_flow.data test.data
sed "s/101 26/71 19/" test.data > modifie.data
mv modifie.data test.data
sed "s/# AA #/Trianguler_H dom/" test.data > modifie.data
mv modifie.data test.data
sed "s/VDF/VEFPreP1B/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { quick }/convection { EF_stab { } }/" test.data > modifie.data
mv modifie.data test.data
sed "s/paroi_echange_externe_impose T_ext/paroi_temperature_imposee/" test.data > modifie.data
mv modifie.data test.data
sed "s/H_imp Champ_Front_Uniforme 1  1.e11//" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
# VEF/EF_stab02
cd $RACINE/VEF/EF_stab02
cp $RACINE/test_osc_flow.data test.data
sed "s/101 26/71 19/" test.data > modifie.data
mv modifie.data test.data
sed "s/# AA #/Trianguler_H dom/" test.data > modifie.data
mv modifie.data test.data
sed "s/VDF/VEFPreP1B/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { quick }/convection { EF_stab { alpha 0.2 } }/" test.data > modifie.data
mv modifie.data test.data
sed "s/paroi_echange_externe_impose T_ext/paroi_temperature_imposee/" test.data > modifie.data
mv modifie.data test.data
sed "s/H_imp Champ_Front_Uniforme 1  1.e11//" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
# VEF/Muscl
cd $RACINE/VEF/Muscl
cp $RACINE/test_osc_flow.data test.data
sed "s/101 26/71 19/" test.data > modifie.data
mv modifie.data test.data
sed "s/# AA #/Trianguler_H dom/" test.data > modifie.data
mv modifie.data test.data
sed "s/VDF/VEFPreP1B/" test.data > modifie.data
mv modifie.data test.data
sed "s/convection { quick }/convection { Muscl }/" test.data > modifie.data
mv modifie.data test.data
sed "s/paroi_echange_externe_impose T_ext/paroi_temperature_imposee/" test.data > modifie.data
mv modifie.data test.data
sed "s/H_imp Champ_Front_Uniforme 1  1.e11//" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .



















