#!/bin/bash


##################################################################################
# mode d'emploi : use_vs_extract_all_volume chemin_to_lata nom_grandeur chemin_curve
##################################################################################
# Chemin vers le lata a ouvrir
database=$1

# Nom de la grandeur, telle qu'elle est dans le lata
nom_grandeur=$2

# Chemin ou enregistrer le fichier curve
chemin=$3

sed -i "/OpenDatabase/c\OpenDatabase(\"$1\")" /volatile/RANDOM_TRIPERIO/SOME_PYTHON/vs_extract_all_volume.py
sed -i "/AddPlot/c\AddPlot(\"Spreadsheet\", \"$2\", 1, 1)" /volatile/RANDOM_TRIPERIO/SOME_PYTHON/vs_extract_all_volume.py
sed -i "/ExportDBAtts.dirname/c\ExportDBAtts.dirname = \"$3\"" /volatile/RANDOM_TRIPERIO/SOME_PYTHON/vs_extract_all_volume.py
sed -i "/ExportDBAtts.filename/c\ExportDBAtts.filename = \"$2\"" /volatile/RANDOM_TRIPERIO/SOME_PYTHON/vs_extract_all_volume.py
sed -i "/ExportDBAtts.variables/c\ExportDBAtts.variables = (\"$2\")" /volatile/RANDOM_TRIPERIO/SOME_PYTHON/vs_extract_all_volume.py


visit -cli -nowin -s /volatile/RANDOM_TRIPERIO/SOME_PYTHON/vs_extract_all_volume.py
