#!/bin/bash
# Ce script est execute avant de lancer les cas tests
[ -f $1.lml ] && gzip -f $1.lml

if [ $1 = "CANAL_repr_par8" ] 
then
	out=compare_lata.out
	source $TRUST_ROOT/Validation/Outils/Genere_courbe/scripts/scripts_validation.sh
	echo -n "Initial " > $out 
	compare_lata CANAL_seq.lata CANAL_par8.lata && echo "ok" >> $out || echo "ko" >> $out 
	echo -n "Reprise " >> $out 
	compare_lata CANAL_repr.lata CANAL_repr_par8.lata && echo "ok" >> $out || echo "ko" >> $out
fi
