#!/bin/bash

#Creation des repertoires
for dom in pois2D_N0 pois2D_N1 pois2D_N2 pois2D_N3 pois2D_N4 pois2D_N5  ; do
	for etude in EF_stab EF_stab02 Amont ; do
		mkdir -p ./$dom/$etude
	done;
done;

RACINE=`pwd`

echo $RACINE

#cas de base : maillage N0 /Amont 
#-----------------
cd $RACINE/pois2D_N0/Amont
cp $RACINE/test_amont.data .
mv test_amont.data test.data

#maillage N0 (suite)
#------------------
#	EF_stab alpha = 1
cd $RACINE/pois2D_N0/EF_stab
cp $RACINE/test_amont.data .
sed "s/amont/EF_stab { }/" test_amont.data > modifie.data
mv modifie.data test.data
#
#	EF_stab alpha=0.2
#
cd $RACINE/pois2D_N0/EF_stab02
cp $RACINE/test_amont.data .
sed "s/amont/EF_stab { alpha 0.2 }/" test_amont.data > modifie.data
mv modifie.data test.data

#maillage N1
#-----------
#      Amont
cd $RACINE/pois2D_N1/Amont
cp $RACINE/test_amont.data .
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 7 3/" test_amont.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.5 0. 0.5 2/" test.data > modifie.data
mv modifie.data test.data
#
#      EF_stab alpha=1
#
cd $RACINE/pois2D_N1/EF_stab
cp $RACINE/test_amont.data .
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 7 3/" test_amont.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.5 0. 0.5 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { }/" test.data > modifie.data
mv modifie.data test.data
#
#      EF_stab alpha=0.2
#
cd $RACINE/pois2D_N1/EF_stab02
cp $RACINE/test_amont.data .
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 7 3/" test_amont.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.5 0. 0.5 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { alpha 0.2 }/" test.data > modifie.data
mv modifie.data test.data

###
#maillage N2
#-----------
#      Amont
cd $RACINE/pois2D_N2/Amont
cp $RACINE/test_amont.data .
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 13 5/" test_amont.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.25 0. 0.25 2/" test.data > modifie.data
mv modifie.data test.data
#
#      EF_stab alpha=1
#
cd $RACINE/pois2D_N2/EF_stab
cp $RACINE/test_amont.data .
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 13 5/" test_amont.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.25 0. 0.25 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { }/" test.data > modifie.data
mv modifie.data test.data
#
#      EF_stab alpha=0.2
#
cd $RACINE/pois2D_N2/EF_stab02
cp $RACINE/test_amont.data .
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 13 5/" test_amont.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.25 0. 0.25 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { alpha 0.2 }/" test.data > modifie.data
mv modifie.data test.data

###
#maillage N3
#-----------
#      Amont
cd $RACINE/pois2D_N3/Amont
cp $RACINE/test_amont.data .
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 25 9/" test_amont.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.125 0. 0.125 2/" test.data > modifie.data
mv modifie.data test.data
#
#      EF_stab alpha=1
#
cd $RACINE/pois2D_N3/EF_stab
cp $RACINE/test_amont.data .
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 25 9/" test_amont.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.125 0. 0.125 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { }/" test.data > modifie.data
mv modifie.data test.data
#
#      EF_stab alpha=0.2
#
cd $RACINE/pois2D_N3/EF_stab02
cp $RACINE/test_amont.data .
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 25 9/" test_amont.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.125 0. 0.125 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { alpha 0.2 }/" test.data > modifie.data
mv modifie.data test.data

###
#maillage N4
#-----------
#      Amont
cd $RACINE/pois2D_N4/Amont
cp $RACINE/test_amont.data .
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 49 17/" test_amont.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.0625 0. 0.0625 2/" test.data > modifie.data
mv modifie.data test.data
#
#      EF_stab alpha=1
#
cd $RACINE/pois2D_N4/EF_stab
cp $RACINE/test_amont.data .
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 49 17/" test_amont.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.0625 0. 0.0625 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { }/" test.data > modifie.data
mv modifie.data test.data
#
#      EF_stab alpha=0.2
#
cd $RACINE/pois2D_N4/EF_stab02
cp $RACINE/test_amont.data .
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 49 17/" test_amont.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.0625 0. 0.0625 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { alpha 0.2 }/" test.data > modifie.data
mv modifie.data test.data

###
#maillage N5
#-----------
#      Amont
cd $RACINE/pois2D_N5/Amont
cp $RACINE/test_amont.data .
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 97 33/" test_amont.data > modifie.data
mv modifie.data test.data
#
#      EF_stab alpha=1
#
cd $RACINE/pois2D_N5/EF_stab
cp $RACINE/test_amont.data .
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 97 33/" test_amont.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { }/" test.data > modifie.data
mv modifie.data test.data
#
#      EF_stab alpha=0.2
#
cd $RACINE/pois2D_N5/EF_stab02
cp $RACINE/test_amont.data .
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 97 33/" test_amont.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { alpha 0.2 }/" test.data > modifie.data
mv modifie.data test.data



