#!/bin/bash

[ ! -f Couche_Limite_Atmospherique_2couches.msh ] && gunzip Couche_Limite_Atmospherique_2couches.msh.gz
mkdir -p Sol_lisse Sol_rugueux_Erugu Sol_rugueux_Erugu+sigma

cd Sol_lisse
cp ../Couche_Limite_Atmospherique.data Sol_lisse.data
cp ../post_run .

cd ../Sol_rugueux_Erugu
sed "s/SOL	Paroi_fixe/SOL	Paroi_Rugueuse { Erugu 0.00016811635902202942 }/" ../Couche_Limite_Atmospherique.data > Sol_rugueux_Erugu.data
cp ../post_run .

cd ../Sol_rugueux_Erugu+sigma
sed "s/Prandtl_Eps 1.3/Prandtl_Eps 1.196/" ../Sol_rugueux_Erugu/Sol_rugueux_Erugu.data > Sol_rugueux_Erugu+sigma.data
cp ../post_run .

cd ../
