*************************************************************************************************
Statistiques de post resolution
Block divided into 2 parts:
Part 1: for each function, gives the percentage consumed by communications
Part 2: for each type of communication, gives the percentage of time spent in each function
        Note that some counters are nested within each other, 
        that's why the sum of the percentages does not necessarily add up to 100% in this part.
*************************************************************************************************


-----------------------------------------------------------------
DoubleVect/IntVect::echange_espace_virtuel
-----------------------------------------------------------------
Temps total : 0.036543s
	dont Preparer calcul : 0.036543s (100%) 
	dont Resoudre (timestep loop) : 0.033809s (93%) 
	dont SolveurSys::resoudre_systeme : 0.000457s (1%) 
	dont qc diffusion vitesse : 0.001127s (3%) 
	dont qc resoudre systeme : 0.025599s (70%) 
	dont projection: multigrille : 0.02166s (59%) 
	dont multigrille : residu jacobi : 0.019502s (53%) 
	dont multigrille : residu jacobi : 0.00058s (2%) 


-----------------------------------------------------------------
                    Famille MPI_allreduce                         
-----------------------------------------------------------------
Temps total : 0s

-----------------------------------------------------------------
                    Famille MPI_sendrecv                           
-----------------------------------------------------------------
Temps total : 0s


*************************************************************************************************
Statistiques de post resolution
Block divided into 2 parts:
Part 1: for each function, gives the percentage consumed by communications
Part 2: for each type of communication, gives the percentage of time spent in each function
        Note that some counters are nested within each other, 
        that's why the sum of the percentages does not necessarily add up to 100% in this part.
*************************************************************************************************


-----------------------------------------------------------------
DoubleVect/IntVect::echange_espace_virtuel
-----------------------------------------------------------------
Temps total : 0.037116s
	dont Preparer calcul : 0.037116s (100%) 
	dont Resoudre (timestep loop) : 0.03425s (92%) 
	dont SolveurSys::resoudre_systeme : 0.000434s (1%) 
	dont qc diffusion vitesse : 0.001129s (3%) 
	dont qc resoudre systeme : 0.025769s (69%) 
	dont projection: multigrille : 0.021749s (59%) 
	dont multigrille : residu jacobi : 0.019595s (53%) 
	dont multigrille : residu jacobi : 0.000593s (2%) 


-----------------------------------------------------------------
                    Famille MPI_allreduce                         
-----------------------------------------------------------------
Temps total : 0s

-----------------------------------------------------------------
                    Famille MPI_sendrecv                           
-----------------------------------------------------------------
Temps total : 0s


*************************************************************************************************
Statistiques de post resolution
Block divided into 2 parts:
Part 1: for each function, gives the percentage consumed by communications
Part 2: for each type of communication, gives the percentage of time spent in each function
        Note that some counters are nested within each other, 
        that's why the sum of the percentages does not necessarily add up to 100% in this part.
*************************************************************************************************


-----------------------------------------------------------------
DoubleVect/IntVect::echange_espace_virtuel
-----------------------------------------------------------------
Temps total : 0.038172s
	dont Preparer calcul : 0.038172s (100%) 
	dont Resoudre (timestep loop) : 0.034511s (90%) 
	dont SolveurSys::resoudre_systeme : 0.000499s (1%) 
	dont qc diffusion vitesse : 0.001125s (3%) 
	dont qc resoudre systeme : 0.026106s (68%) 
	dont projection: multigrille : 0.021991s (58%) 
	dont multigrille : residu jacobi : 0.019733s (52%) 
	dont multigrille : residu jacobi : 0.000616s (2%) 


-----------------------------------------------------------------
                    Famille MPI_allreduce                         
-----------------------------------------------------------------
Temps total : 0s

-----------------------------------------------------------------
                    Famille MPI_sendrecv                           
-----------------------------------------------------------------
Temps total : 0s


*************************************************************************************************
Statistiques de post resolution
Block divided into 2 parts:
Part 1: for each function, gives the percentage consumed by communications
Part 2: for each type of communication, gives the percentage of time spent in each function
        Note that some counters are nested within each other, 
        that's why the sum of the percentages does not necessarily add up to 100% in this part.
*************************************************************************************************


-----------------------------------------------------------------
DoubleVect/IntVect::echange_espace_virtuel
-----------------------------------------------------------------
Temps total : 0.037964s
	dont Preparer calcul : 0.037964s (100%) 
	dont Resoudre (timestep loop) : 0.035076s (92%) 
	dont SolveurSys::resoudre_systeme : 0.000464s (1%) 
	dont qc diffusion vitesse : 0.001168s (3%) 
	dont qc resoudre systeme : 0.026153s (69%) 
	dont projection: multigrille : 0.021997s (58%) 
	dont multigrille : residu jacobi : 0.01978s (52%) 
	dont multigrille : residu jacobi : 0.000641s (2%) 


-----------------------------------------------------------------
                    Famille MPI_allreduce                         
-----------------------------------------------------------------
Temps total : 0s

-----------------------------------------------------------------
                    Famille MPI_sendrecv                           
-----------------------------------------------------------------
Temps total : 0s


*************************************************************************************************
Statistiques de post resolution
Block divided into 2 parts:
Part 1: for each function, gives the percentage consumed by communications
Part 2: for each type of communication, gives the percentage of time spent in each function
        Note that some counters are nested within each other, 
        that's why the sum of the percentages does not necessarily add up to 100% in this part.
*************************************************************************************************


-----------------------------------------------------------------
DoubleVect/IntVect::echange_espace_virtuel
-----------------------------------------------------------------
Temps total : 0.040672s
	dont Preparer calcul : 0.040672s (100%) 
	dont Resoudre (timestep loop) : 0.037337s (92%) 
	dont SolveurSys::resoudre_systeme : 0.00046s (1%) 
	dont qc diffusion vitesse : 0.001277s (3%) 
	dont qc resoudre systeme : 0.027765s (68%) 
	dont projection: multigrille : 0.023451s (58%) 
	dont multigrille : residu jacobi : 0.021155s (52%) 
	dont multigrille : residu jacobi : 0.000622s (2%) 


-----------------------------------------------------------------
                    Famille MPI_allreduce                         
-----------------------------------------------------------------
Temps total : 0s

-----------------------------------------------------------------
                    Famille MPI_sendrecv                           
-----------------------------------------------------------------
Temps total : 0s


*************************************************************************************************
Statistiques de post resolution
Block divided into 2 parts:
Part 1: for each function, gives the percentage consumed by communications
Part 2: for each type of communication, gives the percentage of time spent in each function
        Note that some counters are nested within each other, 
        that's why the sum of the percentages does not necessarily add up to 100% in this part.
*************************************************************************************************


-----------------------------------------------------------------
DoubleVect/IntVect::echange_espace_virtuel
-----------------------------------------------------------------
Temps total : 0.039324s
	dont Preparer calcul : 0.039324s (100%) 
	dont Resoudre (timestep loop) : 0.036418s (93%) 
	dont SolveurSys::resoudre_systeme : 0.000465s (1%) 
	dont qc diffusion vitesse : 0.001322s (3%) 
	dont qc resoudre systeme : 0.027951s (71%) 
	dont projection: multigrille : 0.023953s (61%) 
	dont multigrille : residu jacobi : 0.021665s (55%) 
	dont multigrille : residu jacobi : 0.000592s (2%) 


-----------------------------------------------------------------
                    Famille MPI_allreduce                         
-----------------------------------------------------------------
Temps total : 0s

-----------------------------------------------------------------
                    Famille MPI_sendrecv                           
-----------------------------------------------------------------
Temps total : 0s


*************************************************************************************************
Statistiques de post resolution
Block divided into 2 parts:
Part 1: for each function, gives the percentage consumed by communications
Part 2: for each type of communication, gives the percentage of time spent in each function
        Note that some counters are nested within each other, 
        that's why the sum of the percentages does not necessarily add up to 100% in this part.
*************************************************************************************************


-----------------------------------------------------------------
DoubleVect/IntVect::echange_espace_virtuel
-----------------------------------------------------------------
Temps total : 0.037842s
	dont Preparer calcul : 0.037842s (100%) 
	dont Resoudre (timestep loop) : 0.034808s (92%) 
	dont SolveurSys::resoudre_systeme : 0.000439s (1%) 
	dont qc diffusion vitesse : 0.001202s (3%) 
	dont qc resoudre systeme : 0.026264s (69%) 
	dont projection: multigrille : 0.022s (58%) 
	dont multigrille : residu jacobi : 0.019808s (52%) 
	dont multigrille : residu jacobi : 0.000687s (2%) 


-----------------------------------------------------------------
                    Famille MPI_allreduce                         
-----------------------------------------------------------------
Temps total : 0s

-----------------------------------------------------------------
                    Famille MPI_sendrecv                           
-----------------------------------------------------------------
Temps total : 0s


*************************************************************************************************
Statistiques de post resolution
Block divided into 2 parts:
Part 1: for each function, gives the percentage consumed by communications
Part 2: for each type of communication, gives the percentage of time spent in each function
        Note that some counters are nested within each other, 
        that's why the sum of the percentages does not necessarily add up to 100% in this part.
*************************************************************************************************


-----------------------------------------------------------------
DoubleVect/IntVect::echange_espace_virtuel
-----------------------------------------------------------------
Temps total : 0.582598s
	dont Preparer calcul : 0.582598s (100%) 
	dont Resoudre (timestep loop) : 0.557943s (96%) 
	dont qc diffusion vitesse : 0.01124s (2%) 
	dont qc resoudre systeme : 0.488515s (84%) 
	dont projection: multigrille : 0.446255s (77%) 
	dont multigrille : residu jacobi : 0.404374s (69%) 
	dont multigrille : residu jacobi : 0.003174s (1%) 


-----------------------------------------------------------------
                    Famille MPI_allreduce                         
-----------------------------------------------------------------
Temps total : 0s

-----------------------------------------------------------------
                    Famille MPI_sendrecv                           
-----------------------------------------------------------------
Temps total : 0s


*************************************************************************************************
Statistiques de post resolution
Block divided into 2 parts:
Part 1: for each function, gives the percentage consumed by communications
Part 2: for each type of communication, gives the percentage of time spent in each function
        Note that some counters are nested within each other, 
        that's why the sum of the percentages does not necessarily add up to 100% in this part.
*************************************************************************************************

Preparer calcul : 0.429434s de communications (soit 4% du temps total consomme par ce compteur)
     	dont MPI_send_recv             2.40e-01 s (55%)
     	dont MPI_send                  4.18e-02 s (10%)
     	dont MPI_recv                  3.93e-03 s ( 1%)
     	dont MPI_broadcast             4.84e-03 s ( 1%)
     	dont MPI_alltoall              1.63e-04 s ( 0%)
     	dont MPI_sumdouble             1.06e-01 s (24%)
     	dont MPI_mindouble             3.24e-03 s ( 0%)
     	dont MPI_maxdouble             1.31e-04 s ( 0%)
     	dont MPI_sumint                1.14e-04 s ( 0%)
     	dont MPI_barrier               2.90e-02 s ( 6%)

Resoudre (timestep loop) : 0.407317s de communications (soit 4% du temps total consomme par ce compteur)
     	dont MPI_send_recv             2.32e-01 s (56%)
     	dont MPI_send                  3.55e-02 s ( 9%)
     	dont MPI_recv                  8.21e-04 s ( 0%)
     	dont MPI_broadcast             7.12e-04 s ( 0%)
     	dont MPI_alltoall              1.27e-04 s ( 0%)
     	dont MPI_sumdouble             1.06e-01 s (25%)
     	dont MPI_mindouble             2.52e-03 s ( 0%)
     	dont MPI_maxdouble             1.22e-04 s ( 0%)
     	dont MPI_sumint                1.02e-04 s ( 0%)
     	dont MPI_barrier               2.92e-02 s ( 7%)

SolveurSys::resoudre_systeme : 0.0364514s de communications (soit 7% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.85e-02 s (50%)
     	dont MPI_sumdouble             1.79e-02 s (49%)
     	dont MPI_sumint                4.56e-05 s ( 0%)

Pb_base::postraiter : 0.0209667s de communications (soit 22% du temps total consomme par ce compteur)
     	dont MPI_send                  6.93e-03 s (29%)
     	dont MPI_recv                  1.76e-04 s ( 9%)
     	dont MPI_sumdouble             1.73e-04 s ( 2%)
     	dont MPI_mindouble             7.97e-04 s ( 4%)
     	dont MPI_maxdouble             8.38e-06 s ( 0%)
     	dont MPI_barrier               1.29e-02 s (54%)

update statistiques : 0.000978s de communications (soit 1% du temps total consomme par ce compteur)
     	dont MPI_sumdouble             1.73e-04 s (38%)
     	dont MPI_mindouble             7.97e-04 s (59%)
     	dont MPI_maxdouble             8.38e-06 s ( 1%)

calcul terme acceleration : 0.000695875s de communications (soit 12% du temps total consomme par ce compteur)
     	dont MPI_broadcast             2.61e-04 s (34%)
     	dont MPI_sumdouble             2.02e-05 s ( 5%)
     	dont MPI_mindouble             3.92e-04 s (52%)
     	dont MPI_maxdouble             2.21e-05 s ( 6%)

checkpointing : 0.0455025s de communications (soit 79% du temps total consomme par ce compteur)
     	dont MPI_send                  2.86e-02 s (55%)
     	dont MPI_recv                  6.45e-04 s (12%)
     	dont MPI_barrier               1.63e-02 s (31%)

qc calcul pthermo,t,rho_v,etc : 0.00031725s de communications (soit 1% du temps total consomme par ce compteur)
     	dont MPI_sumdouble             1.94e-04 s (60%)
     	dont MPI_mindouble             6.28e-05 s (20%)
     	dont MPI_maxdouble             6.04e-05 s (19%)

qc diffusion vitesse : 0.00118362s de communications (soit 0% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.18e-03 s (100%)

qc resoudre systeme : 0.304854s de communications (soit 4% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.99e-01 s (66%)
     	dont MPI_alltoall              1.27e-04 s ( 0%)
     	dont MPI_sumdouble             1.06e-01 s (33%)
     	dont MPI_sumint                1.02e-04 s ( 0%)

projection: multigrille : 0.296854s de communications (soit 4% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.92e-01 s (65%)
     	dont MPI_alltoall              4.99e-05 s ( 0%)
     	dont MPI_sumdouble             1.05e-01 s (34%)
     	dont MPI_sumint                6.74e-05 s ( 0%)

multigrille : residu jacobi : 0.166672s de communications (soit 2% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.67e-01 s (100%)

multigrille : residu jacobi : 0.0003045s de communications (soit 1% du temps total consomme par ce compteur)
     	dont MPI_send_recv             3.04e-04 s (100%)


-----------------------------------------------------------------
DoubleVect/IntVect::echange_espace_virtuel
-----------------------------------------------------------------
Temps total : 0.433187s
	dont Preparer calcul : 0.433187s (100%) 
	dont Resoudre (timestep loop) : 0.417593s (96%) 
	dont qc diffusion vitesse : 0.00382712s (1%) 
	dont qc resoudre systeme : 0.365107s (84%) 
	dont projection: multigrille : 0.344325s (79%) 
	dont multigrille : residu jacobi : 0.321774s (74%) 

-----------------------------------------------------------------
MPI_send_recv
-----------------------------------------------------------------
Temps total : 0.23985s
	dont Preparer calcul : 0.23985s (100%) 
	dont Resoudre (timestep loop) : 0.232097s (96%) 
	dont SolveurSys::resoudre_systeme : 0.0185056s (8%) 
	dont qc resoudre systeme : 0.198883s (84%) 
	dont projection: multigrille : 0.192018s (81%) 
	dont multigrille : residu jacobi : 0.166672s (69%) 

-----------------------------------------------------------------
MPI_send
-----------------------------------------------------------------
Temps total : 0.0487042s
	dont Preparer calcul : 0.041773s (88%) 
	dont Resoudre (timestep loop) : 0.035493s (65%) 
	dont Pb_base::postraiter : 0.00693125s (11%) 
	dont checkpointing : 0.0285618s (53%) 

-----------------------------------------------------------------
MPI_recv
-----------------------------------------------------------------
Temps total : 0.00410687s
	dont Preparer calcul : 0.00393075s (98%) 
	dont Resoudre (timestep loop) : 0.000820875s (5%) 
	dont Pb_base::postraiter : 0.000176125s (1%) 
	dont checkpointing : 0.00064475s (4%) 

-----------------------------------------------------------------
MPI_broadcast
-----------------------------------------------------------------
Temps total : 0.0117337s
	dont Preparer calcul : 0.00483737s (47%) 
	dont Resoudre (timestep loop) : 0.000711625s (5%) 
	dont calcul terme acceleration : 0.000261s (1%) 

-----------------------------------------------------------------
MPI_alltoall
-----------------------------------------------------------------
Temps total : 0.000163s
	dont Preparer calcul : 0.000163s (100%) 
	dont Resoudre (timestep loop) : 0.000127125s (77%) 
	dont qc resoudre systeme : 0.000127125s (77%) 
	dont projection: multigrille : 4.9875e-05s (31%) 

-----------------------------------------------------------------
MPI_sumdouble
-----------------------------------------------------------------
Temps total : 0.106373s
	dont Preparer calcul : 0.106366s (100%) 
	dont Resoudre (timestep loop) : 0.106149s (99%) 
	dont SolveurSys::resoudre_systeme : 0.0179001s (20%) 
	dont qc resoudre systeme : 0.105742s (99%) 
	dont projection: multigrille : 0.10472s (98%) 

-----------------------------------------------------------------
MPI_mindouble
-----------------------------------------------------------------
Temps total : 0.00323513s
	dont Preparer calcul : 0.00323513s (100%) 
	dont Resoudre (timestep loop) : 0.00251637s (84%) 
	dont Pb_base::postraiter : 0.000796625s (17%) 
	dont update statistiques : 0.000796625s (17%) 
	dont calcul terme acceleration : 0.0003925s (18%) 
	dont qc calcul pthermo,t,rho_v,etc : 6.275e-05s (3%) 

-----------------------------------------------------------------
MPI_maxdouble
-----------------------------------------------------------------
Temps total : 0.000178625s
	dont Preparer calcul : 0.000131125s (73%) 
	dont Resoudre (timestep loop) : 0.0001225s (69%) 
	dont Pb_base::postraiter : 8.375e-06s (4%) 
	dont update statistiques : 8.375e-06s (4%) 
	dont calcul terme acceleration : 2.2125e-05s (12%) 
	dont qc calcul pthermo,t,rho_v,etc : 6.0375e-05s (34%) 

-----------------------------------------------------------------
MPI_sumint
-----------------------------------------------------------------
Temps total : 0.000114375s
	dont Preparer calcul : 0.000114375s (100%) 
	dont Resoudre (timestep loop) : 0.00010175s (89%) 
	dont SolveurSys::resoudre_systeme : 4.5625e-05s (40%) 
	dont qc resoudre systeme : 0.00010175s (89%) 
	dont projection: multigrille : 6.7375e-05s (59%) 

-----------------------------------------------------------------
MPI_barrier
-----------------------------------------------------------------
Temps total : 0.0419143s
	dont Preparer calcul : 0.0290329s (68%) 
	dont Resoudre (timestep loop) : 0.0291774s (70%) 
	dont Pb_base::postraiter : 0.0128814s (31%) 
	dont checkpointing : 0.016296s (39%) 


-----------------------------------------------------------------
                    Famille MPI_allreduce                         
-----------------------------------------------------------------
Temps total : 0.151815s
	dont Preparer calcul : 0.13888s (91%) 
	dont Resoudre (timestep loop) : 0.138067s (90%) 
	dont SolveurSys::resoudre_systeme : 0.0179458s (13%) 
	dont Pb_base::postraiter : 0.0138594s (9%) 
	dont checkpointing : 0.016296s (11%) 
	dont qc resoudre systeme : 0.105844s (69%) 
	dont projection: multigrille : 0.104787s (68%) 

-----------------------------------------------------------------
                    Famille MPI_sendrecv                           
-----------------------------------------------------------------
Temps total : 0.304558s
	dont Preparer calcul : 0.290554s (95%) 
	dont Resoudre (timestep loop) : 0.26925s (87%) 
	dont SolveurSys::resoudre_systeme : 0.0185056s (6%) 
	dont Pb_base::postraiter : 0.00710737s (2%) 
	dont checkpointing : 0.0292065s (10%) 
	dont qc resoudre systeme : 0.19901s (65%) 
	dont projection: multigrille : 0.192067s (62%) 
	dont multigrille : residu jacobi : 0.166672s (54%) 


*************************************************************************************************
Statistiques de post resolution
Block divided into 2 parts:
Part 1: for each function, gives the percentage consumed by communications
Part 2: for each type of communication, gives the percentage of time spent in each function
        Note that some counters are nested within each other, 
        that's why the sum of the percentages does not necessarily add up to 100% in this part.
*************************************************************************************************

Preparer calcul : 0.309001s de communications (soit 4% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.58e-01 s (51%)
     	dont MPI_send                  4.24e-02 s (14%)
     	dont MPI_recv                  2.32e-03 s ( 0%)
     	dont MPI_broadcast             8.26e-03 s ( 2%)
     	dont MPI_alltoall              1.61e-04 s ( 0%)
     	dont MPI_sumdouble             6.08e-02 s (19%)
     	dont MPI_mindouble             1.66e-03 s ( 0%)
     	dont MPI_maxdouble             1.53e-04 s ( 0%)
     	dont MPI_sumint                1.46e-04 s ( 0%)
     	dont MPI_barrier               3.47e-02 s (11%)

Resoudre (timestep loop) : 0.277911s de communications (soit 4% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.43e-01 s (51%)
     	dont MPI_send                  3.60e-02 s (13%)
     	dont MPI_recv                  5.56e-04 s ( 0%)
     	dont MPI_broadcast             9.28e-04 s ( 0%)
     	dont MPI_alltoall              1.24e-04 s ( 0%)
     	dont MPI_sumdouble             6.04e-02 s (21%)
     	dont MPI_mindouble             1.53e-03 s ( 0%)
     	dont MPI_maxdouble             1.42e-04 s ( 0%)
     	dont MPI_sumint                1.26e-04 s ( 0%)
     	dont MPI_barrier               3.48e-02 s (12%)

SolveurSys::resoudre_systeme : 0.0483644s de communications (soit 10% du temps total consomme par ce compteur)
     	dont MPI_send_recv             2.10e-02 s (43%)
     	dont MPI_sumdouble             2.73e-02 s (56%)
     	dont MPI_sumint                6.08e-05 s ( 0%)

Pb_base::postraiter : 0.0228633s de communications (soit 32% du temps total consomme par ce compteur)
     	dont MPI_send                  7.44e-03 s (30%)
     	dont MPI_recv                  1.52e-04 s ( 5%)
     	dont MPI_sumdouble             2.46e-04 s ( 1%)
     	dont MPI_mindouble             3.25e-04 s ( 3%)
     	dont MPI_maxdouble             8.50e-06 s ( 0%)
     	dont MPI_barrier               1.47e-02 s (59%)

update statistiques : 0.000578833s de communications (soit 1% du temps total consomme par ce compteur)
     	dont MPI_sumdouble             2.46e-04 s (52%)
     	dont MPI_mindouble             3.25e-04 s (45%)
     	dont MPI_maxdouble             8.50e-06 s ( 1%)

calcul terme acceleration : 0.00118742s de communications (soit 25% du temps total consomme par ce compteur)
     	dont MPI_broadcast             4.78e-04 s (37%)
     	dont MPI_sumdouble             2.48e-05 s ( 4%)
     	dont MPI_mindouble             6.60e-04 s (54%)
     	dont MPI_maxdouble             2.48e-05 s ( 4%)

checkpointing : 0.0490322s de communications (soit 86% du temps total consomme par ce compteur)
     	dont MPI_send                  2.86e-02 s (53%)
     	dont MPI_recv                  4.04e-04 s ( 8%)
     	dont MPI_barrier               2.01e-02 s (38%)

qc calcul pthermo,t,rho_v,etc : 0.000330917s de communications (soit 2% du temps total consomme par ce compteur)
     	dont MPI_sumdouble             1.96e-04 s (58%)
     	dont MPI_mindouble             6.71e-05 s (20%)
     	dont MPI_maxdouble             6.82e-05 s (20%)

qc diffusion vitesse : 0.000831833s de communications (soit 0% du temps total consomme par ce compteur)
     	dont MPI_send_recv             8.32e-04 s (100%)

qc resoudre systeme : 0.17855s de communications (soit 3% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.18e-01 s (66%)
     	dont MPI_alltoall              1.24e-04 s ( 0%)
     	dont MPI_sumdouble             5.99e-02 s (33%)
     	dont MPI_sumint                1.26e-04 s ( 0%)

projection: multigrille : 0.172385s de communications (soit 3% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.14e-01 s (66%)
     	dont MPI_alltoall              5.24e-05 s ( 0%)
     	dont MPI_sumdouble             5.84e-02 s (33%)
     	dont MPI_sumint                8.33e-05 s ( 0%)

multigrille : residu jacobi : 0.0877507s de communications (soit 2% du temps total consomme par ce compteur)
     	dont MPI_send_recv             8.78e-02 s (100%)

multigrille : residu jacobi : 0.000188417s de communications (soit 1% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.88e-04 s (100%)


-----------------------------------------------------------------
DoubleVect/IntVect::echange_espace_virtuel
-----------------------------------------------------------------
Temps total : 0.308735s
	dont Preparer calcul : 0.308735s (100%) 
	dont Resoudre (timestep loop) : 0.287457s (93%) 
	dont qc diffusion vitesse : 0.00290733s (1%) 
	dont qc resoudre systeme : 0.24757s (80%) 
	dont projection: multigrille : 0.231662s (75%) 
	dont multigrille : residu jacobi : 0.213853s (69%) 

-----------------------------------------------------------------
MPI_send_recv
-----------------------------------------------------------------
Temps total : 0.15843s
	dont Preparer calcul : 0.15843s (100%) 
	dont Resoudre (timestep loop) : 0.143344s (90%) 
	dont SolveurSys::resoudre_systeme : 0.0209778s (13%) 
	dont qc resoudre systeme : 0.11839s (74%) 
	dont projection: multigrille : 0.1138s (71%) 
	dont multigrille : residu jacobi : 0.0877507s (55%) 

-----------------------------------------------------------------
MPI_send
-----------------------------------------------------------------
Temps total : 0.0498016s
	dont Preparer calcul : 0.0423632s (87%) 
	dont Resoudre (timestep loop) : 0.0359953s (67%) 
	dont Pb_base::postraiter : 0.00743842s (13%) 
	dont checkpointing : 0.0285569s (54%) 

-----------------------------------------------------------------
MPI_recv
-----------------------------------------------------------------
Temps total : 0.00247575s
	dont Preparer calcul : 0.00232367s (98%) 
	dont Resoudre (timestep loop) : 0.00055575s (3%) 
	dont Pb_base::postraiter : 0.000152083s (1%) 
	dont checkpointing : 0.000403667s (2%) 

-----------------------------------------------------------------
MPI_broadcast
-----------------------------------------------------------------
Temps total : 0.0158173s
	dont Preparer calcul : 0.0082635s (55%) 
	dont Resoudre (timestep loop) : 0.00092825s (5%) 
	dont calcul terme acceleration : 0.000478083s (2%) 

-----------------------------------------------------------------
MPI_alltoall
-----------------------------------------------------------------
Temps total : 0.000161333s
	dont Preparer calcul : 0.000161333s (100%) 
	dont Resoudre (timestep loop) : 0.000123833s (76%) 
	dont qc resoudre systeme : 0.000123833s (76%) 
	dont projection: multigrille : 5.24167e-05s (32%) 

-----------------------------------------------------------------
MPI_sumdouble
-----------------------------------------------------------------
Temps total : 0.0608588s
	dont Preparer calcul : 0.0608497s (100%) 
	dont Resoudre (timestep loop) : 0.060403s (99%) 
	dont SolveurSys::resoudre_systeme : 0.0273258s (47%) 
	dont qc resoudre systeme : 0.059911s (98%) 
	dont projection: multigrille : 0.0584495s (95%) 

-----------------------------------------------------------------
MPI_mindouble
-----------------------------------------------------------------
Temps total : 0.00166033s
	dont Preparer calcul : 0.00166033s (100%) 
	dont Resoudre (timestep loop) : 0.00152692s (91%) 
	dont Pb_base::postraiter : 0.000324667s (16%) 
	dont update statistiques : 0.000324667s (16%) 
	dont calcul terme acceleration : 0.000659667s (43%) 
	dont qc calcul pthermo,t,rho_v,etc : 6.70833e-05s (4%) 

-----------------------------------------------------------------
MPI_maxdouble
-----------------------------------------------------------------
Temps total : 0.00023375s
	dont Preparer calcul : 0.000153s (66%) 
	dont Resoudre (timestep loop) : 0.000142167s (61%) 
	dont Pb_base::postraiter : 8.5e-06s (3%) 
	dont update statistiques : 8.5e-06s (3%) 
	dont calcul terme acceleration : 2.48333e-05s (10%) 
	dont qc calcul pthermo,t,rho_v,etc : 6.825e-05s (29%) 

-----------------------------------------------------------------
MPI_sumint
-----------------------------------------------------------------
Temps total : 0.000146s
	dont Preparer calcul : 0.000146s (100%) 
	dont Resoudre (timestep loop) : 0.000125833s (86%) 
	dont SolveurSys::resoudre_systeme : 6.075e-05s (41%) 
	dont qc resoudre systeme : 0.000125833s (86%) 
	dont projection: multigrille : 8.33333e-05s (57%) 

-----------------------------------------------------------------
MPI_barrier
-----------------------------------------------------------------
Temps total : 0.0493448s
	dont Preparer calcul : 0.0346509s (69%) 
	dont Resoudre (timestep loop) : 0.0347656s (71%) 
	dont Pb_base::postraiter : 0.0146939s (30%) 
	dont checkpointing : 0.0200717s (40%) 


-----------------------------------------------------------------
                    Famille MPI_allreduce                         
-----------------------------------------------------------------
Temps total : 0.112244s
	dont Preparer calcul : 0.09746s (86%) 
	dont Resoudre (timestep loop) : 0.0969635s (86%) 
	dont SolveurSys::resoudre_systeme : 0.0273866s (25%) 
	dont Pb_base::postraiter : 0.0152727s (13%) 
	dont checkpointing : 0.0200717s (17%) 
	dont qc resoudre systeme : 0.0600368s (53%) 
	dont projection: multigrille : 0.0585328s (52%) 

-----------------------------------------------------------------
                    Famille MPI_sendrecv                           
-----------------------------------------------------------------
Temps total : 0.226686s
	dont Preparer calcul : 0.211541s (93%) 
	dont Resoudre (timestep loop) : 0.180947s (79%) 
	dont SolveurSys::resoudre_systeme : 0.0209778s (9%) 
	dont Pb_base::postraiter : 0.0075905s (3%) 
	dont checkpointing : 0.0289606s (12%) 
	dont qc resoudre systeme : 0.118514s (51%) 
	dont projection: multigrille : 0.113852s (49%) 
	dont multigrille : residu jacobi : 0.0877507s (38%) 


*************************************************************************************************
Statistiques de post resolution
Block divided into 2 parts:
Part 1: for each function, gives the percentage consumed by communications
Part 2: for each type of communication, gives the percentage of time spent in each function
        Note that some counters are nested within each other, 
        that's why the sum of the percentages does not necessarily add up to 100% in this part.
*************************************************************************************************

Preparer calcul : 0.272905s de communications (soit 4% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.13e-01 s (42%)
     	dont MPI_send                  4.19e-02 s (15%)
     	dont MPI_recv                  2.75e-03 s ( 1%)
     	dont MPI_broadcast             7.29e-03 s ( 2%)
     	dont MPI_alltoall              4.47e-04 s ( 0%)
     	dont MPI_sumdouble             3.28e-02 s (12%)
     	dont MPI_mindouble             1.63e-03 s ( 0%)
     	dont MPI_maxdouble             1.37e-04 s ( 0%)
     	dont MPI_sumint                1.45e-04 s ( 0%)
     	dont MPI_barrier               7.26e-02 s (25%)

Resoudre (timestep loop) : 0.252513s de communications (soit 3% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.08e-01 s (43%)
     	dont MPI_send                  3.59e-02 s (13%)
     	dont MPI_recv                  5.21e-04 s ( 0%)
     	dont MPI_broadcast             7.72e-04 s ( 0%)
     	dont MPI_alltoall              1.31e-04 s ( 0%)
     	dont MPI_sumdouble             3.22e-02 s (13%)
     	dont MPI_mindouble             1.42e-03 s ( 0%)
     	dont MPI_maxdouble             1.29e-04 s ( 0%)
     	dont MPI_sumint                1.28e-04 s ( 0%)
     	dont MPI_barrier               7.31e-02 s (27%)

SolveurSys::resoudre_systeme : 0.035133s de communications (soit 7% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.63e-02 s (46%)
     	dont MPI_sumdouble             1.87e-02 s (53%)
     	dont MPI_sumint                6.56e-05 s ( 0%)

Pb_base::postraiter : 0.0215017s de communications (soit 31% du temps total consomme par ce compteur)
     	dont MPI_send                  7.35e-03 s (31%)
     	dont MPI_recv                  1.41e-04 s ( 6%)
     	dont MPI_sumdouble             2.45e-04 s ( 1%)
     	dont MPI_mindouble             1.99e-04 s ( 1%)
     	dont MPI_maxdouble             6.67e-06 s ( 0%)
     	dont MPI_barrier               1.36e-02 s (58%)

update statistiques : 0.00045075s de communications (soit 1% du temps total consomme par ce compteur)
     	dont MPI_sumdouble             2.45e-04 s (56%)
     	dont MPI_mindouble             1.99e-04 s (42%)
     	dont MPI_maxdouble             6.67e-06 s ( 1%)

calcul terme acceleration : 0.000732417s de communications (soit 18% du temps total consomme par ce compteur)
     	dont MPI_broadcast             2.75e-04 s (35%)
     	dont MPI_sumdouble             2.66e-05 s ( 5%)
     	dont MPI_mindouble             4.05e-04 s (53%)
     	dont MPI_maxdouble             2.53e-05 s ( 5%)

checkpointing : 0.0884192s de communications (soit 88% du temps total consomme par ce compteur)
     	dont MPI_send                  2.85e-02 s (29%)
     	dont MPI_recv                  3.80e-04 s ( 8%)
     	dont MPI_barrier               5.95e-02 s (62%)

qc calcul pthermo,t,rho_v,etc : 0.000313583s de communications (soit 2% du temps total consomme par ce compteur)
     	dont MPI_sumdouble             1.76e-04 s (56%)
     	dont MPI_mindouble             7.40e-05 s (23%)
     	dont MPI_maxdouble             6.36e-05 s (20%)

qc diffusion vitesse : 0.000831083s de communications (soit 0% du temps total consomme par ce compteur)
     	dont MPI_send_recv             8.31e-04 s (100%)

qc resoudre systeme : 0.117529s de communications (soit 2% du temps total consomme par ce compteur)
     	dont MPI_send_recv             8.55e-02 s (72%)
     	dont MPI_alltoall              1.31e-04 s ( 0%)
     	dont MPI_sumdouble             3.18e-02 s (27%)
     	dont MPI_sumint                1.28e-04 s ( 0%)

projection: multigrille : 0.112831s de communications (soit 2% du temps total consomme par ce compteur)
     	dont MPI_send_recv             8.14e-02 s (72%)
     	dont MPI_alltoall              6.28e-05 s ( 0%)
     	dont MPI_sumdouble             3.13e-02 s (27%)
     	dont MPI_sumint                8.97e-05 s ( 0%)

multigrille : residu jacobi : 0.0601421s de communications (soit 1% du temps total consomme par ce compteur)
     	dont MPI_send_recv             6.01e-02 s (100%)

multigrille : residu jacobi : 0.000237083s de communications (soit 1% du temps total consomme par ce compteur)
     	dont MPI_send_recv             2.37e-04 s (100%)


-----------------------------------------------------------------
DoubleVect/IntVect::echange_espace_virtuel
-----------------------------------------------------------------
Temps total : 0.268645s
	dont Preparer calcul : 0.268645s (100%) 
	dont Resoudre (timestep loop) : 0.257399s (95%) 
	dont qc diffusion vitesse : 0.00292158s (1%) 
	dont qc resoudre systeme : 0.219548s (81%) 
	dont projection: multigrille : 0.204054s (76%) 
	dont multigrille : residu jacobi : 0.186359s (69%) 

-----------------------------------------------------------------
MPI_send_recv
-----------------------------------------------------------------
Temps total : 0.113272s
	dont Preparer calcul : 0.113272s (100%) 
	dont Resoudre (timestep loop) : 0.108215s (95%) 
	dont SolveurSys::resoudre_systeme : 0.0163423s (14%) 
	dont qc diffusion vitesse : 0.000831083s (1%) 
	dont qc resoudre systeme : 0.0854968s (75%) 
	dont projection: multigrille : 0.0813784s (71%) 
	dont multigrille : residu jacobi : 0.0601421s (53%) 

-----------------------------------------------------------------
MPI_send
-----------------------------------------------------------------
Temps total : 0.0492051s
	dont Preparer calcul : 0.0418511s (86%) 
	dont Resoudre (timestep loop) : 0.0358776s (67%) 
	dont Pb_base::postraiter : 0.007354s (13%) 
	dont checkpointing : 0.0285236s (54%) 

-----------------------------------------------------------------
MPI_recv
-----------------------------------------------------------------
Temps total : 0.00288917s
	dont Preparer calcul : 0.00274783s (99%) 
	dont Resoudre (timestep loop) : 0.000521167s (3%) 
	dont Pb_base::postraiter : 0.000141333s (1%) 
	dont checkpointing : 0.000379833s (2%) 

-----------------------------------------------------------------
MPI_broadcast
-----------------------------------------------------------------
Temps total : 0.0142069s
	dont Preparer calcul : 0.007293s (55%) 
	dont Resoudre (timestep loop) : 0.000771667s (5%) 
	dont calcul terme acceleration : 0.000275167s (1%) 

-----------------------------------------------------------------
MPI_alltoall
-----------------------------------------------------------------
Temps total : 0.00044725s
	dont Preparer calcul : 0.00044725s (100%) 
	dont Resoudre (timestep loop) : 0.000131167s (29%) 
	dont qc resoudre systeme : 0.000131167s (29%) 
	dont projection: multigrille : 6.28333e-05s (13%) 

-----------------------------------------------------------------
MPI_sumdouble
-----------------------------------------------------------------
Temps total : 0.0327858s
	dont Preparer calcul : 0.0327778s (100%) 
	dont Resoudre (timestep loop) : 0.0322444s (98%) 
	dont SolveurSys::resoudre_systeme : 0.0187251s (57%) 
	dont Pb_base::postraiter : 0.000245167s (1%) 
	dont update statistiques : 0.000245167s (1%) 
	dont qc resoudre systeme : 0.0317732s (96%) 
	dont projection: multigrille : 0.0313003s (95%) 

-----------------------------------------------------------------
MPI_mindouble
-----------------------------------------------------------------
Temps total : 0.00163375s
	dont Preparer calcul : 0.00163375s (100%) 
	dont Resoudre (timestep loop) : 0.00142475s (86%) 
	dont Pb_base::postraiter : 0.000198917s (12%) 
	dont update statistiques : 0.000198917s (12%) 
	dont calcul terme acceleration : 0.000405333s (25%) 
	dont qc calcul pthermo,t,rho_v,etc : 7.4e-05s (4%) 

-----------------------------------------------------------------
MPI_maxdouble
-----------------------------------------------------------------
Temps total : 0.000200583s
	dont Preparer calcul : 0.000136833s (69%) 
	dont Resoudre (timestep loop) : 0.000128583s (65%) 
	dont Pb_base::postraiter : 6.66667e-06s (3%) 
	dont update statistiques : 6.66667e-06s (3%) 
	dont calcul terme acceleration : 2.53333e-05s (12%) 
	dont qc calcul pthermo,t,rho_v,etc : 6.35833e-05s (32%) 

-----------------------------------------------------------------
MPI_sumint
-----------------------------------------------------------------
Temps total : 0.000144917s
	dont Preparer calcul : 0.000144917s (100%) 
	dont Resoudre (timestep loop) : 0.000127583s (87%) 
	dont SolveurSys::resoudre_systeme : 6.55833e-05s (44%) 
	dont qc resoudre systeme : 0.000127583s (87%) 
	dont projection: multigrille : 8.96667e-05s (61%) 

-----------------------------------------------------------------
MPI_barrier
-----------------------------------------------------------------
Temps total : 0.0861562s
	dont Preparer calcul : 0.0726006s (82%) 
	dont Resoudre (timestep loop) : 0.0730713s (83%) 
	dont Pb_base::postraiter : 0.0135556s (17%) 
	dont checkpointing : 0.0595157s (66%) 


-----------------------------------------------------------------
                    Famille MPI_allreduce                         
-----------------------------------------------------------------
Temps total : 0.120921s
	dont Preparer calcul : 0.107294s (89%) 
	dont Resoudre (timestep loop) : 0.106997s (89%) 
	dont SolveurSys::resoudre_systeme : 0.0187907s (17%) 
	dont Pb_base::postraiter : 0.0140063s (10%) 
	dont checkpointing : 0.0595157s (46%) 
	dont qc resoudre systeme : 0.0319008s (30%) 
	dont projection: multigrille : 0.0313899s (29%) 

-----------------------------------------------------------------
                    Famille MPI_sendrecv                           
-----------------------------------------------------------------
Temps total : 0.18002s
	dont Preparer calcul : 0.165611s (92%) 
	dont Resoudre (timestep loop) : 0.145517s (81%) 
	dont SolveurSys::resoudre_systeme : 0.0163423s (9%) 
	dont Pb_base::postraiter : 0.00749533s (3%) 
	dont checkpointing : 0.0289034s (15%) 
	dont qc resoudre systeme : 0.085628s (48%) 
	dont projection: multigrille : 0.0814413s (45%) 
	dont multigrille : residu jacobi : 0.0601421s (33%) 


*************************************************************************************************
Statistiques de post resolution
Block divided into 2 parts:
Part 1: for each function, gives the percentage consumed by communications
Part 2: for each type of communication, gives the percentage of time spent in each function
        Note that some counters are nested within each other, 
        that's why the sum of the percentages does not necessarily add up to 100% in this part.
*************************************************************************************************

Preparer calcul : 0.336218s de communications (soit 6% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.57e-01 s (46%)
     	dont MPI_send                  4.50e-02 s (13%)
     	dont MPI_recv                  2.63e-03 s ( 1%)
     	dont MPI_broadcast             7.58e-03 s ( 1%)
     	dont MPI_alltoall              1.88e-04 s ( 0%)
     	dont MPI_sumdouble             8.96e-02 s (26%)
     	dont MPI_mindouble             1.14e-03 s ( 0%)
     	dont MPI_maxdouble             1.76e-04 s ( 0%)
     	dont MPI_sumint                1.66e-04 s ( 0%)
     	dont MPI_barrier               3.31e-02 s ( 9%)

Resoudre (timestep loop) : 0.315498s de communications (soit 6% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.53e-01 s (48%)
     	dont MPI_send                  3.82e-02 s (12%)
     	dont MPI_recv                  4.74e-04 s ( 0%)
     	dont MPI_broadcast             7.70e-04 s ( 0%)
     	dont MPI_alltoall              1.46e-04 s ( 0%)
     	dont MPI_sumdouble             8.89e-02 s (28%)
     	dont MPI_mindouble             1.01e-03 s ( 0%)
     	dont MPI_maxdouble             1.64e-04 s ( 0%)
     	dont MPI_sumint                1.47e-04 s ( 0%)
     	dont MPI_barrier               3.29e-02 s (10%)

SolveurSys::resoudre_systeme : 0.0485808s de communications (soit 9% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.97e-02 s (40%)
     	dont MPI_sumdouble             2.88e-02 s (59%)
     	dont MPI_sumint                7.65e-05 s ( 0%)

Pb_base::postraiter : 0.0230048s de communications (soit 42% du temps total consomme par ce compteur)
     	dont MPI_send                  7.87e-03 s (32%)
     	dont MPI_recv                  1.20e-04 s ( 4%)
     	dont MPI_sumdouble             2.85e-04 s ( 1%)
     	dont MPI_mindouble             1.64e-04 s ( 1%)
     	dont MPI_maxdouble             1.06e-05 s ( 0%)
     	dont MPI_barrier               1.46e-02 s (60%)

update statistiques : 0.000459722s de communications (soit 1% du temps total consomme par ce compteur)
     	dont MPI_sumdouble             2.85e-04 s (62%)
     	dont MPI_mindouble             1.64e-04 s (34%)
     	dont MPI_maxdouble             1.06e-05 s ( 2%)

calcul terme acceleration : 0.000832s de communications (soit 27% du temps total consomme par ce compteur)
     	dont MPI_broadcast             2.72e-04 s (31%)
     	dont MPI_sumdouble             2.77e-05 s ( 4%)
     	dont MPI_mindouble             5.04e-04 s (58%)
     	dont MPI_maxdouble             2.82e-05 s ( 4%)

checkpointing : 0.0489934s de communications (soit 90% du temps total consomme par ce compteur)
     	dont MPI_send                  3.03e-02 s (58%)
     	dont MPI_recv                  3.54e-04 s ( 5%)
     	dont MPI_barrier               1.83e-02 s (35%)

qc calcul pthermo,t,rho_v,etc : 0.000358222s de communications (soit 3% du temps total consomme par ce compteur)
     	dont MPI_sumdouble             1.96e-04 s (54%)
     	dont MPI_mindouble             8.29e-05 s (23%)
     	dont MPI_maxdouble             7.92e-05 s (22%)

qc diffusion vitesse : 0.000694111s de communications (soit 0% du temps total consomme par ce compteur)
     	dont MPI_send_recv             6.94e-04 s (100%)

qc resoudre systeme : 0.229024s de communications (soit 5% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.40e-01 s (61%)
     	dont MPI_alltoall              1.46e-04 s ( 0%)
     	dont MPI_sumdouble             8.84e-02 s (38%)
     	dont MPI_sumint                1.47e-04 s ( 0%)

projection: multigrille : 0.225219s de communications (soit 5% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.37e-01 s (61%)
     	dont MPI_alltoall              6.68e-05 s ( 0%)
     	dont MPI_sumdouble             8.80e-02 s (38%)
     	dont MPI_sumint                1.04e-04 s ( 0%)

multigrille : residu jacobi : 0.112604s de communications (soit 3% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.13e-01 s (100%)

multigrille : residu jacobi : 0.0001735s de communications (soit 1% du temps total consomme par ce compteur)
     	dont MPI_send_recv             1.73e-04 s (100%)


-----------------------------------------------------------------
DoubleVect/IntVect::echange_espace_virtuel
-----------------------------------------------------------------
Temps total : 0.271577s
	dont Preparer calcul : 0.271577s (100%) 
	dont Resoudre (timestep loop) : 0.262824s (96%) 
	dont qc diffusion vitesse : 0.00232272s (1%) 
	dont qc resoudre systeme : 0.238881s (87%) 
	dont projection: multigrille : 0.226453s (83%) 
	dont multigrille : residu jacobi : 0.212518s (78%) 

-----------------------------------------------------------------
MPI_send_recv
-----------------------------------------------------------------
Temps total : 0.156729s
	dont Preparer calcul : 0.156729s (100%) 
	dont Resoudre (timestep loop) : 0.152777s (97%) 
	dont SolveurSys::resoudre_systeme : 0.0196776s (12%) 
	dont qc resoudre systeme : 0.140322s (89%) 
	dont projection: multigrille : 0.137006s (87%) 
	dont multigrille : residu jacobi : 0.112604s (71%) 

-----------------------------------------------------------------
MPI_send
-----------------------------------------------------------------
Temps total : 0.0528433s
	dont Preparer calcul : 0.0449686s (86%) 
	dont Resoudre (timestep loop) : 0.0381666s (69%) 
	dont Pb_base::postraiter : 0.00787467s (13%) 
	dont checkpointing : 0.0302919s (56%) 

-----------------------------------------------------------------
MPI_recv
-----------------------------------------------------------------
Temps total : 0.002754s
	dont Preparer calcul : 0.00263367s (99%) 
	dont Resoudre (timestep loop) : 0.000473944s (2%) 
	dont checkpointing : 0.000353611s (1%) 

-----------------------------------------------------------------
MPI_broadcast
-----------------------------------------------------------------
Temps total : 0.0143261s
	dont Preparer calcul : 0.00757661s (55%) 
	dont Resoudre (timestep loop) : 0.000769667s (4%) 
	dont calcul terme acceleration : 0.000272278s (1%) 

-----------------------------------------------------------------
MPI_alltoall
-----------------------------------------------------------------
Temps total : 0.000188056s
	dont Preparer calcul : 0.000188056s (100%) 
	dont Resoudre (timestep loop) : 0.000146056s (77%) 
	dont qc resoudre systeme : 0.000146056s (77%) 
	dont projection: multigrille : 6.67778e-05s (35%) 

-----------------------------------------------------------------
MPI_sumdouble
-----------------------------------------------------------------
Temps total : 0.0895939s
	dont Preparer calcul : 0.0895822s (100%) 
	dont Resoudre (timestep loop) : 0.0889451s (98%) 
	dont SolveurSys::resoudre_systeme : 0.0288267s (33%) 
	dont qc resoudre systeme : 0.0884083s (98%) 
	dont projection: multigrille : 0.088042s (97%) 

-----------------------------------------------------------------
MPI_mindouble
-----------------------------------------------------------------
Temps total : 0.00114228s
	dont Preparer calcul : 0.00114228s (100%) 
	dont Resoudre (timestep loop) : 0.00100989s (88%) 
	dont Pb_base::postraiter : 0.000164167s (14%) 
	dont update statistiques : 0.000164167s (14%) 
	dont calcul terme acceleration : 0.000503778s (44%) 
	dont qc calcul pthermo,t,rho_v,etc : 8.28889e-05s (7%) 

-----------------------------------------------------------------
MPI_maxdouble
-----------------------------------------------------------------
Temps total : 0.000225611s
	dont Preparer calcul : 0.000175889s (78%) 
	dont Resoudre (timestep loop) : 0.000164167s (72%) 
	dont Pb_base::postraiter : 1.06111e-05s (4%) 
	dont update statistiques : 1.06111e-05s (4%) 
	dont calcul terme acceleration : 2.82222e-05s (12%) 
	dont qc calcul pthermo,t,rho_v,etc : 7.91667e-05s (35%) 

-----------------------------------------------------------------
MPI_sumint
-----------------------------------------------------------------
Temps total : 0.000165833s
	dont Preparer calcul : 0.000165833s (100%) 
	dont Resoudre (timestep loop) : 0.000147056s (88%) 
	dont SolveurSys::resoudre_systeme : 7.65e-05s (46%) 
	dont qc resoudre systeme : 0.000147056s (88%) 
	dont projection: multigrille : 0.000104222s (62%) 

-----------------------------------------------------------------
MPI_barrier
-----------------------------------------------------------------
Temps total : 0.0476054s
	dont Preparer calcul : 0.0330554s (68%) 
	dont Resoudre (timestep loop) : 0.0328979s (70%) 
	dont Pb_base::postraiter : 0.0145501s (31%) 
	dont checkpointing : 0.0183479s (39%) 


-----------------------------------------------------------------
                    Famille MPI_allreduce                         
-----------------------------------------------------------------
Temps total : 0.138733s
	dont Preparer calcul : 0.124122s (89%) 
	dont Resoudre (timestep loop) : 0.123164s (89%) 
	dont SolveurSys::resoudre_systeme : 0.0289032s (21%) 
	dont Pb_base::postraiter : 0.0150098s (10%) 
	dont checkpointing : 0.0183479s (13%) 
	dont qc resoudre systeme : 0.0885554s (64%) 
	dont projection: multigrille : 0.0881462s (64%) 

-----------------------------------------------------------------
                    Famille MPI_sendrecv                           
-----------------------------------------------------------------
Temps total : 0.22684s
	dont Preparer calcul : 0.212096s (93%) 
	dont Resoudre (timestep loop) : 0.192334s (85%) 
	dont SolveurSys::resoudre_systeme : 0.0196776s (8%) 
	dont Pb_base::postraiter : 0.007995s (3%) 
	dont checkpointing : 0.0306455s (13%) 
	dont qc resoudre systeme : 0.140469s (62%) 
	dont projection: multigrille : 0.137073s (60%) 
	dont multigrille : residu jacobi : 0.112604s (50%) 


*************************************************************************************************
Statistiques de post resolution
Block divided into 2 parts:
Part 1: for each function, gives the percentage consumed by communications
Part 2: for each type of communication, gives the percentage of time spent in each function
        Note that some counters are nested within each other, 
        that's why the sum of the percentages does not necessarily add up to 100% in this part.
*************************************************************************************************


-----------------------------------------------------------------
DoubleVect/IntVect::echange_espace_virtuel
-----------------------------------------------------------------
Temps total : 0.037769s
	dont Preparer calcul : 0.037769s (100%) 
	dont Resoudre (timestep loop) : 0.034899s (92%) 
	dont SolveurSys::resoudre_systeme : 0.000435s (1%) 
	dont qc diffusion vitesse : 0.001289s (3%) 
	dont qc resoudre systeme : 0.026506s (70%) 
	dont projection: multigrille : 0.022611s (60%) 
	dont multigrille : residu jacobi : 0.020356s (54%) 
	dont multigrille : residu jacobi : 0.000578s (2%) 


-----------------------------------------------------------------
                    Famille MPI_allreduce                         
-----------------------------------------------------------------
Temps total : 0s

-----------------------------------------------------------------
                    Famille MPI_sendrecv                           
-----------------------------------------------------------------
Temps total : 0s


