#!/bin/bash
# Ce script est execute avant de lancer les cas tests
[ -f $1.lml ] && gzip -f $1.lml

# python ./ordre_cvg.py
cas=`echo $1`
# cd ..
# ls | tail
if [ $cas = "CANAL_desactvie" ] 
then
    ./$cas.sh
    # cp $cas.sauv.* CANAL_TEMPERATURE_IMPOSEE_repr.sauv.*
fi

if [ $cas = "pre_run" ]
then
    # cp pre_run.* CANAL/
    cp pre_run.* SWARM/
    cp pre_run.* CHMTVAR/
fi
if [ $cas = "SWARM_seq" ]
then
    cp SWARM_seq.* ../CHMTVAR/
    sed -i "s/type_T_source SWARM/type_T_source variable_change2/" ../CHMTVAR/SWARM_seq.sauv
fi
