#!/bin/bash
# ce script est execute avant de lire les cas tests

cat >deplacements3.txt <<EOF
0.0015823 0.0015798 0.00151354 bulle3.msh
0.0045867 0.0010343 0.00155486 bulle3.msh
0.0055337 0.0029443 0.00255486 bulle3.msh
EOF

./cree_multi_bulles.sh deplacements3.txt init_multi.lata

# Creation d'un JDD de reprise suite au pre_run : 
echo "JDD pour Preparation du calcul en avancant la bulle au bout du domaine..."
sed -e "s/timestep .*/  timestep 0.0001655/g"      \
    -e "s/dt_post .*/   dt_post 10/g"             \
    -e "s/dt_sauvegarde .*/   dt_sauvegarde 10/g" \
    -e "s/nb_pas_dt_max .*/   nb_pas_dt_max 10/g" \
    -e "s/fichier_reprise_interface.*/fichier_reprise_interface init_multi\.lata/g"                    \
    -e "s/# lata_meshname   FTMESH #/lata_meshname   FTMESH/g" \
    -e "/timestep_reprise_vitesse/d"               \
    -e "/fichier_reprise_vitesse/d"                \
    -e "s/champs_a_postraiter 1 TEMPERATURE/champs_a_postraiter 8 INTERFACES INDICATRICE COMPO_CONNEXE COURBURE DISTANCE_AUTRES_INTERFACES REPULSION_FT PRESSURE VELOCITY_FT/g" basic_temperature.data > pre_run.data

for dir in "SWARM" "CHMTVAR"
do
    mkdir -p $dir
    cp post_run $dir
    cp pre_run.data $dir
    # Genearation du cas test correspondant a $dir
    echo "JDD pour calcul de base " $dir
    sed -e "s/basic_temperature/ ${dir}_seq/g"   \
        -e "s/BASIC_TEMPERATURE/ $dir/g" 
            -e "s/champs_a_postraiter .*/champs_a_postraiter 6 TEMPERATURE INTERFACES COMPO_CONNEXE VELOCITY_FT INDICATRICE TEMPERATURE_ADIM_BULLES/g" basic_temperature.data > $dir/${dir}_seq.data

    # sed -e "s/BASIC_TEMPERATURE/$dir/g"          \
    #     -e "s/basic_temperature/${dir}_seq/g" basic_temperature.sh > $dir/${dir}_seq.sh
#    if [ $dir = "SWARM" ]
#    then
#        sed -i "s/# prerio_k #/perio_k/g" ${dir}/${dir}_seq.data
#    fi

    if [ $dir = "CHMTVAR" ]
    then
        sed -e "s/type_T_source SWARM/type_T_source variable_change2/g" \
            -e "s/SWARM/CHMTVAR/g" SWARM/SWARM_seq.data >${dir}/${dir}_seq.data
    fi

    cd $dir
    # Generation des cas tests paralleles
    echo "JDD pour calcul paralleles ..."
    sed -e "s/nproc_i 1/nproc_i 2/g"    \
        -e "s/nproc_j 1/nproc_j 2/g"    \
        -e "s/nproc_k 1/nproc_k 2/g"    \
        -e "s/seq/par8/g" ${dir}_seq.data >${dir}_par8.data

    # Generation du cas avec reprise
    if [ $dir = "SWARM" ]
    then
    echo "JDD pour calcul avec reprise ..."
    sed -e "s/ # reprise #/ nom_sauvegarde reprise\.sauv/g" \
        -e "s/ # REPRISE #/ nom_reprise ${dir}_seq\.sauv/g" \
        -e "s/ # reprise_T #/  fichier_reprise_temperature ${dir}_seq\.sauv\.lata\n timestep_reprise_temperature 1/g"   \
        -e "s/pre_run/${dir}_seq/g"    \
        -e "s/ expression_vx_init.*/  # expression_vx_init 0.0/g" \
        -e "s/ expression_vz_init.*/ expression_vz_init 0.0 #/g"  ${dir}_seq.data > ${dir}_repr_.data

        n=`grep -n thermique ${dir}_repr_.data | awk -F":" '{print $1}'`
        head -n$n  ${dir}_repr_.data > ${dir}_repr.data
        rm ${dir}_repr_.data
        sed -i "s/thermique/}\nFin/g" ${dir}_repr.data 

        sed -e "s/nproc_i 1/nproc_i 2/g"        \
            -e "s/nproc_j 1/nproc_j 2/g"        \
            -e "s/nproc_k 1/nproc_k 2/g"        \
            -e "s/_seq/_par8/g" ${dir}_repr.data >${dir}_repr_par8.data

    fi
    cd ..
done



