#!/bin/bash

if [ ! -d FTD_remaillage_vef ]
then
  # copie_cas_test FTD_remaillage_vef
  cp -R ${project_directory}/tests/Reference/Multiphase/Front_tracking_discontinu/Front_tracking_discontinu/FTD_remaillage_vef ./
fi

if [ ! -d FTD_remaillage_vdf ]
then
  # copie_cas_test FTD_remaillage_vdf
  cp -R ${project_directory}/tests/Reference/Multiphase/Front_tracking_discontinu/Front_tracking_discontinu/FTD_remaillage_vdf ./
fi

cp -f pre_run_vef FTD_remaillage_vef/pre_run
(cd FTD_remaillage_vef;./pre_run)

cp -f pre_run_vdf FTD_remaillage_vdf/pre_run
(cd FTD_remaillage_vdf;./pre_run)
