#!/bin/bash

#Creation des repertoires
for dom in N0 N1 N2 N3 N4 N5  ; do
	for etude in EF_stab EF_stab02 Amont Muscl ; do
		mkdir -p ./$dom/$etude
	done;
done;

RACINE=`pwd`

echo $RACINE

#cas de base : maillage N0 /Amont 
#-----------------
cd $RACINE/N0/Amont
cp $RACINE/test_amont.data test.data
cp $RACINE/post_run .

#maillage N0 (suite)
#------------------
#	EF_stab alpha = 1
cd $RACINE/N0/EF_stab
cp $RACINE/test_amont.data test.data
sed "s/amont/EF_stab { }/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/python ..\/..\/propertiesGeometry.py/ /" post_run > modifie.data
mv modifie.data post_run
sed "s/cp propertiesGeometry.dat ..\/../ /" post_run > modifie.data
mv modifie.data post_run
#
#	EF_stab alpha=0.2
#
cd $RACINE/N0/EF_stab02
cp $RACINE/test_amont.data test.data
sed "s/amont/EF_stab { alpha 0.2 }/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/python ..\/..\/propertiesGeometry.py/ /" post_run > modifie.data
mv modifie.data post_run
sed "s/cp propertiesGeometry.dat ..\/../ /" post_run > modifie.data
mv modifie.data post_run
#
#	Muscl
#
cd $RACINE/N0/Muscl
cp $RACINE/test_amont.data test.data
sed "s/amont/muscl/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/python ..\/..\/propertiesGeometry.py/ /" post_run > modifie.data
mv modifie.data post_run
sed "s/cp propertiesGeometry.dat ..\/../ /" post_run > modifie.data
mv modifie.data post_run

#maillage N1
#-----------
#      Amont
cd $RACINE/N1/Amont
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 7 3/" test.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.5 0. 0.5 2/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/0.3 0.0/0.3 1.0/" post_run > modifie.data
mv modifie.data post_run
#
#      EF_stab alpha=1
#
cd $RACINE/N1/EF_stab
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 7 3/" test.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.5 0. 0.5 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { }/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/python ..\/..\/propertiesGeometry.py/ /" post_run > modifie.data
mv modifie.data post_run
sed "s/cp propertiesGeometry.dat ..\/../ /" post_run > modifie.data
mv modifie.data post_run
#
#      EF_stab alpha=0.2
#
cd $RACINE/N1/EF_stab02
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 7 3/" test.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.5 0. 0.5 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { alpha 0.2 }/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/python ..\/..\/propertiesGeometry.py/ /" post_run > modifie.data
mv modifie.data post_run
sed "s/cp propertiesGeometry.dat ..\/../ /" post_run > modifie.data
mv modifie.data post_run
#
#	Muscl
#
cd $RACINE/N1/Muscl
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 7 3/" test.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.5 0. 0.5 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/muscl/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/python ..\/..\/propertiesGeometry.py/ /" post_run > modifie.data
mv modifie.data post_run
sed "s/cp propertiesGeometry.dat ..\/../ /" post_run > modifie.data
mv modifie.data post_run
###
#maillage N2
#-----------
#      Amont
cd $RACINE/N2/Amont
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 13 5/" test.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.25 0. 0.25 2/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/0.3 0.0/0.25 2.0/" post_run > modifie.data
mv modifie.data post_run
sed "s/0.3/0.25/" post_run > modifie.data
mv modifie.data post_run
#
#      EF_stab alpha=1
#
cd $RACINE/N2/EF_stab
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 13 5/" test.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.25 0. 0.25 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { }/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/python ..\/..\/propertiesGeometry.py/ /" post_run > modifie.data
mv modifie.data post_run
sed "s/cp propertiesGeometry.dat ..\/../ /" post_run > modifie.data
mv modifie.data post_run
sed "s/0.3/0.25/" post_run > modifie.data
mv modifie.data post_run
#
#      EF_stab alpha=0.2
#
cd $RACINE/N2/EF_stab02
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 13 5/" test.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.25 0. 0.25 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { alpha 0.2 }/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/python ..\/..\/propertiesGeometry.py/ /" post_run > modifie.data
mv modifie.data post_run
sed "s/cp propertiesGeometry.dat ..\/../ /" post_run > modifie.data
mv modifie.data post_run
sed "s/0.3/0.25/" post_run > modifie.data
mv modifie.data post_run
#
#	Muscl
#
cd $RACINE/N2/Muscl
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 13 5/" test.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.25 0. 0.25 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/muscl/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/python ..\/..\/propertiesGeometry.py/ /" post_run > modifie.data
mv modifie.data post_run
sed "s/cp propertiesGeometry.dat ..\/../ /" post_run > modifie.data
mv modifie.data post_run
sed "s/0.3/0.25/" post_run > modifie.data
mv modifie.data post_run


###
#maillage N3
#-----------
#      Amont
cd $RACINE/N3/Amont
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 25 9/" test.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.125 0. 0.125 2/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/0.3 0.0/0.3 3.0/" post_run > modifie.data
mv modifie.data post_run
sed "s/0.3/0.25/" post_run > modifie.data
mv modifie.data post_run
#
#      EF_stab alpha=1
#
cd $RACINE/N3/EF_stab
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 25 9/" test.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.125 0. 0.125 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { }/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/python ..\/..\/propertiesGeometry.py/ /" post_run > modifie.data
mv modifie.data post_run
sed "s/cp propertiesGeometry.dat ..\/../ /" post_run > modifie.data
mv modifie.data post_run
#
#      EF_stab alpha=0.2
#
cd $RACINE/N3/EF_stab02
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 25 9/" test.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.125 0. 0.125 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { alpha 0.2 }/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/python ..\/..\/propertiesGeometry.py/ /" post_run > modifie.data
mv modifie.data post_run
sed "s/cp propertiesGeometry.dat ..\/../ /" post_run > modifie.data
mv modifie.data post_run
#
#	Muscl
#
cd $RACINE/N3/Muscl
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 25 9/" test.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.125 0. 0.125 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/muscl/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/python ..\/..\/propertiesGeometry.py/ /" post_run > modifie.data
mv modifie.data post_run
sed "s/cp propertiesGeometry.dat ..\/../ /" post_run > modifie.data
mv modifie.data post_run

###
#maillage N4
#-----------
#      Amont
cd $RACINE/N4/Amont
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 49 17/" test.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.0625 0. 0.0625 2/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/0.3 0.0/0.3 4.0/" post_run > modifie.data
mv modifie.data post_run
sed "s/0.3/0.25/" post_run > modifie.data
mv modifie.data post_run
#
#      EF_stab alpha=1
#
cd $RACINE/N4/EF_stab
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 49 17/" test.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.0625 0. 0.0625 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { }/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/python ..\/..\/propertiesGeometry.py/ /" post_run > modifie.data
mv modifie.data post_run
sed "s/cp propertiesGeometry.dat ..\/../ /" post_run > modifie.data
mv modifie.data post_run
#
#      EF_stab alpha=0.2
#
cd $RACINE/N4/EF_stab02
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 49 17/" test.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.0625 0. 0.0625 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { alpha 0.2 }/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/python ..\/..\/propertiesGeometry.py/ /" post_run > modifie.data
mv modifie.data post_run
sed "s/cp propertiesGeometry.dat ..\/../ /" post_run > modifie.data
mv modifie.data post_run

#
#	Muscl
#
cd $RACINE/N4/Muscl
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 49 17/" test.data > modifie.data
mv modifie.data test.data
sed "s/1. 0. 1. 2/0.0625 0. 0.0625 2/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/muscl/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/python ..\/..\/propertiesGeometry.py/ /" post_run > modifie.data
mv modifie.data post_run
sed "s/cp propertiesGeometry.dat ..\/../ /" post_run > modifie.data
mv modifie.data post_run

###
#maillage N5
#-----------
#      Amont
cd $RACINE/N5/Amont
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 97 33/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/0.3 0.0/0.3 5.0/" post_run > modifie.data
mv modifie.data post_run
sed "s/0.3/0.25/" post_run > modifie.data
mv modifie.data post_run
#
#      EF_stab alpha=1
#
cd $RACINE/N5/EF_stab
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 97 33/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { }/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/python ..\/..\/propertiesGeometry.py/ /" post_run > modifie.data
mv modifie.data post_run
sed "s/cp propertiesGeometry.dat ..\/../ /" post_run > modifie.data
mv modifie.data post_run
#
#      EF_stab alpha=0.2
#
cd $RACINE/N5/EF_stab02
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 97 33/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/EF_stab { alpha 0.2 }/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/python ..\/..\/propertiesGeometry.py/ /" post_run > modifie.data
mv modifie.data post_run
sed "s/cp propertiesGeometry.dat ..\/../ /" post_run > modifie.data
mv modifie.data post_run
#
#	Muscl
#
cd $RACINE/N5/Muscl
cp $RACINE/test_amont.data test.data
sed "s/Nombre_de_Noeuds 4 2/Nombre_de_Noeuds 97 33/" test.data > modifie.data
mv modifie.data test.data
sed "s/amont/muscl/" test.data > modifie.data
mv modifie.data test.data
cp $RACINE/post_run .
sed "s/python ..\/..\/propertiesGeometry.py/ /" post_run > modifie.data
mv modifie.data post_run
sed "s/cp propertiesGeometry.dat ..\/../ /" post_run > modifie.data
mv modifie.data post_run

